/*
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/* This file was automatically generated --- DO NOT EDIT */
/* Generated on Wed Feb  5 14:50:36 IST 2020 */

#include "dft/codelet-dft.h"



#if defined(ARCH_PREFERS_FMA) || defined(ISA_EXTENSION_PREFERS_FMA)

/* Generated by: ../../../genfft/gen_twidsq_c.native -fma -simd -compact -variables 4 -pipeline-latency 8 -n 10 -dif -name q1fv_10 -include dft/simd/q1f.h */

/*
 * This function contains 510 FP additions, 400 FP multiplications,
 * (or, 330 additions, 220 multiplications, 180 fused multiply/add),
 * 118 stack variables, 4 constants, and 200 memory accesses
 */
#include "dft/simd/q1f.h"

static void q1fv_10(R * ri, R * ii, const R * W, stride rs, stride vs, INT mb, INT me, INT ms)
{
DVK(KP559016994, +0.559016994374947424102293417182819058860154590);
DVK(KP250000000, +0.250000000000000000000000000000000000000000000);
DVK(KP618033988, +0.618033988749894848204586834365638117720309180);
DVK(KP951056516, +0.951056516295153572116439333379382143405698634);
{
INT m;
R * x;
x = ri;
for (m = mb, W = W + (mb * ((TWVL/VL) * 18)); m < me; m = m + VL, x = x + (VL * ms), W = W + (TWVL * 18), MAKE_VOLATILE_STRIDE(20, rs), MAKE_VOLATILE_STRIDE(20, vs)){
V T3, Tw, TS, T1l, T4a, T4D, T7s, T7V, T3l, T3O, T4Z, T5s, T5O, T6h, T6D;
V T76, T2w, T2Z, T1H, T2a, Tm, Tn, TI, TH, TD, TF, Ti, Tk, T1b, T1c;
V T1x, T1w, T1s, T1u, T17, T19, T4t, T4u, T4P, T4O, T4K, T4M, T4p, T4r, T7L;
V T7M, T87, T86, T82, T84, T7H, T7J, T3E, T3F, T40, T3Z, T3V, T3X, T3A, T3C;
V T5i, T5j, T5E, T5D, T5z, T5B, T5e, T5g, T67, T68, T6t, T6s, T6o, T6q, T63;
V T65, T6W, T6X, T7i, T7h, T7d, T7f, T6S, T6U, T2P, T2Q, T3b, T3a, T36, T38;
V T2L, T2N, T20, T21, T2m, T2l, T2h, T2j, T1W, T1Y;
{
V T48, T49, T6B, T6C;
{
V T1, T2, TQ, TR;
T1 = LD(&(x[0]), ms, &(x[0]));
T2 = LD(&(x[WS(rs, 5)]), ms, &(x[WS(rs, 1)]));
T3 = VSUB(T1, T2);
Tw = VADD(T1, T2);
TQ = LD(&(x[WS(vs, 1)]), ms, &(x[WS(vs, 1)]));
TR = LD(&(x[WS(vs, 1) + WS(rs, 5)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
TS = VSUB(TQ, TR);
T1l = VADD(TQ, TR);
}
T48 = LD(&(x[WS(vs, 5)]), ms, &(x[WS(vs, 5)]));
T49 = LD(&(x[WS(vs, 5) + WS(rs, 5)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4a = VSUB(T48, T49);
T4D = VADD(T48, T49);
{
V T7q, T7r, T3j, T3k;
T7q = LD(&(x[WS(vs, 9)]), ms, &(x[WS(vs, 9)]));
T7r = LD(&(x[WS(vs, 9) + WS(rs, 5)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7s = VSUB(T7q, T7r);
T7V = VADD(T7q, T7r);
T3j = LD(&(x[WS(vs, 4)]), ms, &(x[WS(vs, 4)]));
T3k = LD(&(x[WS(vs, 4) + WS(rs, 5)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3l = VSUB(T3j, T3k);
T3O = VADD(T3j, T3k);
}
{
V T4X, T4Y, T5M, T5N;
T4X = LD(&(x[WS(vs, 6)]), ms, &(x[WS(vs, 6)]));
T4Y = LD(&(x[WS(vs, 6) + WS(rs, 5)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T4Z = VSUB(T4X, T4Y);
T5s = VADD(T4X, T4Y);
T5M = LD(&(x[WS(vs, 7)]), ms, &(x[WS(vs, 7)]));
T5N = LD(&(x[WS(vs, 7) + WS(rs, 5)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5O = VSUB(T5M, T5N);
T6h = VADD(T5M, T5N);
}
T6B = LD(&(x[WS(vs, 8)]), ms, &(x[WS(vs, 8)]));
T6C = LD(&(x[WS(vs, 8) + WS(rs, 5)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6D = VSUB(T6B, T6C);
T76 = VADD(T6B, T6C);
{
V T2u, T2v, T1F, T1G;
T2u = LD(&(x[WS(vs, 3)]), ms, &(x[WS(vs, 3)]));
T2v = LD(&(x[WS(vs, 3) + WS(rs, 5)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2w = VSUB(T2u, T2v);
T2Z = VADD(T2u, T2v);
T1F = LD(&(x[WS(vs, 2)]), ms, &(x[WS(vs, 2)]));
T1G = LD(&(x[WS(vs, 2) + WS(rs, 5)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1H = VSUB(T1F, T1G);
T2a = VADD(T1F, T1G);
}
}
{
V T6, Tx, Tg, TB, T9, Ty, Td, TA;
{
V T4, T5, Te, Tf;
T4 = LD(&(x[WS(rs, 2)]), ms, &(x[0]));
T5 = LD(&(x[WS(rs, 7)]), ms, &(x[WS(rs, 1)]));
T6 = VSUB(T4, T5);
Tx = VADD(T4, T5);
Te = LD(&(x[WS(rs, 6)]), ms, &(x[0]));
Tf = LD(&(x[WS(rs, 1)]), ms, &(x[WS(rs, 1)]));
Tg = VSUB(Te, Tf);
TB = VADD(Te, Tf);
}
{
V T7, T8, Tb, Tc;
T7 = LD(&(x[WS(rs, 8)]), ms, &(x[0]));
T8 = LD(&(x[WS(rs, 3)]), ms, &(x[WS(rs, 1)]));
T9 = VSUB(T7, T8);
Ty = VADD(T7, T8);
Tb = LD(&(x[WS(rs, 4)]), ms, &(x[0]));
Tc = LD(&(x[WS(rs, 9)]), ms, &(x[WS(rs, 1)]));
Td = VSUB(Tb, Tc);
TA = VADD(Tb, Tc);
}
Tm = VSUB(T6, T9);
Tn = VSUB(Td, Tg);
TI = VSUB(Tx, Ty);
TH = VSUB(TA, TB);
{
V Tz, TC, Ta, Th;
Tz = VADD(Tx, Ty);
TC = VADD(TA, TB);
TD = VADD(Tz, TC);
TF = VSUB(Tz, TC);
Ta = VADD(T6, T9);
Th = VADD(Td, Tg);
Ti = VADD(Ta, Th);
Tk = VSUB(Ta, Th);
}
}
{
V TV, T1m, T15, T1q, TY, T1n, T12, T1p;
{
V TT, TU, T13, T14;
TT = LD(&(x[WS(vs, 1) + WS(rs, 2)]), ms, &(x[WS(vs, 1)]));
TU = LD(&(x[WS(vs, 1) + WS(rs, 7)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
TV = VSUB(TT, TU);
T1m = VADD(TT, TU);
T13 = LD(&(x[WS(vs, 1) + WS(rs, 6)]), ms, &(x[WS(vs, 1)]));
T14 = LD(&(x[WS(vs, 1) + WS(rs, 1)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T15 = VSUB(T13, T14);
T1q = VADD(T13, T14);
}
{
V TW, TX, T10, T11;
TW = LD(&(x[WS(vs, 1) + WS(rs, 8)]), ms, &(x[WS(vs, 1)]));
TX = LD(&(x[WS(vs, 1) + WS(rs, 3)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
TY = VSUB(TW, TX);
T1n = VADD(TW, TX);
T10 = LD(&(x[WS(vs, 1) + WS(rs, 4)]), ms, &(x[WS(vs, 1)]));
T11 = LD(&(x[WS(vs, 1) + WS(rs, 9)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T12 = VSUB(T10, T11);
T1p = VADD(T10, T11);
}
T1b = VSUB(TV, TY);
T1c = VSUB(T12, T15);
T1x = VSUB(T1m, T1n);
T1w = VSUB(T1p, T1q);
{
V T1o, T1r, TZ, T16;
T1o = VADD(T1m, T1n);
T1r = VADD(T1p, T1q);
T1s = VADD(T1o, T1r);
T1u = VSUB(T1o, T1r);
TZ = VADD(TV, TY);
T16 = VADD(T12, T15);
T17 = VADD(TZ, T16);
T19 = VSUB(TZ, T16);
}
}
{
V T4d, T4E, T4n, T4I, T4g, T4F, T4k, T4H;
{
V T4b, T4c, T4l, T4m;
T4b = LD(&(x[WS(vs, 5) + WS(rs, 2)]), ms, &(x[WS(vs, 5)]));
T4c = LD(&(x[WS(vs, 5) + WS(rs, 7)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4d = VSUB(T4b, T4c);
T4E = VADD(T4b, T4c);
T4l = LD(&(x[WS(vs, 5) + WS(rs, 6)]), ms, &(x[WS(vs, 5)]));
T4m = LD(&(x[WS(vs, 5) + WS(rs, 1)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4n = VSUB(T4l, T4m);
T4I = VADD(T4l, T4m);
}
{
V T4e, T4f, T4i, T4j;
T4e = LD(&(x[WS(vs, 5) + WS(rs, 8)]), ms, &(x[WS(vs, 5)]));
T4f = LD(&(x[WS(vs, 5) + WS(rs, 3)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4g = VSUB(T4e, T4f);
T4F = VADD(T4e, T4f);
T4i = LD(&(x[WS(vs, 5) + WS(rs, 4)]), ms, &(x[WS(vs, 5)]));
T4j = LD(&(x[WS(vs, 5) + WS(rs, 9)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4k = VSUB(T4i, T4j);
T4H = VADD(T4i, T4j);
}
T4t = VSUB(T4d, T4g);
T4u = VSUB(T4k, T4n);
T4P = VSUB(T4E, T4F);
T4O = VSUB(T4H, T4I);
{
V T4G, T4J, T4h, T4o;
T4G = VADD(T4E, T4F);
T4J = VADD(T4H, T4I);
T4K = VADD(T4G, T4J);
T4M = VSUB(T4G, T4J);
T4h = VADD(T4d, T4g);
T4o = VADD(T4k, T4n);
T4p = VADD(T4h, T4o);
T4r = VSUB(T4h, T4o);
}
}
{
V T7v, T7W, T7F, T80, T7y, T7X, T7C, T7Z;
{
V T7t, T7u, T7D, T7E;
T7t = LD(&(x[WS(vs, 9) + WS(rs, 2)]), ms, &(x[WS(vs, 9)]));
T7u = LD(&(x[WS(vs, 9) + WS(rs, 7)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7v = VSUB(T7t, T7u);
T7W = VADD(T7t, T7u);
T7D = LD(&(x[WS(vs, 9) + WS(rs, 6)]), ms, &(x[WS(vs, 9)]));
T7E = LD(&(x[WS(vs, 9) + WS(rs, 1)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7F = VSUB(T7D, T7E);
T80 = VADD(T7D, T7E);
}
{
V T7w, T7x, T7A, T7B;
T7w = LD(&(x[WS(vs, 9) + WS(rs, 8)]), ms, &(x[WS(vs, 9)]));
T7x = LD(&(x[WS(vs, 9) + WS(rs, 3)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7y = VSUB(T7w, T7x);
T7X = VADD(T7w, T7x);
T7A = LD(&(x[WS(vs, 9) + WS(rs, 4)]), ms, &(x[WS(vs, 9)]));
T7B = LD(&(x[WS(vs, 9) + WS(rs, 9)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7C = VSUB(T7A, T7B);
T7Z = VADD(T7A, T7B);
}
T7L = VSUB(T7v, T7y);
T7M = VSUB(T7C, T7F);
T87 = VSUB(T7W, T7X);
T86 = VSUB(T7Z, T80);
{
V T7Y, T81, T7z, T7G;
T7Y = VADD(T7W, T7X);
T81 = VADD(T7Z, T80);
T82 = VADD(T7Y, T81);
T84 = VSUB(T7Y, T81);
T7z = VADD(T7v, T7y);
T7G = VADD(T7C, T7F);
T7H = VADD(T7z, T7G);
T7J = VSUB(T7z, T7G);
}
}
{
V T3o, T3P, T3y, T3T, T3r, T3Q, T3v, T3S;
{
V T3m, T3n, T3w, T3x;
T3m = LD(&(x[WS(vs, 4) + WS(rs, 2)]), ms, &(x[WS(vs, 4)]));
T3n = LD(&(x[WS(vs, 4) + WS(rs, 7)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3o = VSUB(T3m, T3n);
T3P = VADD(T3m, T3n);
T3w = LD(&(x[WS(vs, 4) + WS(rs, 6)]), ms, &(x[WS(vs, 4)]));
T3x = LD(&(x[WS(vs, 4) + WS(rs, 1)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3y = VSUB(T3w, T3x);
T3T = VADD(T3w, T3x);
}
{
V T3p, T3q, T3t, T3u;
T3p = LD(&(x[WS(vs, 4) + WS(rs, 8)]), ms, &(x[WS(vs, 4)]));
T3q = LD(&(x[WS(vs, 4) + WS(rs, 3)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3r = VSUB(T3p, T3q);
T3Q = VADD(T3p, T3q);
T3t = LD(&(x[WS(vs, 4) + WS(rs, 4)]), ms, &(x[WS(vs, 4)]));
T3u = LD(&(x[WS(vs, 4) + WS(rs, 9)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3v = VSUB(T3t, T3u);
T3S = VADD(T3t, T3u);
}
T3E = VSUB(T3o, T3r);
T3F = VSUB(T3v, T3y);
T40 = VSUB(T3P, T3Q);
T3Z = VSUB(T3S, T3T);
{
V T3R, T3U, T3s, T3z;
T3R = VADD(T3P, T3Q);
T3U = VADD(T3S, T3T);
T3V = VADD(T3R, T3U);
T3X = VSUB(T3R, T3U);
T3s = VADD(T3o, T3r);
T3z = VADD(T3v, T3y);
T3A = VADD(T3s, T3z);
T3C = VSUB(T3s, T3z);
}
}
{
V T52, T5t, T5c, T5x, T55, T5u, T59, T5w;
{
V T50, T51, T5a, T5b;
T50 = LD(&(x[WS(vs, 6) + WS(rs, 2)]), ms, &(x[WS(vs, 6)]));
T51 = LD(&(x[WS(vs, 6) + WS(rs, 7)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T52 = VSUB(T50, T51);
T5t = VADD(T50, T51);
T5a = LD(&(x[WS(vs, 6) + WS(rs, 6)]), ms, &(x[WS(vs, 6)]));
T5b = LD(&(x[WS(vs, 6) + WS(rs, 1)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5c = VSUB(T5a, T5b);
T5x = VADD(T5a, T5b);
}
{
V T53, T54, T57, T58;
T53 = LD(&(x[WS(vs, 6) + WS(rs, 8)]), ms, &(x[WS(vs, 6)]));
T54 = LD(&(x[WS(vs, 6) + WS(rs, 3)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T55 = VSUB(T53, T54);
T5u = VADD(T53, T54);
T57 = LD(&(x[WS(vs, 6) + WS(rs, 4)]), ms, &(x[WS(vs, 6)]));
T58 = LD(&(x[WS(vs, 6) + WS(rs, 9)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T59 = VSUB(T57, T58);
T5w = VADD(T57, T58);
}
T5i = VSUB(T52, T55);
T5j = VSUB(T59, T5c);
T5E = VSUB(T5t, T5u);
T5D = VSUB(T5w, T5x);
{
V T5v, T5y, T56, T5d;
T5v = VADD(T5t, T5u);
T5y = VADD(T5w, T5x);
T5z = VADD(T5v, T5y);
T5B = VSUB(T5v, T5y);
T56 = VADD(T52, T55);
T5d = VADD(T59, T5c);
T5e = VADD(T56, T5d);
T5g = VSUB(T56, T5d);
}
}
{
V T5R, T6i, T61, T6m, T5U, T6j, T5Y, T6l;
{
V T5P, T5Q, T5Z, T60;
T5P = LD(&(x[WS(vs, 7) + WS(rs, 2)]), ms, &(x[WS(vs, 7)]));
T5Q = LD(&(x[WS(vs, 7) + WS(rs, 7)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5R = VSUB(T5P, T5Q);
T6i = VADD(T5P, T5Q);
T5Z = LD(&(x[WS(vs, 7) + WS(rs, 6)]), ms, &(x[WS(vs, 7)]));
T60 = LD(&(x[WS(vs, 7) + WS(rs, 1)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T61 = VSUB(T5Z, T60);
T6m = VADD(T5Z, T60);
}
{
V T5S, T5T, T5W, T5X;
T5S = LD(&(x[WS(vs, 7) + WS(rs, 8)]), ms, &(x[WS(vs, 7)]));
T5T = LD(&(x[WS(vs, 7) + WS(rs, 3)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5U = VSUB(T5S, T5T);
T6j = VADD(T5S, T5T);
T5W = LD(&(x[WS(vs, 7) + WS(rs, 4)]), ms, &(x[WS(vs, 7)]));
T5X = LD(&(x[WS(vs, 7) + WS(rs, 9)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5Y = VSUB(T5W, T5X);
T6l = VADD(T5W, T5X);
}
T67 = VSUB(T5R, T5U);
T68 = VSUB(T5Y, T61);
T6t = VSUB(T6i, T6j);
T6s = VSUB(T6l, T6m);
{
V T6k, T6n, T5V, T62;
T6k = VADD(T6i, T6j);
T6n = VADD(T6l, T6m);
T6o = VADD(T6k, T6n);
T6q = VSUB(T6k, T6n);
T5V = VADD(T5R, T5U);
T62 = VADD(T5Y, T61);
T63 = VADD(T5V, T62);
T65 = VSUB(T5V, T62);
}
}
{
V T6G, T77, T6Q, T7b, T6J, T78, T6N, T7a;
{
V T6E, T6F, T6O, T6P;
T6E = LD(&(x[WS(vs, 8) + WS(rs, 2)]), ms, &(x[WS(vs, 8)]));
T6F = LD(&(x[WS(vs, 8) + WS(rs, 7)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6G = VSUB(T6E, T6F);
T77 = VADD(T6E, T6F);
T6O = LD(&(x[WS(vs, 8) + WS(rs, 6)]), ms, &(x[WS(vs, 8)]));
T6P = LD(&(x[WS(vs, 8) + WS(rs, 1)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6Q = VSUB(T6O, T6P);
T7b = VADD(T6O, T6P);
}
{
V T6H, T6I, T6L, T6M;
T6H = LD(&(x[WS(vs, 8) + WS(rs, 8)]), ms, &(x[WS(vs, 8)]));
T6I = LD(&(x[WS(vs, 8) + WS(rs, 3)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6J = VSUB(T6H, T6I);
T78 = VADD(T6H, T6I);
T6L = LD(&(x[WS(vs, 8) + WS(rs, 4)]), ms, &(x[WS(vs, 8)]));
T6M = LD(&(x[WS(vs, 8) + WS(rs, 9)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6N = VSUB(T6L, T6M);
T7a = VADD(T6L, T6M);
}
T6W = VSUB(T6G, T6J);
T6X = VSUB(T6N, T6Q);
T7i = VSUB(T77, T78);
T7h = VSUB(T7a, T7b);
{
V T79, T7c, T6K, T6R;
T79 = VADD(T77, T78);
T7c = VADD(T7a, T7b);
T7d = VADD(T79, T7c);
T7f = VSUB(T79, T7c);
T6K = VADD(T6G, T6J);
T6R = VADD(T6N, T6Q);
T6S = VADD(T6K, T6R);
T6U = VSUB(T6K, T6R);
}
}
{
V T2z, T30, T2J, T34, T2C, T31, T2G, T33;
{
V T2x, T2y, T2H, T2I;
T2x = LD(&(x[WS(vs, 3) + WS(rs, 2)]), ms, &(x[WS(vs, 3)]));
T2y = LD(&(x[WS(vs, 3) + WS(rs, 7)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2z = VSUB(T2x, T2y);
T30 = VADD(T2x, T2y);
T2H = LD(&(x[WS(vs, 3) + WS(rs, 6)]), ms, &(x[WS(vs, 3)]));
T2I = LD(&(x[WS(vs, 3) + WS(rs, 1)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2J = VSUB(T2H, T2I);
T34 = VADD(T2H, T2I);
}
{
V T2A, T2B, T2E, T2F;
T2A = LD(&(x[WS(vs, 3) + WS(rs, 8)]), ms, &(x[WS(vs, 3)]));
T2B = LD(&(x[WS(vs, 3) + WS(rs, 3)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2C = VSUB(T2A, T2B);
T31 = VADD(T2A, T2B);
T2E = LD(&(x[WS(vs, 3) + WS(rs, 4)]), ms, &(x[WS(vs, 3)]));
T2F = LD(&(x[WS(vs, 3) + WS(rs, 9)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2G = VSUB(T2E, T2F);
T33 = VADD(T2E, T2F);
}
T2P = VSUB(T2z, T2C);
T2Q = VSUB(T2G, T2J);
T3b = VSUB(T30, T31);
T3a = VSUB(T33, T34);
{
V T32, T35, T2D, T2K;
T32 = VADD(T30, T31);
T35 = VADD(T33, T34);
T36 = VADD(T32, T35);
T38 = VSUB(T32, T35);
T2D = VADD(T2z, T2C);
T2K = VADD(T2G, T2J);
T2L = VADD(T2D, T2K);
T2N = VSUB(T2D, T2K);
}
}
{
V T1K, T2b, T1U, T2f, T1N, T2c, T1R, T2e;
{
V T1I, T1J, T1S, T1T;
T1I = LD(&(x[WS(vs, 2) + WS(rs, 2)]), ms, &(x[WS(vs, 2)]));
T1J = LD(&(x[WS(vs, 2) + WS(rs, 7)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1K = VSUB(T1I, T1J);
T2b = VADD(T1I, T1J);
T1S = LD(&(x[WS(vs, 2) + WS(rs, 6)]), ms, &(x[WS(vs, 2)]));
T1T = LD(&(x[WS(vs, 2) + WS(rs, 1)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1U = VSUB(T1S, T1T);
T2f = VADD(T1S, T1T);
}
{
V T1L, T1M, T1P, T1Q;
T1L = LD(&(x[WS(vs, 2) + WS(rs, 8)]), ms, &(x[WS(vs, 2)]));
T1M = LD(&(x[WS(vs, 2) + WS(rs, 3)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1N = VSUB(T1L, T1M);
T2c = VADD(T1L, T1M);
T1P = LD(&(x[WS(vs, 2) + WS(rs, 4)]), ms, &(x[WS(vs, 2)]));
T1Q = LD(&(x[WS(vs, 2) + WS(rs, 9)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1R = VSUB(T1P, T1Q);
T2e = VADD(T1P, T1Q);
}
T20 = VSUB(T1K, T1N);
T21 = VSUB(T1R, T1U);
T2m = VSUB(T2b, T2c);
T2l = VSUB(T2e, T2f);
{
V T2d, T2g, T1O, T1V;
T2d = VADD(T2b, T2c);
T2g = VADD(T2e, T2f);
T2h = VADD(T2d, T2g);
T2j = VSUB(T2d, T2g);
T1O = VADD(T1K, T1N);
T1V = VADD(T1R, T1U);
T1W = VADD(T1O, T1V);
T1Y = VSUB(T1O, T1V);
}
}
ST(&(x[0]),VADD(Tw, TD),ms,&(x[0]));
ST(&(x[WS(rs, 9)]),VADD(T7V, T82),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 7)]),VADD(T6h, T6o),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 5)]),VADD(T4D, T4K),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 2)]),VADD(T2a, T2h),ms,&(x[0]));
ST(&(x[WS(rs, 3)]),VADD(T2Z, T36),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 6)]),VADD(T5s, T5z),ms,&(x[0]));
ST(&(x[WS(rs, 4)]),VADD(T3O, T3V),ms,&(x[0]));
ST(&(x[WS(rs, 8)]),VADD(T76, T7d),ms,&(x[0]));
ST(&(x[WS(rs, 1)]),VADD(T1l, T1s),ms,&(x[WS(rs, 1)]));
{
V Tv, T7U, T6g, T4C, T29;
Tv = BYTWJ(&(W[TWVL * 8]),VADD(T3, Ti));
ST(&(x[WS(vs, 5)]),Tv,ms,&(x[WS(vs, 5)]));
T7U = BYTWJ(&(W[TWVL * 8]),VADD(T7s, T7H));
ST(&(x[WS(vs, 5) + WS(rs, 9)]),T7U,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T6g = BYTWJ(&(W[TWVL * 8]),VADD(T5O, T63));
ST(&(x[WS(vs, 5) + WS(rs, 7)]),T6g,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T4C = BYTWJ(&(W[TWVL * 8]),VADD(T4a, T4p));
ST(&(x[WS(vs, 5) + WS(rs, 5)]),T4C,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T29 = BYTWJ(&(W[TWVL * 8]),VADD(T1H, T1W));
ST(&(x[WS(vs, 5) + WS(rs, 2)]),T29,ms,&(x[WS(vs, 5)]));
}
{
V T2Y, T5r, T3N, T75, T1k;
T2Y = BYTWJ(&(W[TWVL * 8]),VADD(T2w, T2L));
ST(&(x[WS(vs, 5) + WS(rs, 3)]),T2Y,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T5r = BYTWJ(&(W[TWVL * 8]),VADD(T4Z, T5e));
ST(&(x[WS(vs, 5) + WS(rs, 6)]),T5r,ms,&(x[WS(vs, 5)]));
T3N = BYTWJ(&(W[TWVL * 8]),VADD(T3l, T3A));
ST(&(x[WS(vs, 5) + WS(rs, 4)]),T3N,ms,&(x[WS(vs, 5)]));
T75 = BYTWJ(&(W[TWVL * 8]),VADD(T6D, T6S));
ST(&(x[WS(vs, 5) + WS(rs, 8)]),T75,ms,&(x[WS(vs, 5)]));
T1k = BYTWJ(&(W[TWVL * 8]),VADD(TS, T17));
ST(&(x[WS(vs, 5) + WS(rs, 1)]),T1k,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
}
{
V To, Ts, Tl, Tr, Tj;
To = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), Tn, Tm));
Ts = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), Tm, Tn));
Tj = VFNMS(LDK(KP250000000), Ti, T3);
Tl = VFMA(LDK(KP559016994), Tk, Tj);
Tr = VFNMS(LDK(KP559016994), Tk, Tj);
{
V Tp, Tu, Tq, Tt;
Tp = BYTWJ(&(W[0]),VFNMSI(To, Tl));
ST(&(x[WS(vs, 1)]),Tp,ms,&(x[WS(vs, 1)]));
Tu = BYTWJ(&(W[TWVL * 12]),VFMAI(Ts, Tr));
ST(&(x[WS(vs, 7)]),Tu,ms,&(x[WS(vs, 7)]));
Tq = BYTWJ(&(W[TWVL * 16]),VFMAI(To, Tl));
ST(&(x[WS(vs, 9)]),Tq,ms,&(x[WS(vs, 9)]));
Tt = BYTWJ(&(W[TWVL * 4]),VFNMSI(Ts, Tr));
ST(&(x[WS(vs, 3)]),Tt,ms,&(x[WS(vs, 3)]));
}
}
{
V T7N, T7R, T7K, T7Q, T7I;
T7N = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T7M, T7L));
T7R = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T7L, T7M));
T7I = VFNMS(LDK(KP250000000), T7H, T7s);
T7K = VFMA(LDK(KP559016994), T7J, T7I);
T7Q = VFNMS(LDK(KP559016994), T7J, T7I);
{
V T7O, T7T, T7P, T7S;
T7O = BYTWJ(&(W[0]),VFNMSI(T7N, T7K));
ST(&(x[WS(vs, 1) + WS(rs, 9)]),T7O,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T7T = BYTWJ(&(W[TWVL * 12]),VFMAI(T7R, T7Q));
ST(&(x[WS(vs, 7) + WS(rs, 9)]),T7T,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T7P = BYTWJ(&(W[TWVL * 16]),VFMAI(T7N, T7K));
ST(&(x[WS(vs, 9) + WS(rs, 9)]),T7P,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T7S = BYTWJ(&(W[TWVL * 4]),VFNMSI(T7R, T7Q));
ST(&(x[WS(vs, 3) + WS(rs, 9)]),T7S,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T69, T6d, T66, T6c, T64;
T69 = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T68, T67));
T6d = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T67, T68));
T64 = VFNMS(LDK(KP250000000), T63, T5O);
T66 = VFMA(LDK(KP559016994), T65, T64);
T6c = VFNMS(LDK(KP559016994), T65, T64);
{
V T6a, T6f, T6b, T6e;
T6a = BYTWJ(&(W[0]),VFNMSI(T69, T66));
ST(&(x[WS(vs, 1) + WS(rs, 7)]),T6a,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T6f = BYTWJ(&(W[TWVL * 12]),VFMAI(T6d, T6c));
ST(&(x[WS(vs, 7) + WS(rs, 7)]),T6f,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T6b = BYTWJ(&(W[TWVL * 16]),VFMAI(T69, T66));
ST(&(x[WS(vs, 9) + WS(rs, 7)]),T6b,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T6e = BYTWJ(&(W[TWVL * 4]),VFNMSI(T6d, T6c));
ST(&(x[WS(vs, 3) + WS(rs, 7)]),T6e,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T4v, T4z, T4s, T4y, T4q;
T4v = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T4u, T4t));
T4z = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T4t, T4u));
T4q = VFNMS(LDK(KP250000000), T4p, T4a);
T4s = VFMA(LDK(KP559016994), T4r, T4q);
T4y = VFNMS(LDK(KP559016994), T4r, T4q);
{
V T4w, T4B, T4x, T4A;
T4w = BYTWJ(&(W[0]),VFNMSI(T4v, T4s));
ST(&(x[WS(vs, 1) + WS(rs, 5)]),T4w,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T4B = BYTWJ(&(W[TWVL * 12]),VFMAI(T4z, T4y));
ST(&(x[WS(vs, 7) + WS(rs, 5)]),T4B,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T4x = BYTWJ(&(W[TWVL * 16]),VFMAI(T4v, T4s));
ST(&(x[WS(vs, 9) + WS(rs, 5)]),T4x,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T4A = BYTWJ(&(W[TWVL * 4]),VFNMSI(T4z, T4y));
ST(&(x[WS(vs, 3) + WS(rs, 5)]),T4A,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T22, T26, T1Z, T25, T1X;
T22 = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T21, T20));
T26 = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T20, T21));
T1X = VFNMS(LDK(KP250000000), T1W, T1H);
T1Z = VFMA(LDK(KP559016994), T1Y, T1X);
T25 = VFNMS(LDK(KP559016994), T1Y, T1X);
{
V T23, T28, T24, T27;
T23 = BYTWJ(&(W[0]),VFNMSI(T22, T1Z));
ST(&(x[WS(vs, 1) + WS(rs, 2)]),T23,ms,&(x[WS(vs, 1)]));
T28 = BYTWJ(&(W[TWVL * 12]),VFMAI(T26, T25));
ST(&(x[WS(vs, 7) + WS(rs, 2)]),T28,ms,&(x[WS(vs, 7)]));
T24 = BYTWJ(&(W[TWVL * 16]),VFMAI(T22, T1Z));
ST(&(x[WS(vs, 9) + WS(rs, 2)]),T24,ms,&(x[WS(vs, 9)]));
T27 = BYTWJ(&(W[TWVL * 4]),VFNMSI(T26, T25));
ST(&(x[WS(vs, 3) + WS(rs, 2)]),T27,ms,&(x[WS(vs, 3)]));
}
}
{
V T2R, T2V, T2O, T2U, T2M;
T2R = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T2Q, T2P));
T2V = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T2P, T2Q));
T2M = VFNMS(LDK(KP250000000), T2L, T2w);
T2O = VFMA(LDK(KP559016994), T2N, T2M);
T2U = VFNMS(LDK(KP559016994), T2N, T2M);
{
V T2S, T2X, T2T, T2W;
T2S = BYTWJ(&(W[0]),VFNMSI(T2R, T2O));
ST(&(x[WS(vs, 1) + WS(rs, 3)]),T2S,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T2X = BYTWJ(&(W[TWVL * 12]),VFMAI(T2V, T2U));
ST(&(x[WS(vs, 7) + WS(rs, 3)]),T2X,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T2T = BYTWJ(&(W[TWVL * 16]),VFMAI(T2R, T2O));
ST(&(x[WS(vs, 9) + WS(rs, 3)]),T2T,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T2W = BYTWJ(&(W[TWVL * 4]),VFNMSI(T2V, T2U));
ST(&(x[WS(vs, 3) + WS(rs, 3)]),T2W,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T5k, T5o, T5h, T5n, T5f;
T5k = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T5j, T5i));
T5o = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T5i, T5j));
T5f = VFNMS(LDK(KP250000000), T5e, T4Z);
T5h = VFMA(LDK(KP559016994), T5g, T5f);
T5n = VFNMS(LDK(KP559016994), T5g, T5f);
{
V T5l, T5q, T5m, T5p;
T5l = BYTWJ(&(W[0]),VFNMSI(T5k, T5h));
ST(&(x[WS(vs, 1) + WS(rs, 6)]),T5l,ms,&(x[WS(vs, 1)]));
T5q = BYTWJ(&(W[TWVL * 12]),VFMAI(T5o, T5n));
ST(&(x[WS(vs, 7) + WS(rs, 6)]),T5q,ms,&(x[WS(vs, 7)]));
T5m = BYTWJ(&(W[TWVL * 16]),VFMAI(T5k, T5h));
ST(&(x[WS(vs, 9) + WS(rs, 6)]),T5m,ms,&(x[WS(vs, 9)]));
T5p = BYTWJ(&(W[TWVL * 4]),VFNMSI(T5o, T5n));
ST(&(x[WS(vs, 3) + WS(rs, 6)]),T5p,ms,&(x[WS(vs, 3)]));
}
}
{
V T3G, T3K, T3D, T3J, T3B;
T3G = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T3F, T3E));
T3K = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T3E, T3F));
T3B = VFNMS(LDK(KP250000000), T3A, T3l);
T3D = VFMA(LDK(KP559016994), T3C, T3B);
T3J = VFNMS(LDK(KP559016994), T3C, T3B);
{
V T3H, T3M, T3I, T3L;
T3H = BYTWJ(&(W[0]),VFNMSI(T3G, T3D));
ST(&(x[WS(vs, 1) + WS(rs, 4)]),T3H,ms,&(x[WS(vs, 1)]));
T3M = BYTWJ(&(W[TWVL * 12]),VFMAI(T3K, T3J));
ST(&(x[WS(vs, 7) + WS(rs, 4)]),T3M,ms,&(x[WS(vs, 7)]));
T3I = BYTWJ(&(W[TWVL * 16]),VFMAI(T3G, T3D));
ST(&(x[WS(vs, 9) + WS(rs, 4)]),T3I,ms,&(x[WS(vs, 9)]));
T3L = BYTWJ(&(W[TWVL * 4]),VFNMSI(T3K, T3J));
ST(&(x[WS(vs, 3) + WS(rs, 4)]),T3L,ms,&(x[WS(vs, 3)]));
}
}
{
V T6Y, T72, T6V, T71, T6T;
T6Y = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T6X, T6W));
T72 = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T6W, T6X));
T6T = VFNMS(LDK(KP250000000), T6S, T6D);
T6V = VFMA(LDK(KP559016994), T6U, T6T);
T71 = VFNMS(LDK(KP559016994), T6U, T6T);
{
V T6Z, T74, T70, T73;
T6Z = BYTWJ(&(W[0]),VFNMSI(T6Y, T6V));
ST(&(x[WS(vs, 1) + WS(rs, 8)]),T6Z,ms,&(x[WS(vs, 1)]));
T74 = BYTWJ(&(W[TWVL * 12]),VFMAI(T72, T71));
ST(&(x[WS(vs, 7) + WS(rs, 8)]),T74,ms,&(x[WS(vs, 7)]));
T70 = BYTWJ(&(W[TWVL * 16]),VFMAI(T6Y, T6V));
ST(&(x[WS(vs, 9) + WS(rs, 8)]),T70,ms,&(x[WS(vs, 9)]));
T73 = BYTWJ(&(W[TWVL * 4]),VFNMSI(T72, T71));
ST(&(x[WS(vs, 3) + WS(rs, 8)]),T73,ms,&(x[WS(vs, 3)]));
}
}
{
V T1d, T1h, T1a, T1g, T18;
T1d = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T1c, T1b));
T1h = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T1b, T1c));
T18 = VFNMS(LDK(KP250000000), T17, TS);
T1a = VFMA(LDK(KP559016994), T19, T18);
T1g = VFNMS(LDK(KP559016994), T19, T18);
{
V T1e, T1j, T1f, T1i;
T1e = BYTWJ(&(W[0]),VFNMSI(T1d, T1a));
ST(&(x[WS(vs, 1) + WS(rs, 1)]),T1e,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T1j = BYTWJ(&(W[TWVL * 12]),VFMAI(T1h, T1g));
ST(&(x[WS(vs, 7) + WS(rs, 1)]),T1j,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T1f = BYTWJ(&(W[TWVL * 16]),VFMAI(T1d, T1a));
ST(&(x[WS(vs, 9) + WS(rs, 1)]),T1f,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T1i = BYTWJ(&(W[TWVL * 4]),VFNMSI(T1h, T1g));
ST(&(x[WS(vs, 3) + WS(rs, 1)]),T1i,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V TJ, TN, TG, TM, TE;
TJ = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), TI, TH));
TN = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), TH, TI));
TE = VFNMS(LDK(KP250000000), TD, Tw);
TG = VFNMS(LDK(KP559016994), TF, TE);
TM = VFMA(LDK(KP559016994), TF, TE);
{
V TK, TP, TL, TO;
TK = BYTWJ(&(W[TWVL * 2]),VFMAI(TJ, TG));
ST(&(x[WS(vs, 2)]),TK,ms,&(x[WS(vs, 2)]));
TP = BYTWJ(&(W[TWVL * 10]),VFNMSI(TN, TM));
ST(&(x[WS(vs, 6)]),TP,ms,&(x[WS(vs, 6)]));
TL = BYTWJ(&(W[TWVL * 14]),VFNMSI(TJ, TG));
ST(&(x[WS(vs, 8)]),TL,ms,&(x[WS(vs, 8)]));
TO = BYTWJ(&(W[TWVL * 6]),VFMAI(TN, TM));
ST(&(x[WS(vs, 4)]),TO,ms,&(x[WS(vs, 4)]));
}
}
{
V T88, T8c, T85, T8b, T83;
T88 = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T87, T86));
T8c = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T86, T87));
T83 = VFNMS(LDK(KP250000000), T82, T7V);
T85 = VFNMS(LDK(KP559016994), T84, T83);
T8b = VFMA(LDK(KP559016994), T84, T83);
{
V T89, T8e, T8a, T8d;
T89 = BYTWJ(&(W[TWVL * 2]),VFMAI(T88, T85));
ST(&(x[WS(vs, 2) + WS(rs, 9)]),T89,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T8e = BYTWJ(&(W[TWVL * 10]),VFNMSI(T8c, T8b));
ST(&(x[WS(vs, 6) + WS(rs, 9)]),T8e,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T8a = BYTWJ(&(W[TWVL * 14]),VFNMSI(T88, T85));
ST(&(x[WS(vs, 8) + WS(rs, 9)]),T8a,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T8d = BYTWJ(&(W[TWVL * 6]),VFMAI(T8c, T8b));
ST(&(x[WS(vs, 4) + WS(rs, 9)]),T8d,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T6u, T6y, T6r, T6x, T6p;
T6u = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T6t, T6s));
T6y = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T6s, T6t));
T6p = VFNMS(LDK(KP250000000), T6o, T6h);
T6r = VFNMS(LDK(KP559016994), T6q, T6p);
T6x = VFMA(LDK(KP559016994), T6q, T6p);
{
V T6v, T6A, T6w, T6z;
T6v = BYTWJ(&(W[TWVL * 2]),VFMAI(T6u, T6r));
ST(&(x[WS(vs, 2) + WS(rs, 7)]),T6v,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T6A = BYTWJ(&(W[TWVL * 10]),VFNMSI(T6y, T6x));
ST(&(x[WS(vs, 6) + WS(rs, 7)]),T6A,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T6w = BYTWJ(&(W[TWVL * 14]),VFNMSI(T6u, T6r));
ST(&(x[WS(vs, 8) + WS(rs, 7)]),T6w,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T6z = BYTWJ(&(W[TWVL * 6]),VFMAI(T6y, T6x));
ST(&(x[WS(vs, 4) + WS(rs, 7)]),T6z,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T4Q, T4U, T4N, T4T, T4L;
T4Q = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T4P, T4O));
T4U = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T4O, T4P));
T4L = VFNMS(LDK(KP250000000), T4K, T4D);
T4N = VFNMS(LDK(KP559016994), T4M, T4L);
T4T = VFMA(LDK(KP559016994), T4M, T4L);
{
V T4R, T4W, T4S, T4V;
T4R = BYTWJ(&(W[TWVL * 2]),VFMAI(T4Q, T4N));
ST(&(x[WS(vs, 2) + WS(rs, 5)]),T4R,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T4W = BYTWJ(&(W[TWVL * 10]),VFNMSI(T4U, T4T));
ST(&(x[WS(vs, 6) + WS(rs, 5)]),T4W,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T4S = BYTWJ(&(W[TWVL * 14]),VFNMSI(T4Q, T4N));
ST(&(x[WS(vs, 8) + WS(rs, 5)]),T4S,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T4V = BYTWJ(&(W[TWVL * 6]),VFMAI(T4U, T4T));
ST(&(x[WS(vs, 4) + WS(rs, 5)]),T4V,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T2n, T2r, T2k, T2q, T2i;
T2n = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T2m, T2l));
T2r = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T2l, T2m));
T2i = VFNMS(LDK(KP250000000), T2h, T2a);
T2k = VFNMS(LDK(KP559016994), T2j, T2i);
T2q = VFMA(LDK(KP559016994), T2j, T2i);
{
V T2o, T2t, T2p, T2s;
T2o = BYTWJ(&(W[TWVL * 2]),VFMAI(T2n, T2k));
ST(&(x[WS(vs, 2) + WS(rs, 2)]),T2o,ms,&(x[WS(vs, 2)]));
T2t = BYTWJ(&(W[TWVL * 10]),VFNMSI(T2r, T2q));
ST(&(x[WS(vs, 6) + WS(rs, 2)]),T2t,ms,&(x[WS(vs, 6)]));
T2p = BYTWJ(&(W[TWVL * 14]),VFNMSI(T2n, T2k));
ST(&(x[WS(vs, 8) + WS(rs, 2)]),T2p,ms,&(x[WS(vs, 8)]));
T2s = BYTWJ(&(W[TWVL * 6]),VFMAI(T2r, T2q));
ST(&(x[WS(vs, 4) + WS(rs, 2)]),T2s,ms,&(x[WS(vs, 4)]));
}
}
{
V T3c, T3g, T39, T3f, T37;
T3c = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T3b, T3a));
T3g = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T3a, T3b));
T37 = VFNMS(LDK(KP250000000), T36, T2Z);
T39 = VFNMS(LDK(KP559016994), T38, T37);
T3f = VFMA(LDK(KP559016994), T38, T37);
{
V T3d, T3i, T3e, T3h;
T3d = BYTWJ(&(W[TWVL * 2]),VFMAI(T3c, T39));
ST(&(x[WS(vs, 2) + WS(rs, 3)]),T3d,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T3i = BYTWJ(&(W[TWVL * 10]),VFNMSI(T3g, T3f));
ST(&(x[WS(vs, 6) + WS(rs, 3)]),T3i,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T3e = BYTWJ(&(W[TWVL * 14]),VFNMSI(T3c, T39));
ST(&(x[WS(vs, 8) + WS(rs, 3)]),T3e,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T3h = BYTWJ(&(W[TWVL * 6]),VFMAI(T3g, T3f));
ST(&(x[WS(vs, 4) + WS(rs, 3)]),T3h,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T5F, T5J, T5C, T5I, T5A;
T5F = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T5E, T5D));
T5J = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T5D, T5E));
T5A = VFNMS(LDK(KP250000000), T5z, T5s);
T5C = VFNMS(LDK(KP559016994), T5B, T5A);
T5I = VFMA(LDK(KP559016994), T5B, T5A);
{
V T5G, T5L, T5H, T5K;
T5G = BYTWJ(&(W[TWVL * 2]),VFMAI(T5F, T5C));
ST(&(x[WS(vs, 2) + WS(rs, 6)]),T5G,ms,&(x[WS(vs, 2)]));
T5L = BYTWJ(&(W[TWVL * 10]),VFNMSI(T5J, T5I));
ST(&(x[WS(vs, 6) + WS(rs, 6)]),T5L,ms,&(x[WS(vs, 6)]));
T5H = BYTWJ(&(W[TWVL * 14]),VFNMSI(T5F, T5C));
ST(&(x[WS(vs, 8) + WS(rs, 6)]),T5H,ms,&(x[WS(vs, 8)]));
T5K = BYTWJ(&(W[TWVL * 6]),VFMAI(T5J, T5I));
ST(&(x[WS(vs, 4) + WS(rs, 6)]),T5K,ms,&(x[WS(vs, 4)]));
}
}
{
V T41, T45, T3Y, T44, T3W;
T41 = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T40, T3Z));
T45 = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T3Z, T40));
T3W = VFNMS(LDK(KP250000000), T3V, T3O);
T3Y = VFNMS(LDK(KP559016994), T3X, T3W);
T44 = VFMA(LDK(KP559016994), T3X, T3W);
{
V T42, T47, T43, T46;
T42 = BYTWJ(&(W[TWVL * 2]),VFMAI(T41, T3Y));
ST(&(x[WS(vs, 2) + WS(rs, 4)]),T42,ms,&(x[WS(vs, 2)]));
T47 = BYTWJ(&(W[TWVL * 10]),VFNMSI(T45, T44));
ST(&(x[WS(vs, 6) + WS(rs, 4)]),T47,ms,&(x[WS(vs, 6)]));
T43 = BYTWJ(&(W[TWVL * 14]),VFNMSI(T41, T3Y));
ST(&(x[WS(vs, 8) + WS(rs, 4)]),T43,ms,&(x[WS(vs, 8)]));
T46 = BYTWJ(&(W[TWVL * 6]),VFMAI(T45, T44));
ST(&(x[WS(vs, 4) + WS(rs, 4)]),T46,ms,&(x[WS(vs, 4)]));
}
}
{
V T7j, T7n, T7g, T7m, T7e;
T7j = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T7i, T7h));
T7n = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T7h, T7i));
T7e = VFNMS(LDK(KP250000000), T7d, T76);
T7g = VFNMS(LDK(KP559016994), T7f, T7e);
T7m = VFMA(LDK(KP559016994), T7f, T7e);
{
V T7k, T7p, T7l, T7o;
T7k = BYTWJ(&(W[TWVL * 2]),VFMAI(T7j, T7g));
ST(&(x[WS(vs, 2) + WS(rs, 8)]),T7k,ms,&(x[WS(vs, 2)]));
T7p = BYTWJ(&(W[TWVL * 10]),VFNMSI(T7n, T7m));
ST(&(x[WS(vs, 6) + WS(rs, 8)]),T7p,ms,&(x[WS(vs, 6)]));
T7l = BYTWJ(&(W[TWVL * 14]),VFNMSI(T7j, T7g));
ST(&(x[WS(vs, 8) + WS(rs, 8)]),T7l,ms,&(x[WS(vs, 8)]));
T7o = BYTWJ(&(W[TWVL * 6]),VFMAI(T7n, T7m));
ST(&(x[WS(vs, 4) + WS(rs, 8)]),T7o,ms,&(x[WS(vs, 4)]));
}
}
{
V T1y, T1C, T1v, T1B, T1t;
T1y = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), T1x, T1w));
T1C = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), T1w, T1x));
T1t = VFNMS(LDK(KP250000000), T1s, T1l);
T1v = VFNMS(LDK(KP559016994), T1u, T1t);
T1B = VFMA(LDK(KP559016994), T1u, T1t);
{
V T1z, T1E, T1A, T1D;
T1z = BYTWJ(&(W[TWVL * 2]),VFMAI(T1y, T1v));
ST(&(x[WS(vs, 2) + WS(rs, 1)]),T1z,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T1E = BYTWJ(&(W[TWVL * 10]),VFNMSI(T1C, T1B));
ST(&(x[WS(vs, 6) + WS(rs, 1)]),T1E,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T1A = BYTWJ(&(W[TWVL * 14]),VFNMSI(T1y, T1v));
ST(&(x[WS(vs, 8) + WS(rs, 1)]),T1A,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T1D = BYTWJ(&(W[TWVL * 6]),VFMAI(T1C, T1B));
ST(&(x[WS(vs, 4) + WS(rs, 1)]),T1D,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
}
}
VLEAVE();}


static const tw_instr twinstr[] = {
VTW(0,1),
VTW(0,2),
VTW(0,3),
VTW(0,4),
VTW(0,5),
VTW(0,6),
VTW(0,7),
VTW(0,8),
VTW(0,9),
{TW_NEXT, VL, 0}};

static const ct_desc desc = {10, XSIMD_STRING("q1fv_10"), twinstr, &GENUS, { 330, 220, 180, 0 }, 0, 0, 0};

void XSIMD(codelet_q1fv_10)(planner *p)
{
X(kdft_difsq_register)(p, q1fv_10, &desc);
}
#else

/* Generated by: ../../../genfft/gen_twidsq_c.native -simd -compact -variables 4 -pipeline-latency 8 -n 10 -dif -name q1fv_10 -include dft/simd/q1f.h */

/*
 * This function contains 510 FP additions, 300 FP multiplications,
 * (or, 450 additions, 240 multiplications, 60 fused multiply/add),
 * 118 stack variables, 4 constants, and 200 memory accesses
 */
#include "dft/simd/q1f.h"

static void q1fv_10(R * ri, R * ii, const R * W, stride rs, stride vs, INT mb, INT me, INT ms)
{
DVK(KP250000000, +0.250000000000000000000000000000000000000000000);
DVK(KP587785252, +0.587785252292473129168705954639072768597652438);
DVK(KP951056516, +0.951056516295153572116439333379382143405698634);
DVK(KP559016994, +0.559016994374947424102293417182819058860154590);
{
INT m;
R * x;
x = ri;
for (m = mb, W = W + (mb * ((TWVL/VL) * 18)); m < me; m = m + VL, x = x + (VL * ms), W = W + (TWVL * 18), MAKE_VOLATILE_STRIDE(20, rs), MAKE_VOLATILE_STRIDE(20, vs)){
V Ti, TD, T17, T1s, T4p, T4K, T7H, T82, T3A, T3V, T5e, T5z, T63, T6o, T6S;
V T7d, T2L, T36, T1W, T2h, Tm, Tn, TB, Ty, TG, TI, Tf, Tj, T1b, T1c;
V T1q, T1n, T1v, T1x, T14, T18, T4t, T4u, T4I, T4F, T4N, T4P, T4m, T4q, T7L;
V T7M, T80, T7X, T85, T87, T7E, T7I, T3E, T3F, T3T, T3Q, T3Y, T40, T3x, T3B;
V T5i, T5j, T5x, T5u, T5C, T5E, T5b, T5f, T67, T68, T6m, T6j, T6r, T6t, T60;
V T64, T6W, T6X, T7b, T78, T7g, T7i, T6P, T6T, T2P, T2Q, T34, T31, T39, T3b;
V T2I, T2M, T20, T21, T2f, T2c, T2k, T2m, T1T, T1X;
{
V T4n, T4o, T6Q, T6R;
{
V Tg, Th, T15, T16;
Tg = LD(&(x[0]), ms, &(x[0]));
Th = LD(&(x[WS(rs, 5)]), ms, &(x[WS(rs, 1)]));
Ti = VSUB(Tg, Th);
TD = VADD(Tg, Th);
T15 = LD(&(x[WS(vs, 1)]), ms, &(x[WS(vs, 1)]));
T16 = LD(&(x[WS(vs, 1) + WS(rs, 5)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T17 = VSUB(T15, T16);
T1s = VADD(T15, T16);
}
T4n = LD(&(x[WS(vs, 5)]), ms, &(x[WS(vs, 5)]));
T4o = LD(&(x[WS(vs, 5) + WS(rs, 5)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4p = VSUB(T4n, T4o);
T4K = VADD(T4n, T4o);
{
V T7F, T7G, T3y, T3z;
T7F = LD(&(x[WS(vs, 9)]), ms, &(x[WS(vs, 9)]));
T7G = LD(&(x[WS(vs, 9) + WS(rs, 5)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7H = VSUB(T7F, T7G);
T82 = VADD(T7F, T7G);
T3y = LD(&(x[WS(vs, 4)]), ms, &(x[WS(vs, 4)]));
T3z = LD(&(x[WS(vs, 4) + WS(rs, 5)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3A = VSUB(T3y, T3z);
T3V = VADD(T3y, T3z);
}
{
V T5c, T5d, T61, T62;
T5c = LD(&(x[WS(vs, 6)]), ms, &(x[WS(vs, 6)]));
T5d = LD(&(x[WS(vs, 6) + WS(rs, 5)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5e = VSUB(T5c, T5d);
T5z = VADD(T5c, T5d);
T61 = LD(&(x[WS(vs, 7)]), ms, &(x[WS(vs, 7)]));
T62 = LD(&(x[WS(vs, 7) + WS(rs, 5)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T63 = VSUB(T61, T62);
T6o = VADD(T61, T62);
}
T6Q = LD(&(x[WS(vs, 8)]), ms, &(x[WS(vs, 8)]));
T6R = LD(&(x[WS(vs, 8) + WS(rs, 5)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6S = VSUB(T6Q, T6R);
T7d = VADD(T6Q, T6R);
{
V T2J, T2K, T1U, T1V;
T2J = LD(&(x[WS(vs, 3)]), ms, &(x[WS(vs, 3)]));
T2K = LD(&(x[WS(vs, 3) + WS(rs, 5)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2L = VSUB(T2J, T2K);
T36 = VADD(T2J, T2K);
T1U = LD(&(x[WS(vs, 2)]), ms, &(x[WS(vs, 2)]));
T1V = LD(&(x[WS(vs, 2) + WS(rs, 5)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1W = VSUB(T1U, T1V);
T2h = VADD(T1U, T1V);
}
}
{
V T3, Tz, Td, Tx, T6, TA, Ta, Tw;
{
V T1, T2, Tb, Tc;
T1 = LD(&(x[WS(rs, 2)]), ms, &(x[0]));
T2 = LD(&(x[WS(rs, 7)]), ms, &(x[WS(rs, 1)]));
T3 = VSUB(T1, T2);
Tz = VADD(T1, T2);
Tb = LD(&(x[WS(rs, 6)]), ms, &(x[0]));
Tc = LD(&(x[WS(rs, 1)]), ms, &(x[WS(rs, 1)]));
Td = VSUB(Tb, Tc);
Tx = VADD(Tb, Tc);
}
{
V T4, T5, T8, T9;
T4 = LD(&(x[WS(rs, 8)]), ms, &(x[0]));
T5 = LD(&(x[WS(rs, 3)]), ms, &(x[WS(rs, 1)]));
T6 = VSUB(T4, T5);
TA = VADD(T4, T5);
T8 = LD(&(x[WS(rs, 4)]), ms, &(x[0]));
T9 = LD(&(x[WS(rs, 9)]), ms, &(x[WS(rs, 1)]));
Ta = VSUB(T8, T9);
Tw = VADD(T8, T9);
}
Tm = VSUB(T3, T6);
Tn = VSUB(Ta, Td);
TB = VSUB(Tz, TA);
Ty = VSUB(Tw, Tx);
{
V TE, TF, T7, Te;
TE = VADD(Tz, TA);
TF = VADD(Tw, Tx);
TG = VADD(TE, TF);
TI = VMUL(LDK(KP559016994), VSUB(TE, TF));
T7 = VADD(T3, T6);
Te = VADD(Ta, Td);
Tf = VMUL(LDK(KP559016994), VSUB(T7, Te));
Tj = VADD(T7, Te);
}
}
{
V TS, T1o, T12, T1m, TV, T1p, TZ, T1l;
{
V TQ, TR, T10, T11;
TQ = LD(&(x[WS(vs, 1) + WS(rs, 2)]), ms, &(x[WS(vs, 1)]));
TR = LD(&(x[WS(vs, 1) + WS(rs, 7)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
TS = VSUB(TQ, TR);
T1o = VADD(TQ, TR);
T10 = LD(&(x[WS(vs, 1) + WS(rs, 6)]), ms, &(x[WS(vs, 1)]));
T11 = LD(&(x[WS(vs, 1) + WS(rs, 1)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T12 = VSUB(T10, T11);
T1m = VADD(T10, T11);
}
{
V TT, TU, TX, TY;
TT = LD(&(x[WS(vs, 1) + WS(rs, 8)]), ms, &(x[WS(vs, 1)]));
TU = LD(&(x[WS(vs, 1) + WS(rs, 3)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
TV = VSUB(TT, TU);
T1p = VADD(TT, TU);
TX = LD(&(x[WS(vs, 1) + WS(rs, 4)]), ms, &(x[WS(vs, 1)]));
TY = LD(&(x[WS(vs, 1) + WS(rs, 9)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
TZ = VSUB(TX, TY);
T1l = VADD(TX, TY);
}
T1b = VSUB(TS, TV);
T1c = VSUB(TZ, T12);
T1q = VSUB(T1o, T1p);
T1n = VSUB(T1l, T1m);
{
V T1t, T1u, TW, T13;
T1t = VADD(T1o, T1p);
T1u = VADD(T1l, T1m);
T1v = VADD(T1t, T1u);
T1x = VMUL(LDK(KP559016994), VSUB(T1t, T1u));
TW = VADD(TS, TV);
T13 = VADD(TZ, T12);
T14 = VMUL(LDK(KP559016994), VSUB(TW, T13));
T18 = VADD(TW, T13);
}
}
{
V T4a, T4G, T4k, T4E, T4d, T4H, T4h, T4D;
{
V T48, T49, T4i, T4j;
T48 = LD(&(x[WS(vs, 5) + WS(rs, 2)]), ms, &(x[WS(vs, 5)]));
T49 = LD(&(x[WS(vs, 5) + WS(rs, 7)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4a = VSUB(T48, T49);
T4G = VADD(T48, T49);
T4i = LD(&(x[WS(vs, 5) + WS(rs, 6)]), ms, &(x[WS(vs, 5)]));
T4j = LD(&(x[WS(vs, 5) + WS(rs, 1)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4k = VSUB(T4i, T4j);
T4E = VADD(T4i, T4j);
}
{
V T4b, T4c, T4f, T4g;
T4b = LD(&(x[WS(vs, 5) + WS(rs, 8)]), ms, &(x[WS(vs, 5)]));
T4c = LD(&(x[WS(vs, 5) + WS(rs, 3)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4d = VSUB(T4b, T4c);
T4H = VADD(T4b, T4c);
T4f = LD(&(x[WS(vs, 5) + WS(rs, 4)]), ms, &(x[WS(vs, 5)]));
T4g = LD(&(x[WS(vs, 5) + WS(rs, 9)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4h = VSUB(T4f, T4g);
T4D = VADD(T4f, T4g);
}
T4t = VSUB(T4a, T4d);
T4u = VSUB(T4h, T4k);
T4I = VSUB(T4G, T4H);
T4F = VSUB(T4D, T4E);
{
V T4L, T4M, T4e, T4l;
T4L = VADD(T4G, T4H);
T4M = VADD(T4D, T4E);
T4N = VADD(T4L, T4M);
T4P = VMUL(LDK(KP559016994), VSUB(T4L, T4M));
T4e = VADD(T4a, T4d);
T4l = VADD(T4h, T4k);
T4m = VMUL(LDK(KP559016994), VSUB(T4e, T4l));
T4q = VADD(T4e, T4l);
}
}
{
V T7s, T7Y, T7C, T7W, T7v, T7Z, T7z, T7V;
{
V T7q, T7r, T7A, T7B;
T7q = LD(&(x[WS(vs, 9) + WS(rs, 2)]), ms, &(x[WS(vs, 9)]));
T7r = LD(&(x[WS(vs, 9) + WS(rs, 7)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7s = VSUB(T7q, T7r);
T7Y = VADD(T7q, T7r);
T7A = LD(&(x[WS(vs, 9) + WS(rs, 6)]), ms, &(x[WS(vs, 9)]));
T7B = LD(&(x[WS(vs, 9) + WS(rs, 1)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7C = VSUB(T7A, T7B);
T7W = VADD(T7A, T7B);
}
{
V T7t, T7u, T7x, T7y;
T7t = LD(&(x[WS(vs, 9) + WS(rs, 8)]), ms, &(x[WS(vs, 9)]));
T7u = LD(&(x[WS(vs, 9) + WS(rs, 3)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7v = VSUB(T7t, T7u);
T7Z = VADD(T7t, T7u);
T7x = LD(&(x[WS(vs, 9) + WS(rs, 4)]), ms, &(x[WS(vs, 9)]));
T7y = LD(&(x[WS(vs, 9) + WS(rs, 9)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T7z = VSUB(T7x, T7y);
T7V = VADD(T7x, T7y);
}
T7L = VSUB(T7s, T7v);
T7M = VSUB(T7z, T7C);
T80 = VSUB(T7Y, T7Z);
T7X = VSUB(T7V, T7W);
{
V T83, T84, T7w, T7D;
T83 = VADD(T7Y, T7Z);
T84 = VADD(T7V, T7W);
T85 = VADD(T83, T84);
T87 = VMUL(LDK(KP559016994), VSUB(T83, T84));
T7w = VADD(T7s, T7v);
T7D = VADD(T7z, T7C);
T7E = VMUL(LDK(KP559016994), VSUB(T7w, T7D));
T7I = VADD(T7w, T7D);
}
}
{
V T3l, T3R, T3v, T3P, T3o, T3S, T3s, T3O;
{
V T3j, T3k, T3t, T3u;
T3j = LD(&(x[WS(vs, 4) + WS(rs, 2)]), ms, &(x[WS(vs, 4)]));
T3k = LD(&(x[WS(vs, 4) + WS(rs, 7)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3l = VSUB(T3j, T3k);
T3R = VADD(T3j, T3k);
T3t = LD(&(x[WS(vs, 4) + WS(rs, 6)]), ms, &(x[WS(vs, 4)]));
T3u = LD(&(x[WS(vs, 4) + WS(rs, 1)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3v = VSUB(T3t, T3u);
T3P = VADD(T3t, T3u);
}
{
V T3m, T3n, T3q, T3r;
T3m = LD(&(x[WS(vs, 4) + WS(rs, 8)]), ms, &(x[WS(vs, 4)]));
T3n = LD(&(x[WS(vs, 4) + WS(rs, 3)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3o = VSUB(T3m, T3n);
T3S = VADD(T3m, T3n);
T3q = LD(&(x[WS(vs, 4) + WS(rs, 4)]), ms, &(x[WS(vs, 4)]));
T3r = LD(&(x[WS(vs, 4) + WS(rs, 9)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T3s = VSUB(T3q, T3r);
T3O = VADD(T3q, T3r);
}
T3E = VSUB(T3l, T3o);
T3F = VSUB(T3s, T3v);
T3T = VSUB(T3R, T3S);
T3Q = VSUB(T3O, T3P);
{
V T3W, T3X, T3p, T3w;
T3W = VADD(T3R, T3S);
T3X = VADD(T3O, T3P);
T3Y = VADD(T3W, T3X);
T40 = VMUL(LDK(KP559016994), VSUB(T3W, T3X));
T3p = VADD(T3l, T3o);
T3w = VADD(T3s, T3v);
T3x = VMUL(LDK(KP559016994), VSUB(T3p, T3w));
T3B = VADD(T3p, T3w);
}
}
{
V T4Z, T5v, T59, T5t, T52, T5w, T56, T5s;
{
V T4X, T4Y, T57, T58;
T4X = LD(&(x[WS(vs, 6) + WS(rs, 2)]), ms, &(x[WS(vs, 6)]));
T4Y = LD(&(x[WS(vs, 6) + WS(rs, 7)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T4Z = VSUB(T4X, T4Y);
T5v = VADD(T4X, T4Y);
T57 = LD(&(x[WS(vs, 6) + WS(rs, 6)]), ms, &(x[WS(vs, 6)]));
T58 = LD(&(x[WS(vs, 6) + WS(rs, 1)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T59 = VSUB(T57, T58);
T5t = VADD(T57, T58);
}
{
V T50, T51, T54, T55;
T50 = LD(&(x[WS(vs, 6) + WS(rs, 8)]), ms, &(x[WS(vs, 6)]));
T51 = LD(&(x[WS(vs, 6) + WS(rs, 3)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T52 = VSUB(T50, T51);
T5w = VADD(T50, T51);
T54 = LD(&(x[WS(vs, 6) + WS(rs, 4)]), ms, &(x[WS(vs, 6)]));
T55 = LD(&(x[WS(vs, 6) + WS(rs, 9)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T56 = VSUB(T54, T55);
T5s = VADD(T54, T55);
}
T5i = VSUB(T4Z, T52);
T5j = VSUB(T56, T59);
T5x = VSUB(T5v, T5w);
T5u = VSUB(T5s, T5t);
{
V T5A, T5B, T53, T5a;
T5A = VADD(T5v, T5w);
T5B = VADD(T5s, T5t);
T5C = VADD(T5A, T5B);
T5E = VMUL(LDK(KP559016994), VSUB(T5A, T5B));
T53 = VADD(T4Z, T52);
T5a = VADD(T56, T59);
T5b = VMUL(LDK(KP559016994), VSUB(T53, T5a));
T5f = VADD(T53, T5a);
}
}
{
V T5O, T6k, T5Y, T6i, T5R, T6l, T5V, T6h;
{
V T5M, T5N, T5W, T5X;
T5M = LD(&(x[WS(vs, 7) + WS(rs, 2)]), ms, &(x[WS(vs, 7)]));
T5N = LD(&(x[WS(vs, 7) + WS(rs, 7)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5O = VSUB(T5M, T5N);
T6k = VADD(T5M, T5N);
T5W = LD(&(x[WS(vs, 7) + WS(rs, 6)]), ms, &(x[WS(vs, 7)]));
T5X = LD(&(x[WS(vs, 7) + WS(rs, 1)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5Y = VSUB(T5W, T5X);
T6i = VADD(T5W, T5X);
}
{
V T5P, T5Q, T5T, T5U;
T5P = LD(&(x[WS(vs, 7) + WS(rs, 8)]), ms, &(x[WS(vs, 7)]));
T5Q = LD(&(x[WS(vs, 7) + WS(rs, 3)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5R = VSUB(T5P, T5Q);
T6l = VADD(T5P, T5Q);
T5T = LD(&(x[WS(vs, 7) + WS(rs, 4)]), ms, &(x[WS(vs, 7)]));
T5U = LD(&(x[WS(vs, 7) + WS(rs, 9)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T5V = VSUB(T5T, T5U);
T6h = VADD(T5T, T5U);
}
T67 = VSUB(T5O, T5R);
T68 = VSUB(T5V, T5Y);
T6m = VSUB(T6k, T6l);
T6j = VSUB(T6h, T6i);
{
V T6p, T6q, T5S, T5Z;
T6p = VADD(T6k, T6l);
T6q = VADD(T6h, T6i);
T6r = VADD(T6p, T6q);
T6t = VMUL(LDK(KP559016994), VSUB(T6p, T6q));
T5S = VADD(T5O, T5R);
T5Z = VADD(T5V, T5Y);
T60 = VMUL(LDK(KP559016994), VSUB(T5S, T5Z));
T64 = VADD(T5S, T5Z);
}
}
{
V T6D, T79, T6N, T77, T6G, T7a, T6K, T76;
{
V T6B, T6C, T6L, T6M;
T6B = LD(&(x[WS(vs, 8) + WS(rs, 2)]), ms, &(x[WS(vs, 8)]));
T6C = LD(&(x[WS(vs, 8) + WS(rs, 7)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6D = VSUB(T6B, T6C);
T79 = VADD(T6B, T6C);
T6L = LD(&(x[WS(vs, 8) + WS(rs, 6)]), ms, &(x[WS(vs, 8)]));
T6M = LD(&(x[WS(vs, 8) + WS(rs, 1)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6N = VSUB(T6L, T6M);
T77 = VADD(T6L, T6M);
}
{
V T6E, T6F, T6I, T6J;
T6E = LD(&(x[WS(vs, 8) + WS(rs, 8)]), ms, &(x[WS(vs, 8)]));
T6F = LD(&(x[WS(vs, 8) + WS(rs, 3)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6G = VSUB(T6E, T6F);
T7a = VADD(T6E, T6F);
T6I = LD(&(x[WS(vs, 8) + WS(rs, 4)]), ms, &(x[WS(vs, 8)]));
T6J = LD(&(x[WS(vs, 8) + WS(rs, 9)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T6K = VSUB(T6I, T6J);
T76 = VADD(T6I, T6J);
}
T6W = VSUB(T6D, T6G);
T6X = VSUB(T6K, T6N);
T7b = VSUB(T79, T7a);
T78 = VSUB(T76, T77);
{
V T7e, T7f, T6H, T6O;
T7e = VADD(T79, T7a);
T7f = VADD(T76, T77);
T7g = VADD(T7e, T7f);
T7i = VMUL(LDK(KP559016994), VSUB(T7e, T7f));
T6H = VADD(T6D, T6G);
T6O = VADD(T6K, T6N);
T6P = VMUL(LDK(KP559016994), VSUB(T6H, T6O));
T6T = VADD(T6H, T6O);
}
}
{
V T2w, T32, T2G, T30, T2z, T33, T2D, T2Z;
{
V T2u, T2v, T2E, T2F;
T2u = LD(&(x[WS(vs, 3) + WS(rs, 2)]), ms, &(x[WS(vs, 3)]));
T2v = LD(&(x[WS(vs, 3) + WS(rs, 7)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2w = VSUB(T2u, T2v);
T32 = VADD(T2u, T2v);
T2E = LD(&(x[WS(vs, 3) + WS(rs, 6)]), ms, &(x[WS(vs, 3)]));
T2F = LD(&(x[WS(vs, 3) + WS(rs, 1)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2G = VSUB(T2E, T2F);
T30 = VADD(T2E, T2F);
}
{
V T2x, T2y, T2B, T2C;
T2x = LD(&(x[WS(vs, 3) + WS(rs, 8)]), ms, &(x[WS(vs, 3)]));
T2y = LD(&(x[WS(vs, 3) + WS(rs, 3)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2z = VSUB(T2x, T2y);
T33 = VADD(T2x, T2y);
T2B = LD(&(x[WS(vs, 3) + WS(rs, 4)]), ms, &(x[WS(vs, 3)]));
T2C = LD(&(x[WS(vs, 3) + WS(rs, 9)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T2D = VSUB(T2B, T2C);
T2Z = VADD(T2B, T2C);
}
T2P = VSUB(T2w, T2z);
T2Q = VSUB(T2D, T2G);
T34 = VSUB(T32, T33);
T31 = VSUB(T2Z, T30);
{
V T37, T38, T2A, T2H;
T37 = VADD(T32, T33);
T38 = VADD(T2Z, T30);
T39 = VADD(T37, T38);
T3b = VMUL(LDK(KP559016994), VSUB(T37, T38));
T2A = VADD(T2w, T2z);
T2H = VADD(T2D, T2G);
T2I = VMUL(LDK(KP559016994), VSUB(T2A, T2H));
T2M = VADD(T2A, T2H);
}
}
{
V T1H, T2d, T1R, T2b, T1K, T2e, T1O, T2a;
{
V T1F, T1G, T1P, T1Q;
T1F = LD(&(x[WS(vs, 2) + WS(rs, 2)]), ms, &(x[WS(vs, 2)]));
T1G = LD(&(x[WS(vs, 2) + WS(rs, 7)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1H = VSUB(T1F, T1G);
T2d = VADD(T1F, T1G);
T1P = LD(&(x[WS(vs, 2) + WS(rs, 6)]), ms, &(x[WS(vs, 2)]));
T1Q = LD(&(x[WS(vs, 2) + WS(rs, 1)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1R = VSUB(T1P, T1Q);
T2b = VADD(T1P, T1Q);
}
{
V T1I, T1J, T1M, T1N;
T1I = LD(&(x[WS(vs, 2) + WS(rs, 8)]), ms, &(x[WS(vs, 2)]));
T1J = LD(&(x[WS(vs, 2) + WS(rs, 3)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1K = VSUB(T1I, T1J);
T2e = VADD(T1I, T1J);
T1M = LD(&(x[WS(vs, 2) + WS(rs, 4)]), ms, &(x[WS(vs, 2)]));
T1N = LD(&(x[WS(vs, 2) + WS(rs, 9)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T1O = VSUB(T1M, T1N);
T2a = VADD(T1M, T1N);
}
T20 = VSUB(T1H, T1K);
T21 = VSUB(T1O, T1R);
T2f = VSUB(T2d, T2e);
T2c = VSUB(T2a, T2b);
{
V T2i, T2j, T1L, T1S;
T2i = VADD(T2d, T2e);
T2j = VADD(T2a, T2b);
T2k = VADD(T2i, T2j);
T2m = VMUL(LDK(KP559016994), VSUB(T2i, T2j));
T1L = VADD(T1H, T1K);
T1S = VADD(T1O, T1R);
T1T = VMUL(LDK(KP559016994), VSUB(T1L, T1S));
T1X = VADD(T1L, T1S);
}
}
ST(&(x[0]),VADD(TD, TG),ms,&(x[0]));
ST(&(x[WS(rs, 9)]),VADD(T82, T85),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 7)]),VADD(T6o, T6r),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 5)]),VADD(T4K, T4N),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 2)]),VADD(T2h, T2k),ms,&(x[0]));
ST(&(x[WS(rs, 3)]),VADD(T36, T39),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 6)]),VADD(T5z, T5C),ms,&(x[0]));
ST(&(x[WS(rs, 4)]),VADD(T3V, T3Y),ms,&(x[0]));
ST(&(x[WS(rs, 8)]),VADD(T7d, T7g),ms,&(x[0]));
ST(&(x[WS(rs, 1)]),VADD(T1s, T1v),ms,&(x[WS(rs, 1)]));
{
V Tv, T7U, T6g, T4C, T29;
Tv = BYTWJ(&(W[TWVL * 8]),VADD(Ti, Tj));
ST(&(x[WS(vs, 5)]),Tv,ms,&(x[WS(vs, 5)]));
T7U = BYTWJ(&(W[TWVL * 8]),VADD(T7H, T7I));
ST(&(x[WS(vs, 5) + WS(rs, 9)]),T7U,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T6g = BYTWJ(&(W[TWVL * 8]),VADD(T63, T64));
ST(&(x[WS(vs, 5) + WS(rs, 7)]),T6g,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T4C = BYTWJ(&(W[TWVL * 8]),VADD(T4p, T4q));
ST(&(x[WS(vs, 5) + WS(rs, 5)]),T4C,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T29 = BYTWJ(&(W[TWVL * 8]),VADD(T1W, T1X));
ST(&(x[WS(vs, 5) + WS(rs, 2)]),T29,ms,&(x[WS(vs, 5)]));
}
{
V T2Y, T5r, T3N, T75, T1k;
T2Y = BYTWJ(&(W[TWVL * 8]),VADD(T2L, T2M));
ST(&(x[WS(vs, 5) + WS(rs, 3)]),T2Y,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
T5r = BYTWJ(&(W[TWVL * 8]),VADD(T5e, T5f));
ST(&(x[WS(vs, 5) + WS(rs, 6)]),T5r,ms,&(x[WS(vs, 5)]));
T3N = BYTWJ(&(W[TWVL * 8]),VADD(T3A, T3B));
ST(&(x[WS(vs, 5) + WS(rs, 4)]),T3N,ms,&(x[WS(vs, 5)]));
T75 = BYTWJ(&(W[TWVL * 8]),VADD(T6S, T6T));
ST(&(x[WS(vs, 5) + WS(rs, 8)]),T75,ms,&(x[WS(vs, 5)]));
T1k = BYTWJ(&(W[TWVL * 8]),VADD(T17, T18));
ST(&(x[WS(vs, 5) + WS(rs, 1)]),T1k,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
}
{
V To, Ts, Tl, Tr, Tk;
To = VBYI(VFMA(LDK(KP951056516), Tm, VMUL(LDK(KP587785252), Tn)));
Ts = VBYI(VFNMS(LDK(KP587785252), Tm, VMUL(LDK(KP951056516), Tn)));
Tk = VFNMS(LDK(KP250000000), Tj, Ti);
Tl = VADD(Tf, Tk);
Tr = VSUB(Tk, Tf);
{
V Tp, Tu, Tq, Tt;
Tp = BYTWJ(&(W[0]),VSUB(Tl, To));
ST(&(x[WS(vs, 1)]),Tp,ms,&(x[WS(vs, 1)]));
Tu = BYTWJ(&(W[TWVL * 12]),VADD(Ts, Tr));
ST(&(x[WS(vs, 7)]),Tu,ms,&(x[WS(vs, 7)]));
Tq = BYTWJ(&(W[TWVL * 16]),VADD(To, Tl));
ST(&(x[WS(vs, 9)]),Tq,ms,&(x[WS(vs, 9)]));
Tt = BYTWJ(&(W[TWVL * 4]),VSUB(Tr, Ts));
ST(&(x[WS(vs, 3)]),Tt,ms,&(x[WS(vs, 3)]));
}
}
{
V T7N, T7R, T7K, T7Q, T7J;
T7N = VBYI(VFMA(LDK(KP951056516), T7L, VMUL(LDK(KP587785252), T7M)));
T7R = VBYI(VFNMS(LDK(KP587785252), T7L, VMUL(LDK(KP951056516), T7M)));
T7J = VFNMS(LDK(KP250000000), T7I, T7H);
T7K = VADD(T7E, T7J);
T7Q = VSUB(T7J, T7E);
{
V T7O, T7T, T7P, T7S;
T7O = BYTWJ(&(W[0]),VSUB(T7K, T7N));
ST(&(x[WS(vs, 1) + WS(rs, 9)]),T7O,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T7T = BYTWJ(&(W[TWVL * 12]),VADD(T7R, T7Q));
ST(&(x[WS(vs, 7) + WS(rs, 9)]),T7T,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T7P = BYTWJ(&(W[TWVL * 16]),VADD(T7N, T7K));
ST(&(x[WS(vs, 9) + WS(rs, 9)]),T7P,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T7S = BYTWJ(&(W[TWVL * 4]),VSUB(T7Q, T7R));
ST(&(x[WS(vs, 3) + WS(rs, 9)]),T7S,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T69, T6d, T66, T6c, T65;
T69 = VBYI(VFMA(LDK(KP951056516), T67, VMUL(LDK(KP587785252), T68)));
T6d = VBYI(VFNMS(LDK(KP587785252), T67, VMUL(LDK(KP951056516), T68)));
T65 = VFNMS(LDK(KP250000000), T64, T63);
T66 = VADD(T60, T65);
T6c = VSUB(T65, T60);
{
V T6a, T6f, T6b, T6e;
T6a = BYTWJ(&(W[0]),VSUB(T66, T69));
ST(&(x[WS(vs, 1) + WS(rs, 7)]),T6a,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T6f = BYTWJ(&(W[TWVL * 12]),VADD(T6d, T6c));
ST(&(x[WS(vs, 7) + WS(rs, 7)]),T6f,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T6b = BYTWJ(&(W[TWVL * 16]),VADD(T69, T66));
ST(&(x[WS(vs, 9) + WS(rs, 7)]),T6b,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T6e = BYTWJ(&(W[TWVL * 4]),VSUB(T6c, T6d));
ST(&(x[WS(vs, 3) + WS(rs, 7)]),T6e,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T4v, T4z, T4s, T4y, T4r;
T4v = VBYI(VFMA(LDK(KP951056516), T4t, VMUL(LDK(KP587785252), T4u)));
T4z = VBYI(VFNMS(LDK(KP587785252), T4t, VMUL(LDK(KP951056516), T4u)));
T4r = VFNMS(LDK(KP250000000), T4q, T4p);
T4s = VADD(T4m, T4r);
T4y = VSUB(T4r, T4m);
{
V T4w, T4B, T4x, T4A;
T4w = BYTWJ(&(W[0]),VSUB(T4s, T4v));
ST(&(x[WS(vs, 1) + WS(rs, 5)]),T4w,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T4B = BYTWJ(&(W[TWVL * 12]),VADD(T4z, T4y));
ST(&(x[WS(vs, 7) + WS(rs, 5)]),T4B,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T4x = BYTWJ(&(W[TWVL * 16]),VADD(T4v, T4s));
ST(&(x[WS(vs, 9) + WS(rs, 5)]),T4x,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T4A = BYTWJ(&(W[TWVL * 4]),VSUB(T4y, T4z));
ST(&(x[WS(vs, 3) + WS(rs, 5)]),T4A,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T22, T26, T1Z, T25, T1Y;
T22 = VBYI(VFMA(LDK(KP951056516), T20, VMUL(LDK(KP587785252), T21)));
T26 = VBYI(VFNMS(LDK(KP587785252), T20, VMUL(LDK(KP951056516), T21)));
T1Y = VFNMS(LDK(KP250000000), T1X, T1W);
T1Z = VADD(T1T, T1Y);
T25 = VSUB(T1Y, T1T);
{
V T23, T28, T24, T27;
T23 = BYTWJ(&(W[0]),VSUB(T1Z, T22));
ST(&(x[WS(vs, 1) + WS(rs, 2)]),T23,ms,&(x[WS(vs, 1)]));
T28 = BYTWJ(&(W[TWVL * 12]),VADD(T26, T25));
ST(&(x[WS(vs, 7) + WS(rs, 2)]),T28,ms,&(x[WS(vs, 7)]));
T24 = BYTWJ(&(W[TWVL * 16]),VADD(T22, T1Z));
ST(&(x[WS(vs, 9) + WS(rs, 2)]),T24,ms,&(x[WS(vs, 9)]));
T27 = BYTWJ(&(W[TWVL * 4]),VSUB(T25, T26));
ST(&(x[WS(vs, 3) + WS(rs, 2)]),T27,ms,&(x[WS(vs, 3)]));
}
}
{
V T2R, T2V, T2O, T2U, T2N;
T2R = VBYI(VFMA(LDK(KP951056516), T2P, VMUL(LDK(KP587785252), T2Q)));
T2V = VBYI(VFNMS(LDK(KP587785252), T2P, VMUL(LDK(KP951056516), T2Q)));
T2N = VFNMS(LDK(KP250000000), T2M, T2L);
T2O = VADD(T2I, T2N);
T2U = VSUB(T2N, T2I);
{
V T2S, T2X, T2T, T2W;
T2S = BYTWJ(&(W[0]),VSUB(T2O, T2R));
ST(&(x[WS(vs, 1) + WS(rs, 3)]),T2S,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T2X = BYTWJ(&(W[TWVL * 12]),VADD(T2V, T2U));
ST(&(x[WS(vs, 7) + WS(rs, 3)]),T2X,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T2T = BYTWJ(&(W[TWVL * 16]),VADD(T2R, T2O));
ST(&(x[WS(vs, 9) + WS(rs, 3)]),T2T,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T2W = BYTWJ(&(W[TWVL * 4]),VSUB(T2U, T2V));
ST(&(x[WS(vs, 3) + WS(rs, 3)]),T2W,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T5k, T5o, T5h, T5n, T5g;
T5k = VBYI(VFMA(LDK(KP951056516), T5i, VMUL(LDK(KP587785252), T5j)));
T5o = VBYI(VFNMS(LDK(KP587785252), T5i, VMUL(LDK(KP951056516), T5j)));
T5g = VFNMS(LDK(KP250000000), T5f, T5e);
T5h = VADD(T5b, T5g);
T5n = VSUB(T5g, T5b);
{
V T5l, T5q, T5m, T5p;
T5l = BYTWJ(&(W[0]),VSUB(T5h, T5k));
ST(&(x[WS(vs, 1) + WS(rs, 6)]),T5l,ms,&(x[WS(vs, 1)]));
T5q = BYTWJ(&(W[TWVL * 12]),VADD(T5o, T5n));
ST(&(x[WS(vs, 7) + WS(rs, 6)]),T5q,ms,&(x[WS(vs, 7)]));
T5m = BYTWJ(&(W[TWVL * 16]),VADD(T5k, T5h));
ST(&(x[WS(vs, 9) + WS(rs, 6)]),T5m,ms,&(x[WS(vs, 9)]));
T5p = BYTWJ(&(W[TWVL * 4]),VSUB(T5n, T5o));
ST(&(x[WS(vs, 3) + WS(rs, 6)]),T5p,ms,&(x[WS(vs, 3)]));
}
}
{
V T3G, T3K, T3D, T3J, T3C;
T3G = VBYI(VFMA(LDK(KP951056516), T3E, VMUL(LDK(KP587785252), T3F)));
T3K = VBYI(VFNMS(LDK(KP587785252), T3E, VMUL(LDK(KP951056516), T3F)));
T3C = VFNMS(LDK(KP250000000), T3B, T3A);
T3D = VADD(T3x, T3C);
T3J = VSUB(T3C, T3x);
{
V T3H, T3M, T3I, T3L;
T3H = BYTWJ(&(W[0]),VSUB(T3D, T3G));
ST(&(x[WS(vs, 1) + WS(rs, 4)]),T3H,ms,&(x[WS(vs, 1)]));
T3M = BYTWJ(&(W[TWVL * 12]),VADD(T3K, T3J));
ST(&(x[WS(vs, 7) + WS(rs, 4)]),T3M,ms,&(x[WS(vs, 7)]));
T3I = BYTWJ(&(W[TWVL * 16]),VADD(T3G, T3D));
ST(&(x[WS(vs, 9) + WS(rs, 4)]),T3I,ms,&(x[WS(vs, 9)]));
T3L = BYTWJ(&(W[TWVL * 4]),VSUB(T3J, T3K));
ST(&(x[WS(vs, 3) + WS(rs, 4)]),T3L,ms,&(x[WS(vs, 3)]));
}
}
{
V T6Y, T72, T6V, T71, T6U;
T6Y = VBYI(VFMA(LDK(KP951056516), T6W, VMUL(LDK(KP587785252), T6X)));
T72 = VBYI(VFNMS(LDK(KP587785252), T6W, VMUL(LDK(KP951056516), T6X)));
T6U = VFNMS(LDK(KP250000000), T6T, T6S);
T6V = VADD(T6P, T6U);
T71 = VSUB(T6U, T6P);
{
V T6Z, T74, T70, T73;
T6Z = BYTWJ(&(W[0]),VSUB(T6V, T6Y));
ST(&(x[WS(vs, 1) + WS(rs, 8)]),T6Z,ms,&(x[WS(vs, 1)]));
T74 = BYTWJ(&(W[TWVL * 12]),VADD(T72, T71));
ST(&(x[WS(vs, 7) + WS(rs, 8)]),T74,ms,&(x[WS(vs, 7)]));
T70 = BYTWJ(&(W[TWVL * 16]),VADD(T6Y, T6V));
ST(&(x[WS(vs, 9) + WS(rs, 8)]),T70,ms,&(x[WS(vs, 9)]));
T73 = BYTWJ(&(W[TWVL * 4]),VSUB(T71, T72));
ST(&(x[WS(vs, 3) + WS(rs, 8)]),T73,ms,&(x[WS(vs, 3)]));
}
}
{
V T1d, T1h, T1a, T1g, T19;
T1d = VBYI(VFMA(LDK(KP951056516), T1b, VMUL(LDK(KP587785252), T1c)));
T1h = VBYI(VFNMS(LDK(KP587785252), T1b, VMUL(LDK(KP951056516), T1c)));
T19 = VFNMS(LDK(KP250000000), T18, T17);
T1a = VADD(T14, T19);
T1g = VSUB(T19, T14);
{
V T1e, T1j, T1f, T1i;
T1e = BYTWJ(&(W[0]),VSUB(T1a, T1d));
ST(&(x[WS(vs, 1) + WS(rs, 1)]),T1e,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
T1j = BYTWJ(&(W[TWVL * 12]),VADD(T1h, T1g));
ST(&(x[WS(vs, 7) + WS(rs, 1)]),T1j,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
T1f = BYTWJ(&(W[TWVL * 16]),VADD(T1d, T1a));
ST(&(x[WS(vs, 9) + WS(rs, 1)]),T1f,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
T1i = BYTWJ(&(W[TWVL * 4]),VSUB(T1g, T1h));
ST(&(x[WS(vs, 3) + WS(rs, 1)]),T1i,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V TC, TM, TJ, TN, TH;
TC = VBYI(VFNMS(LDK(KP587785252), TB, VMUL(LDK(KP951056516), Ty)));
TM = VBYI(VFMA(LDK(KP951056516), TB, VMUL(LDK(KP587785252), Ty)));
TH = VFNMS(LDK(KP250000000), TG, TD);
TJ = VSUB(TH, TI);
TN = VADD(TI, TH);
{
V TK, TP, TL, TO;
TK = BYTWJ(&(W[TWVL * 2]),VADD(TC, TJ));
ST(&(x[WS(vs, 2)]),TK,ms,&(x[WS(vs, 2)]));
TP = BYTWJ(&(W[TWVL * 10]),VSUB(TN, TM));
ST(&(x[WS(vs, 6)]),TP,ms,&(x[WS(vs, 6)]));
TL = BYTWJ(&(W[TWVL * 14]),VSUB(TJ, TC));
ST(&(x[WS(vs, 8)]),TL,ms,&(x[WS(vs, 8)]));
TO = BYTWJ(&(W[TWVL * 6]),VADD(TM, TN));
ST(&(x[WS(vs, 4)]),TO,ms,&(x[WS(vs, 4)]));
}
}
{
V T81, T8b, T88, T8c, T86;
T81 = VBYI(VFNMS(LDK(KP587785252), T80, VMUL(LDK(KP951056516), T7X)));
T8b = VBYI(VFMA(LDK(KP951056516), T80, VMUL(LDK(KP587785252), T7X)));
T86 = VFNMS(LDK(KP250000000), T85, T82);
T88 = VSUB(T86, T87);
T8c = VADD(T87, T86);
{
V T89, T8e, T8a, T8d;
T89 = BYTWJ(&(W[TWVL * 2]),VADD(T81, T88));
ST(&(x[WS(vs, 2) + WS(rs, 9)]),T89,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T8e = BYTWJ(&(W[TWVL * 10]),VSUB(T8c, T8b));
ST(&(x[WS(vs, 6) + WS(rs, 9)]),T8e,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T8a = BYTWJ(&(W[TWVL * 14]),VSUB(T88, T81));
ST(&(x[WS(vs, 8) + WS(rs, 9)]),T8a,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T8d = BYTWJ(&(W[TWVL * 6]),VADD(T8b, T8c));
ST(&(x[WS(vs, 4) + WS(rs, 9)]),T8d,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T6n, T6x, T6u, T6y, T6s;
T6n = VBYI(VFNMS(LDK(KP587785252), T6m, VMUL(LDK(KP951056516), T6j)));
T6x = VBYI(VFMA(LDK(KP951056516), T6m, VMUL(LDK(KP587785252), T6j)));
T6s = VFNMS(LDK(KP250000000), T6r, T6o);
T6u = VSUB(T6s, T6t);
T6y = VADD(T6t, T6s);
{
V T6v, T6A, T6w, T6z;
T6v = BYTWJ(&(W[TWVL * 2]),VADD(T6n, T6u));
ST(&(x[WS(vs, 2) + WS(rs, 7)]),T6v,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T6A = BYTWJ(&(W[TWVL * 10]),VSUB(T6y, T6x));
ST(&(x[WS(vs, 6) + WS(rs, 7)]),T6A,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T6w = BYTWJ(&(W[TWVL * 14]),VSUB(T6u, T6n));
ST(&(x[WS(vs, 8) + WS(rs, 7)]),T6w,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T6z = BYTWJ(&(W[TWVL * 6]),VADD(T6x, T6y));
ST(&(x[WS(vs, 4) + WS(rs, 7)]),T6z,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T4J, T4T, T4Q, T4U, T4O;
T4J = VBYI(VFNMS(LDK(KP587785252), T4I, VMUL(LDK(KP951056516), T4F)));
T4T = VBYI(VFMA(LDK(KP951056516), T4I, VMUL(LDK(KP587785252), T4F)));
T4O = VFNMS(LDK(KP250000000), T4N, T4K);
T4Q = VSUB(T4O, T4P);
T4U = VADD(T4P, T4O);
{
V T4R, T4W, T4S, T4V;
T4R = BYTWJ(&(W[TWVL * 2]),VADD(T4J, T4Q));
ST(&(x[WS(vs, 2) + WS(rs, 5)]),T4R,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T4W = BYTWJ(&(W[TWVL * 10]),VSUB(T4U, T4T));
ST(&(x[WS(vs, 6) + WS(rs, 5)]),T4W,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T4S = BYTWJ(&(W[TWVL * 14]),VSUB(T4Q, T4J));
ST(&(x[WS(vs, 8) + WS(rs, 5)]),T4S,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T4V = BYTWJ(&(W[TWVL * 6]),VADD(T4T, T4U));
ST(&(x[WS(vs, 4) + WS(rs, 5)]),T4V,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T2g, T2q, T2n, T2r, T2l;
T2g = VBYI(VFNMS(LDK(KP587785252), T2f, VMUL(LDK(KP951056516), T2c)));
T2q = VBYI(VFMA(LDK(KP951056516), T2f, VMUL(LDK(KP587785252), T2c)));
T2l = VFNMS(LDK(KP250000000), T2k, T2h);
T2n = VSUB(T2l, T2m);
T2r = VADD(T2m, T2l);
{
V T2o, T2t, T2p, T2s;
T2o = BYTWJ(&(W[TWVL * 2]),VADD(T2g, T2n));
ST(&(x[WS(vs, 2) + WS(rs, 2)]),T2o,ms,&(x[WS(vs, 2)]));
T2t = BYTWJ(&(W[TWVL * 10]),VSUB(T2r, T2q));
ST(&(x[WS(vs, 6) + WS(rs, 2)]),T2t,ms,&(x[WS(vs, 6)]));
T2p = BYTWJ(&(W[TWVL * 14]),VSUB(T2n, T2g));
ST(&(x[WS(vs, 8) + WS(rs, 2)]),T2p,ms,&(x[WS(vs, 8)]));
T2s = BYTWJ(&(W[TWVL * 6]),VADD(T2q, T2r));
ST(&(x[WS(vs, 4) + WS(rs, 2)]),T2s,ms,&(x[WS(vs, 4)]));
}
}
{
V T35, T3f, T3c, T3g, T3a;
T35 = VBYI(VFNMS(LDK(KP587785252), T34, VMUL(LDK(KP951056516), T31)));
T3f = VBYI(VFMA(LDK(KP951056516), T34, VMUL(LDK(KP587785252), T31)));
T3a = VFNMS(LDK(KP250000000), T39, T36);
T3c = VSUB(T3a, T3b);
T3g = VADD(T3b, T3a);
{
V T3d, T3i, T3e, T3h;
T3d = BYTWJ(&(W[TWVL * 2]),VADD(T35, T3c));
ST(&(x[WS(vs, 2) + WS(rs, 3)]),T3d,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T3i = BYTWJ(&(W[TWVL * 10]),VSUB(T3g, T3f));
ST(&(x[WS(vs, 6) + WS(rs, 3)]),T3i,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T3e = BYTWJ(&(W[TWVL * 14]),VSUB(T3c, T35));
ST(&(x[WS(vs, 8) + WS(rs, 3)]),T3e,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T3h = BYTWJ(&(W[TWVL * 6]),VADD(T3f, T3g));
ST(&(x[WS(vs, 4) + WS(rs, 3)]),T3h,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
{
V T5y, T5I, T5F, T5J, T5D;
T5y = VBYI(VFNMS(LDK(KP587785252), T5x, VMUL(LDK(KP951056516), T5u)));
T5I = VBYI(VFMA(LDK(KP951056516), T5x, VMUL(LDK(KP587785252), T5u)));
T5D = VFNMS(LDK(KP250000000), T5C, T5z);
T5F = VSUB(T5D, T5E);
T5J = VADD(T5E, T5D);
{
V T5G, T5L, T5H, T5K;
T5G = BYTWJ(&(W[TWVL * 2]),VADD(T5y, T5F));
ST(&(x[WS(vs, 2) + WS(rs, 6)]),T5G,ms,&(x[WS(vs, 2)]));
T5L = BYTWJ(&(W[TWVL * 10]),VSUB(T5J, T5I));
ST(&(x[WS(vs, 6) + WS(rs, 6)]),T5L,ms,&(x[WS(vs, 6)]));
T5H = BYTWJ(&(W[TWVL * 14]),VSUB(T5F, T5y));
ST(&(x[WS(vs, 8) + WS(rs, 6)]),T5H,ms,&(x[WS(vs, 8)]));
T5K = BYTWJ(&(W[TWVL * 6]),VADD(T5I, T5J));
ST(&(x[WS(vs, 4) + WS(rs, 6)]),T5K,ms,&(x[WS(vs, 4)]));
}
}
{
V T3U, T44, T41, T45, T3Z;
T3U = VBYI(VFNMS(LDK(KP587785252), T3T, VMUL(LDK(KP951056516), T3Q)));
T44 = VBYI(VFMA(LDK(KP951056516), T3T, VMUL(LDK(KP587785252), T3Q)));
T3Z = VFNMS(LDK(KP250000000), T3Y, T3V);
T41 = VSUB(T3Z, T40);
T45 = VADD(T40, T3Z);
{
V T42, T47, T43, T46;
T42 = BYTWJ(&(W[TWVL * 2]),VADD(T3U, T41));
ST(&(x[WS(vs, 2) + WS(rs, 4)]),T42,ms,&(x[WS(vs, 2)]));
T47 = BYTWJ(&(W[TWVL * 10]),VSUB(T45, T44));
ST(&(x[WS(vs, 6) + WS(rs, 4)]),T47,ms,&(x[WS(vs, 6)]));
T43 = BYTWJ(&(W[TWVL * 14]),VSUB(T41, T3U));
ST(&(x[WS(vs, 8) + WS(rs, 4)]),T43,ms,&(x[WS(vs, 8)]));
T46 = BYTWJ(&(W[TWVL * 6]),VADD(T44, T45));
ST(&(x[WS(vs, 4) + WS(rs, 4)]),T46,ms,&(x[WS(vs, 4)]));
}
}
{
V T7c, T7m, T7j, T7n, T7h;
T7c = VBYI(VFNMS(LDK(KP587785252), T7b, VMUL(LDK(KP951056516), T78)));
T7m = VBYI(VFMA(LDK(KP951056516), T7b, VMUL(LDK(KP587785252), T78)));
T7h = VFNMS(LDK(KP250000000), T7g, T7d);
T7j = VSUB(T7h, T7i);
T7n = VADD(T7i, T7h);
{
V T7k, T7p, T7l, T7o;
T7k = BYTWJ(&(W[TWVL * 2]),VADD(T7c, T7j));
ST(&(x[WS(vs, 2) + WS(rs, 8)]),T7k,ms,&(x[WS(vs, 2)]));
T7p = BYTWJ(&(W[TWVL * 10]),VSUB(T7n, T7m));
ST(&(x[WS(vs, 6) + WS(rs, 8)]),T7p,ms,&(x[WS(vs, 6)]));
T7l = BYTWJ(&(W[TWVL * 14]),VSUB(T7j, T7c));
ST(&(x[WS(vs, 8) + WS(rs, 8)]),T7l,ms,&(x[WS(vs, 8)]));
T7o = BYTWJ(&(W[TWVL * 6]),VADD(T7m, T7n));
ST(&(x[WS(vs, 4) + WS(rs, 8)]),T7o,ms,&(x[WS(vs, 4)]));
}
}
{
V T1r, T1B, T1y, T1C, T1w;
T1r = VBYI(VFNMS(LDK(KP587785252), T1q, VMUL(LDK(KP951056516), T1n)));
T1B = VBYI(VFMA(LDK(KP951056516), T1q, VMUL(LDK(KP587785252), T1n)));
T1w = VFNMS(LDK(KP250000000), T1v, T1s);
T1y = VSUB(T1w, T1x);
T1C = VADD(T1x, T1w);
{
V T1z, T1E, T1A, T1D;
T1z = BYTWJ(&(W[TWVL * 2]),VADD(T1r, T1y));
ST(&(x[WS(vs, 2) + WS(rs, 1)]),T1z,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
T1E = BYTWJ(&(W[TWVL * 10]),VSUB(T1C, T1B));
ST(&(x[WS(vs, 6) + WS(rs, 1)]),T1E,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
T1A = BYTWJ(&(W[TWVL * 14]),VSUB(T1y, T1r));
ST(&(x[WS(vs, 8) + WS(rs, 1)]),T1A,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
T1D = BYTWJ(&(W[TWVL * 6]),VADD(T1B, T1C));
ST(&(x[WS(vs, 4) + WS(rs, 1)]),T1D,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
}
}
VLEAVE();}


static const tw_instr twinstr[] = {
VTW(0,1),
VTW(0,2),
VTW(0,3),
VTW(0,4),
VTW(0,5),
VTW(0,6),
VTW(0,7),
VTW(0,8),
VTW(0,9),
{TW_NEXT, VL, 0}};

static const ct_desc desc = {10, XSIMD_STRING("q1fv_10"), twinstr, &GENUS, { 450, 240, 60, 0 }, 0, 0, 0};

void XSIMD(codelet_q1fv_10)(planner *p)
{
X(kdft_difsq_register)(p, q1fv_10, &desc);
}
#endif
