/*
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/* This file was automatically generated --- DO NOT EDIT */
/* Generated on Wed Feb  5 14:50:36 IST 2020 */

#include "dft/codelet-dft.h"



#if defined(ARCH_PREFERS_FMA) || defined(ISA_EXTENSION_PREFERS_FMA)

/* Generated by: ../../../genfft/gen_twidsq_c.native -fma -simd -compact -variables 4 -pipeline-latency 8 -n 12 -dif -name q1fv_12 -include dft/simd/q1f.h */

/*
 * This function contains 708 FP additions, 504 FP multiplications,
 * (or, 492 additions, 288 multiplications, 216 fused multiply/add),
 * 160 stack variables, 2 constants, and 288 memory accesses
 */
#include "dft/simd/q1f.h"

static void q1fv_12(R * ri, R * ii, const R * W, stride rs, stride vs, INT mb, INT me, INT ms)
{
DVK(KP866025403, +0.866025403784438646763723170752936183471402627);
DVK(KP500000000, +0.500000000000000000000000000000000000000000000);
{
INT m;
R * x;
x = ri;
for (m = mb, W = W + (mb * ((TWVL/VL) * 22)); m < me; m = m + VL, x = x + (VL * ms), W = W + (TWVL * 22), MAKE_VOLATILE_STRIDE(24, rs), MAKE_VOLATILE_STRIDE(24, vs)){
V Tt, TO, TF, TN, Tb, TB, T92, T9n, T9e, T9m, T8K, T9a, T8R, T9q, T9d;
V T9p, T8Z, T9b, Ti, TR, TE, TQ, Tq, TC, T2c, T2L, T2y, T2K, T2k, T2w;
V TaL, Tbk, Tb7, Tbj, TaT, Tb5, TaW, Tbh, Tb8, Tbg, TaE, Tb4, T2n, T2I, T2z;
V T2H, T25, T2v, T1f, T1O, T1B, T1N, T1n, T1z, T9O, Tan, Taa, Tam, T9W, Ta8;
V T9Z, Tak, Tab, Taj, T9H, Ta7, T1q, T1L, T1C, T1K, T18, T1y, T3k, T3F, T3w;
V T3E, T32, T3s, T6b, T6w, T6n, T6v, T5T, T6j, T60, T6z, T6m, T6y, T68, T6k;
V T39, T3I, T3v, T3H, T3h, T3t, T53, T5C, T5p, T5B, T5b, T5n, T7U, T8t, T8g;
V T8s, T82, T8e, T85, T8q, T8h, T8p, T7N, T8d, T5e, T5z, T5q, T5y, T4W, T5m;
V T46, T4F, T4s, T4E, T4e, T4q, T6X, T7w, T7j, T7v, T75, T7h, T78, T7t, T7k;
V T7s, T6Q, T7g, T4h, T4C, T4t, T4B, T3Z, T4p;
{
V T1, T6, T4, Tr, T9, Ts, T5, Ta;
T1 = LD(&(x[0]), ms, &(x[0]));
T6 = LD(&(x[WS(rs, 6)]), ms, &(x[0]));
{
V T2, T3, T7, T8;
T2 = LD(&(x[WS(rs, 4)]), ms, &(x[0]));
T3 = LD(&(x[WS(rs, 8)]), ms, &(x[0]));
T4 = VADD(T2, T3);
Tr = VSUB(T3, T2);
T7 = LD(&(x[WS(rs, 10)]), ms, &(x[0]));
T8 = LD(&(x[WS(rs, 2)]), ms, &(x[0]));
T9 = VADD(T7, T8);
Ts = VSUB(T8, T7);
}
Tt = VSUB(Tr, Ts);
TO = VADD(T6, T9);
TF = VADD(Tr, Ts);
TN = VADD(T1, T4);
T5 = VFNMS(LDK(KP500000000), T4, T1);
Ta = VFNMS(LDK(KP500000000), T9, T6);
Tb = VSUB(T5, Ta);
TB = VADD(T5, Ta);
}
{
V T8A, T8F, T8D, T90, T8I, T91, T8E, T8J;
T8A = LD(&(x[WS(vs, 9)]), ms, &(x[WS(vs, 9)]));
T8F = LD(&(x[WS(vs, 9) + WS(rs, 6)]), ms, &(x[WS(vs, 9)]));
{
V T8B, T8C, T8G, T8H;
T8B = LD(&(x[WS(vs, 9) + WS(rs, 4)]), ms, &(x[WS(vs, 9)]));
T8C = LD(&(x[WS(vs, 9) + WS(rs, 8)]), ms, &(x[WS(vs, 9)]));
T8D = VADD(T8B, T8C);
T90 = VSUB(T8C, T8B);
T8G = LD(&(x[WS(vs, 9) + WS(rs, 10)]), ms, &(x[WS(vs, 9)]));
T8H = LD(&(x[WS(vs, 9) + WS(rs, 2)]), ms, &(x[WS(vs, 9)]));
T8I = VADD(T8G, T8H);
T91 = VSUB(T8H, T8G);
}
T92 = VSUB(T90, T91);
T9n = VADD(T8F, T8I);
T9e = VADD(T90, T91);
T9m = VADD(T8A, T8D);
T8E = VFNMS(LDK(KP500000000), T8D, T8A);
T8J = VFNMS(LDK(KP500000000), T8I, T8F);
T8K = VSUB(T8E, T8J);
T9a = VADD(T8E, T8J);
}
{
V T8T, T8W, T8N, T8U, T8Q, T8X, T8V, T8Y;
T8T = LD(&(x[WS(vs, 9) + WS(rs, 3)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8W = LD(&(x[WS(vs, 9) + WS(rs, 9)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
{
V T8L, T8M, T8O, T8P;
T8L = LD(&(x[WS(vs, 9) + WS(rs, 11)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8M = LD(&(x[WS(vs, 9) + WS(rs, 7)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8N = VSUB(T8L, T8M);
T8U = VADD(T8M, T8L);
T8O = LD(&(x[WS(vs, 9) + WS(rs, 1)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8P = LD(&(x[WS(vs, 9) + WS(rs, 5)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8Q = VSUB(T8O, T8P);
T8X = VADD(T8O, T8P);
}
T8R = VADD(T8N, T8Q);
T9q = VADD(T8W, T8X);
T9d = VSUB(T8N, T8Q);
T9p = VADD(T8T, T8U);
T8V = VFNMS(LDK(KP500000000), T8U, T8T);
T8Y = VFNMS(LDK(KP500000000), T8X, T8W);
T8Z = VSUB(T8V, T8Y);
T9b = VADD(T8V, T8Y);
}
{
V Tk, Tn, Te, Tl, Th, To, Tm, Tp;
Tk = LD(&(x[WS(rs, 3)]), ms, &(x[WS(rs, 1)]));
Tn = LD(&(x[WS(rs, 9)]), ms, &(x[WS(rs, 1)]));
{
V Tc, Td, Tf, Tg;
Tc = LD(&(x[WS(rs, 11)]), ms, &(x[WS(rs, 1)]));
Td = LD(&(x[WS(rs, 7)]), ms, &(x[WS(rs, 1)]));
Te = VSUB(Tc, Td);
Tl = VADD(Td, Tc);
Tf = LD(&(x[WS(rs, 1)]), ms, &(x[WS(rs, 1)]));
Tg = LD(&(x[WS(rs, 5)]), ms, &(x[WS(rs, 1)]));
Th = VSUB(Tf, Tg);
To = VADD(Tf, Tg);
}
Ti = VADD(Te, Th);
TR = VADD(Tn, To);
TE = VSUB(Te, Th);
TQ = VADD(Tk, Tl);
Tm = VFNMS(LDK(KP500000000), Tl, Tk);
Tp = VFNMS(LDK(KP500000000), To, Tn);
Tq = VSUB(Tm, Tp);
TC = VADD(Tm, Tp);
}
{
V T2e, T2h, T28, T2f, T2b, T2i, T2g, T2j;
T2e = LD(&(x[WS(vs, 2) + WS(rs, 3)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T2h = LD(&(x[WS(vs, 2) + WS(rs, 9)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
{
V T26, T27, T29, T2a;
T26 = LD(&(x[WS(vs, 2) + WS(rs, 11)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T27 = LD(&(x[WS(vs, 2) + WS(rs, 7)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T28 = VSUB(T26, T27);
T2f = VADD(T27, T26);
T29 = LD(&(x[WS(vs, 2) + WS(rs, 1)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T2a = LD(&(x[WS(vs, 2) + WS(rs, 5)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T2b = VSUB(T29, T2a);
T2i = VADD(T29, T2a);
}
T2c = VADD(T28, T2b);
T2L = VADD(T2h, T2i);
T2y = VSUB(T28, T2b);
T2K = VADD(T2e, T2f);
T2g = VFNMS(LDK(KP500000000), T2f, T2e);
T2j = VFNMS(LDK(KP500000000), T2i, T2h);
T2k = VSUB(T2g, T2j);
T2w = VADD(T2g, T2j);
}
{
V TaN, TaQ, TaH, TaO, TaK, TaR, TaP, TaS;
TaN = LD(&(x[WS(vs, 11) + WS(rs, 3)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaQ = LD(&(x[WS(vs, 11) + WS(rs, 9)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
{
V TaF, TaG, TaI, TaJ;
TaF = LD(&(x[WS(vs, 11) + WS(rs, 11)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaG = LD(&(x[WS(vs, 11) + WS(rs, 7)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaH = VSUB(TaF, TaG);
TaO = VADD(TaG, TaF);
TaI = LD(&(x[WS(vs, 11) + WS(rs, 1)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaJ = LD(&(x[WS(vs, 11) + WS(rs, 5)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaK = VSUB(TaI, TaJ);
TaR = VADD(TaI, TaJ);
}
TaL = VADD(TaH, TaK);
Tbk = VADD(TaQ, TaR);
Tb7 = VSUB(TaH, TaK);
Tbj = VADD(TaN, TaO);
TaP = VFNMS(LDK(KP500000000), TaO, TaN);
TaS = VFNMS(LDK(KP500000000), TaR, TaQ);
TaT = VSUB(TaP, TaS);
Tb5 = VADD(TaP, TaS);
}
{
V Tau, Taz, Tax, TaU, TaC, TaV, Tay, TaD;
Tau = LD(&(x[WS(vs, 11)]), ms, &(x[WS(vs, 11)]));
Taz = LD(&(x[WS(vs, 11) + WS(rs, 6)]), ms, &(x[WS(vs, 11)]));
{
V Tav, Taw, TaA, TaB;
Tav = LD(&(x[WS(vs, 11) + WS(rs, 4)]), ms, &(x[WS(vs, 11)]));
Taw = LD(&(x[WS(vs, 11) + WS(rs, 8)]), ms, &(x[WS(vs, 11)]));
Tax = VADD(Tav, Taw);
TaU = VSUB(Taw, Tav);
TaA = LD(&(x[WS(vs, 11) + WS(rs, 10)]), ms, &(x[WS(vs, 11)]));
TaB = LD(&(x[WS(vs, 11) + WS(rs, 2)]), ms, &(x[WS(vs, 11)]));
TaC = VADD(TaA, TaB);
TaV = VSUB(TaB, TaA);
}
TaW = VSUB(TaU, TaV);
Tbh = VADD(Taz, TaC);
Tb8 = VADD(TaU, TaV);
Tbg = VADD(Tau, Tax);
Tay = VFNMS(LDK(KP500000000), Tax, Tau);
TaD = VFNMS(LDK(KP500000000), TaC, Taz);
TaE = VSUB(Tay, TaD);
Tb4 = VADD(Tay, TaD);
}
{
V T1V, T20, T1Y, T2l, T23, T2m, T1Z, T24;
T1V = LD(&(x[WS(vs, 2)]), ms, &(x[WS(vs, 2)]));
T20 = LD(&(x[WS(vs, 2) + WS(rs, 6)]), ms, &(x[WS(vs, 2)]));
{
V T1W, T1X, T21, T22;
T1W = LD(&(x[WS(vs, 2) + WS(rs, 4)]), ms, &(x[WS(vs, 2)]));
T1X = LD(&(x[WS(vs, 2) + WS(rs, 8)]), ms, &(x[WS(vs, 2)]));
T1Y = VADD(T1W, T1X);
T2l = VSUB(T1X, T1W);
T21 = LD(&(x[WS(vs, 2) + WS(rs, 10)]), ms, &(x[WS(vs, 2)]));
T22 = LD(&(x[WS(vs, 2) + WS(rs, 2)]), ms, &(x[WS(vs, 2)]));
T23 = VADD(T21, T22);
T2m = VSUB(T22, T21);
}
T2n = VSUB(T2l, T2m);
T2I = VADD(T20, T23);
T2z = VADD(T2l, T2m);
T2H = VADD(T1V, T1Y);
T1Z = VFNMS(LDK(KP500000000), T1Y, T1V);
T24 = VFNMS(LDK(KP500000000), T23, T20);
T25 = VSUB(T1Z, T24);
T2v = VADD(T1Z, T24);
}
{
V T1h, T1k, T1b, T1i, T1e, T1l, T1j, T1m;
T1h = LD(&(x[WS(vs, 1) + WS(rs, 3)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1k = LD(&(x[WS(vs, 1) + WS(rs, 9)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
{
V T19, T1a, T1c, T1d;
T19 = LD(&(x[WS(vs, 1) + WS(rs, 11)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1a = LD(&(x[WS(vs, 1) + WS(rs, 7)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1b = VSUB(T19, T1a);
T1i = VADD(T1a, T19);
T1c = LD(&(x[WS(vs, 1) + WS(rs, 1)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1d = LD(&(x[WS(vs, 1) + WS(rs, 5)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1e = VSUB(T1c, T1d);
T1l = VADD(T1c, T1d);
}
T1f = VADD(T1b, T1e);
T1O = VADD(T1k, T1l);
T1B = VSUB(T1b, T1e);
T1N = VADD(T1h, T1i);
T1j = VFNMS(LDK(KP500000000), T1i, T1h);
T1m = VFNMS(LDK(KP500000000), T1l, T1k);
T1n = VSUB(T1j, T1m);
T1z = VADD(T1j, T1m);
}
{
V T9Q, T9T, T9K, T9R, T9N, T9U, T9S, T9V;
T9Q = LD(&(x[WS(vs, 10) + WS(rs, 3)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9T = LD(&(x[WS(vs, 10) + WS(rs, 9)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
{
V T9I, T9J, T9L, T9M;
T9I = LD(&(x[WS(vs, 10) + WS(rs, 11)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9J = LD(&(x[WS(vs, 10) + WS(rs, 7)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9K = VSUB(T9I, T9J);
T9R = VADD(T9J, T9I);
T9L = LD(&(x[WS(vs, 10) + WS(rs, 1)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9M = LD(&(x[WS(vs, 10) + WS(rs, 5)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9N = VSUB(T9L, T9M);
T9U = VADD(T9L, T9M);
}
T9O = VADD(T9K, T9N);
Tan = VADD(T9T, T9U);
Taa = VSUB(T9K, T9N);
Tam = VADD(T9Q, T9R);
T9S = VFNMS(LDK(KP500000000), T9R, T9Q);
T9V = VFNMS(LDK(KP500000000), T9U, T9T);
T9W = VSUB(T9S, T9V);
Ta8 = VADD(T9S, T9V);
}
{
V T9x, T9C, T9A, T9X, T9F, T9Y, T9B, T9G;
T9x = LD(&(x[WS(vs, 10)]), ms, &(x[WS(vs, 10)]));
T9C = LD(&(x[WS(vs, 10) + WS(rs, 6)]), ms, &(x[WS(vs, 10)]));
{
V T9y, T9z, T9D, T9E;
T9y = LD(&(x[WS(vs, 10) + WS(rs, 4)]), ms, &(x[WS(vs, 10)]));
T9z = LD(&(x[WS(vs, 10) + WS(rs, 8)]), ms, &(x[WS(vs, 10)]));
T9A = VADD(T9y, T9z);
T9X = VSUB(T9z, T9y);
T9D = LD(&(x[WS(vs, 10) + WS(rs, 10)]), ms, &(x[WS(vs, 10)]));
T9E = LD(&(x[WS(vs, 10) + WS(rs, 2)]), ms, &(x[WS(vs, 10)]));
T9F = VADD(T9D, T9E);
T9Y = VSUB(T9E, T9D);
}
T9Z = VSUB(T9X, T9Y);
Tak = VADD(T9C, T9F);
Tab = VADD(T9X, T9Y);
Taj = VADD(T9x, T9A);
T9B = VFNMS(LDK(KP500000000), T9A, T9x);
T9G = VFNMS(LDK(KP500000000), T9F, T9C);
T9H = VSUB(T9B, T9G);
Ta7 = VADD(T9B, T9G);
}
{
V TY, T13, T11, T1o, T16, T1p, T12, T17;
TY = LD(&(x[WS(vs, 1)]), ms, &(x[WS(vs, 1)]));
T13 = LD(&(x[WS(vs, 1) + WS(rs, 6)]), ms, &(x[WS(vs, 1)]));
{
V TZ, T10, T14, T15;
TZ = LD(&(x[WS(vs, 1) + WS(rs, 4)]), ms, &(x[WS(vs, 1)]));
T10 = LD(&(x[WS(vs, 1) + WS(rs, 8)]), ms, &(x[WS(vs, 1)]));
T11 = VADD(TZ, T10);
T1o = VSUB(T10, TZ);
T14 = LD(&(x[WS(vs, 1) + WS(rs, 10)]), ms, &(x[WS(vs, 1)]));
T15 = LD(&(x[WS(vs, 1) + WS(rs, 2)]), ms, &(x[WS(vs, 1)]));
T16 = VADD(T14, T15);
T1p = VSUB(T15, T14);
}
T1q = VSUB(T1o, T1p);
T1L = VADD(T13, T16);
T1C = VADD(T1o, T1p);
T1K = VADD(TY, T11);
T12 = VFNMS(LDK(KP500000000), T11, TY);
T17 = VFNMS(LDK(KP500000000), T16, T13);
T18 = VSUB(T12, T17);
T1y = VADD(T12, T17);
}
{
V T2S, T2X, T2V, T3i, T30, T3j, T2W, T31;
T2S = LD(&(x[WS(vs, 3)]), ms, &(x[WS(vs, 3)]));
T2X = LD(&(x[WS(vs, 3) + WS(rs, 6)]), ms, &(x[WS(vs, 3)]));
{
V T2T, T2U, T2Y, T2Z;
T2T = LD(&(x[WS(vs, 3) + WS(rs, 4)]), ms, &(x[WS(vs, 3)]));
T2U = LD(&(x[WS(vs, 3) + WS(rs, 8)]), ms, &(x[WS(vs, 3)]));
T2V = VADD(T2T, T2U);
T3i = VSUB(T2U, T2T);
T2Y = LD(&(x[WS(vs, 3) + WS(rs, 10)]), ms, &(x[WS(vs, 3)]));
T2Z = LD(&(x[WS(vs, 3) + WS(rs, 2)]), ms, &(x[WS(vs, 3)]));
T30 = VADD(T2Y, T2Z);
T3j = VSUB(T2Z, T2Y);
}
T3k = VSUB(T3i, T3j);
T3F = VADD(T2X, T30);
T3w = VADD(T3i, T3j);
T3E = VADD(T2S, T2V);
T2W = VFNMS(LDK(KP500000000), T2V, T2S);
T31 = VFNMS(LDK(KP500000000), T30, T2X);
T32 = VSUB(T2W, T31);
T3s = VADD(T2W, T31);
}
{
V T5J, T5O, T5M, T69, T5R, T6a, T5N, T5S;
T5J = LD(&(x[WS(vs, 6)]), ms, &(x[WS(vs, 6)]));
T5O = LD(&(x[WS(vs, 6) + WS(rs, 6)]), ms, &(x[WS(vs, 6)]));
{
V T5K, T5L, T5P, T5Q;
T5K = LD(&(x[WS(vs, 6) + WS(rs, 4)]), ms, &(x[WS(vs, 6)]));
T5L = LD(&(x[WS(vs, 6) + WS(rs, 8)]), ms, &(x[WS(vs, 6)]));
T5M = VADD(T5K, T5L);
T69 = VSUB(T5L, T5K);
T5P = LD(&(x[WS(vs, 6) + WS(rs, 10)]), ms, &(x[WS(vs, 6)]));
T5Q = LD(&(x[WS(vs, 6) + WS(rs, 2)]), ms, &(x[WS(vs, 6)]));
T5R = VADD(T5P, T5Q);
T6a = VSUB(T5Q, T5P);
}
T6b = VSUB(T69, T6a);
T6w = VADD(T5O, T5R);
T6n = VADD(T69, T6a);
T6v = VADD(T5J, T5M);
T5N = VFNMS(LDK(KP500000000), T5M, T5J);
T5S = VFNMS(LDK(KP500000000), T5R, T5O);
T5T = VSUB(T5N, T5S);
T6j = VADD(T5N, T5S);
}
{
V T62, T65, T5W, T63, T5Z, T66, T64, T67;
T62 = LD(&(x[WS(vs, 6) + WS(rs, 3)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T65 = LD(&(x[WS(vs, 6) + WS(rs, 9)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
{
V T5U, T5V, T5X, T5Y;
T5U = LD(&(x[WS(vs, 6) + WS(rs, 11)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5V = LD(&(x[WS(vs, 6) + WS(rs, 7)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5W = VSUB(T5U, T5V);
T63 = VADD(T5V, T5U);
T5X = LD(&(x[WS(vs, 6) + WS(rs, 1)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5Y = LD(&(x[WS(vs, 6) + WS(rs, 5)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5Z = VSUB(T5X, T5Y);
T66 = VADD(T5X, T5Y);
}
T60 = VADD(T5W, T5Z);
T6z = VADD(T65, T66);
T6m = VSUB(T5W, T5Z);
T6y = VADD(T62, T63);
T64 = VFNMS(LDK(KP500000000), T63, T62);
T67 = VFNMS(LDK(KP500000000), T66, T65);
T68 = VSUB(T64, T67);
T6k = VADD(T64, T67);
}
{
V T3b, T3e, T35, T3c, T38, T3f, T3d, T3g;
T3b = LD(&(x[WS(vs, 3) + WS(rs, 3)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T3e = LD(&(x[WS(vs, 3) + WS(rs, 9)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
{
V T33, T34, T36, T37;
T33 = LD(&(x[WS(vs, 3) + WS(rs, 11)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T34 = LD(&(x[WS(vs, 3) + WS(rs, 7)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T35 = VSUB(T33, T34);
T3c = VADD(T34, T33);
T36 = LD(&(x[WS(vs, 3) + WS(rs, 1)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T37 = LD(&(x[WS(vs, 3) + WS(rs, 5)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T38 = VSUB(T36, T37);
T3f = VADD(T36, T37);
}
T39 = VADD(T35, T38);
T3I = VADD(T3e, T3f);
T3v = VSUB(T35, T38);
T3H = VADD(T3b, T3c);
T3d = VFNMS(LDK(KP500000000), T3c, T3b);
T3g = VFNMS(LDK(KP500000000), T3f, T3e);
T3h = VSUB(T3d, T3g);
T3t = VADD(T3d, T3g);
}
{
V T55, T58, T4Z, T56, T52, T59, T57, T5a;
T55 = LD(&(x[WS(vs, 5) + WS(rs, 3)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T58 = LD(&(x[WS(vs, 5) + WS(rs, 9)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
{
V T4X, T4Y, T50, T51;
T4X = LD(&(x[WS(vs, 5) + WS(rs, 11)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4Y = LD(&(x[WS(vs, 5) + WS(rs, 7)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4Z = VSUB(T4X, T4Y);
T56 = VADD(T4Y, T4X);
T50 = LD(&(x[WS(vs, 5) + WS(rs, 1)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T51 = LD(&(x[WS(vs, 5) + WS(rs, 5)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T52 = VSUB(T50, T51);
T59 = VADD(T50, T51);
}
T53 = VADD(T4Z, T52);
T5C = VADD(T58, T59);
T5p = VSUB(T4Z, T52);
T5B = VADD(T55, T56);
T57 = VFNMS(LDK(KP500000000), T56, T55);
T5a = VFNMS(LDK(KP500000000), T59, T58);
T5b = VSUB(T57, T5a);
T5n = VADD(T57, T5a);
}
{
V T7W, T7Z, T7Q, T7X, T7T, T80, T7Y, T81;
T7W = LD(&(x[WS(vs, 8) + WS(rs, 3)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7Z = LD(&(x[WS(vs, 8) + WS(rs, 9)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
{
V T7O, T7P, T7R, T7S;
T7O = LD(&(x[WS(vs, 8) + WS(rs, 11)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7P = LD(&(x[WS(vs, 8) + WS(rs, 7)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7Q = VSUB(T7O, T7P);
T7X = VADD(T7P, T7O);
T7R = LD(&(x[WS(vs, 8) + WS(rs, 1)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7S = LD(&(x[WS(vs, 8) + WS(rs, 5)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7T = VSUB(T7R, T7S);
T80 = VADD(T7R, T7S);
}
T7U = VADD(T7Q, T7T);
T8t = VADD(T7Z, T80);
T8g = VSUB(T7Q, T7T);
T8s = VADD(T7W, T7X);
T7Y = VFNMS(LDK(KP500000000), T7X, T7W);
T81 = VFNMS(LDK(KP500000000), T80, T7Z);
T82 = VSUB(T7Y, T81);
T8e = VADD(T7Y, T81);
}
{
V T7D, T7I, T7G, T83, T7L, T84, T7H, T7M;
T7D = LD(&(x[WS(vs, 8)]), ms, &(x[WS(vs, 8)]));
T7I = LD(&(x[WS(vs, 8) + WS(rs, 6)]), ms, &(x[WS(vs, 8)]));
{
V T7E, T7F, T7J, T7K;
T7E = LD(&(x[WS(vs, 8) + WS(rs, 4)]), ms, &(x[WS(vs, 8)]));
T7F = LD(&(x[WS(vs, 8) + WS(rs, 8)]), ms, &(x[WS(vs, 8)]));
T7G = VADD(T7E, T7F);
T83 = VSUB(T7F, T7E);
T7J = LD(&(x[WS(vs, 8) + WS(rs, 10)]), ms, &(x[WS(vs, 8)]));
T7K = LD(&(x[WS(vs, 8) + WS(rs, 2)]), ms, &(x[WS(vs, 8)]));
T7L = VADD(T7J, T7K);
T84 = VSUB(T7K, T7J);
}
T85 = VSUB(T83, T84);
T8q = VADD(T7I, T7L);
T8h = VADD(T83, T84);
T8p = VADD(T7D, T7G);
T7H = VFNMS(LDK(KP500000000), T7G, T7D);
T7M = VFNMS(LDK(KP500000000), T7L, T7I);
T7N = VSUB(T7H, T7M);
T8d = VADD(T7H, T7M);
}
{
V T4M, T4R, T4P, T5c, T4U, T5d, T4Q, T4V;
T4M = LD(&(x[WS(vs, 5)]), ms, &(x[WS(vs, 5)]));
T4R = LD(&(x[WS(vs, 5) + WS(rs, 6)]), ms, &(x[WS(vs, 5)]));
{
V T4N, T4O, T4S, T4T;
T4N = LD(&(x[WS(vs, 5) + WS(rs, 4)]), ms, &(x[WS(vs, 5)]));
T4O = LD(&(x[WS(vs, 5) + WS(rs, 8)]), ms, &(x[WS(vs, 5)]));
T4P = VADD(T4N, T4O);
T5c = VSUB(T4O, T4N);
T4S = LD(&(x[WS(vs, 5) + WS(rs, 10)]), ms, &(x[WS(vs, 5)]));
T4T = LD(&(x[WS(vs, 5) + WS(rs, 2)]), ms, &(x[WS(vs, 5)]));
T4U = VADD(T4S, T4T);
T5d = VSUB(T4T, T4S);
}
T5e = VSUB(T5c, T5d);
T5z = VADD(T4R, T4U);
T5q = VADD(T5c, T5d);
T5y = VADD(T4M, T4P);
T4Q = VFNMS(LDK(KP500000000), T4P, T4M);
T4V = VFNMS(LDK(KP500000000), T4U, T4R);
T4W = VSUB(T4Q, T4V);
T5m = VADD(T4Q, T4V);
}
{
V T48, T4b, T42, T49, T45, T4c, T4a, T4d;
T48 = LD(&(x[WS(vs, 4) + WS(rs, 3)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T4b = LD(&(x[WS(vs, 4) + WS(rs, 9)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
{
V T40, T41, T43, T44;
T40 = LD(&(x[WS(vs, 4) + WS(rs, 11)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T41 = LD(&(x[WS(vs, 4) + WS(rs, 7)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T42 = VSUB(T40, T41);
T49 = VADD(T41, T40);
T43 = LD(&(x[WS(vs, 4) + WS(rs, 1)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T44 = LD(&(x[WS(vs, 4) + WS(rs, 5)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T45 = VSUB(T43, T44);
T4c = VADD(T43, T44);
}
T46 = VADD(T42, T45);
T4F = VADD(T4b, T4c);
T4s = VSUB(T42, T45);
T4E = VADD(T48, T49);
T4a = VFNMS(LDK(KP500000000), T49, T48);
T4d = VFNMS(LDK(KP500000000), T4c, T4b);
T4e = VSUB(T4a, T4d);
T4q = VADD(T4a, T4d);
}
{
V T6Z, T72, T6T, T70, T6W, T73, T71, T74;
T6Z = LD(&(x[WS(vs, 7) + WS(rs, 3)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T72 = LD(&(x[WS(vs, 7) + WS(rs, 9)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
{
V T6R, T6S, T6U, T6V;
T6R = LD(&(x[WS(vs, 7) + WS(rs, 11)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6S = LD(&(x[WS(vs, 7) + WS(rs, 7)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6T = VSUB(T6R, T6S);
T70 = VADD(T6S, T6R);
T6U = LD(&(x[WS(vs, 7) + WS(rs, 1)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6V = LD(&(x[WS(vs, 7) + WS(rs, 5)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6W = VSUB(T6U, T6V);
T73 = VADD(T6U, T6V);
}
T6X = VADD(T6T, T6W);
T7w = VADD(T72, T73);
T7j = VSUB(T6T, T6W);
T7v = VADD(T6Z, T70);
T71 = VFNMS(LDK(KP500000000), T70, T6Z);
T74 = VFNMS(LDK(KP500000000), T73, T72);
T75 = VSUB(T71, T74);
T7h = VADD(T71, T74);
}
{
V T6G, T6L, T6J, T76, T6O, T77, T6K, T6P;
T6G = LD(&(x[WS(vs, 7)]), ms, &(x[WS(vs, 7)]));
T6L = LD(&(x[WS(vs, 7) + WS(rs, 6)]), ms, &(x[WS(vs, 7)]));
{
V T6H, T6I, T6M, T6N;
T6H = LD(&(x[WS(vs, 7) + WS(rs, 4)]), ms, &(x[WS(vs, 7)]));
T6I = LD(&(x[WS(vs, 7) + WS(rs, 8)]), ms, &(x[WS(vs, 7)]));
T6J = VADD(T6H, T6I);
T76 = VSUB(T6I, T6H);
T6M = LD(&(x[WS(vs, 7) + WS(rs, 10)]), ms, &(x[WS(vs, 7)]));
T6N = LD(&(x[WS(vs, 7) + WS(rs, 2)]), ms, &(x[WS(vs, 7)]));
T6O = VADD(T6M, T6N);
T77 = VSUB(T6N, T6M);
}
T78 = VSUB(T76, T77);
T7t = VADD(T6L, T6O);
T7k = VADD(T76, T77);
T7s = VADD(T6G, T6J);
T6K = VFNMS(LDK(KP500000000), T6J, T6G);
T6P = VFNMS(LDK(KP500000000), T6O, T6L);
T6Q = VSUB(T6K, T6P);
T7g = VADD(T6K, T6P);
}
{
V T3P, T3U, T3S, T4f, T3X, T4g, T3T, T3Y;
T3P = LD(&(x[WS(vs, 4)]), ms, &(x[WS(vs, 4)]));
T3U = LD(&(x[WS(vs, 4) + WS(rs, 6)]), ms, &(x[WS(vs, 4)]));
{
V T3Q, T3R, T3V, T3W;
T3Q = LD(&(x[WS(vs, 4) + WS(rs, 4)]), ms, &(x[WS(vs, 4)]));
T3R = LD(&(x[WS(vs, 4) + WS(rs, 8)]), ms, &(x[WS(vs, 4)]));
T3S = VADD(T3Q, T3R);
T4f = VSUB(T3R, T3Q);
T3V = LD(&(x[WS(vs, 4) + WS(rs, 10)]), ms, &(x[WS(vs, 4)]));
T3W = LD(&(x[WS(vs, 4) + WS(rs, 2)]), ms, &(x[WS(vs, 4)]));
T3X = VADD(T3V, T3W);
T4g = VSUB(T3W, T3V);
}
T4h = VSUB(T4f, T4g);
T4C = VADD(T3U, T3X);
T4t = VADD(T4f, T4g);
T4B = VADD(T3P, T3S);
T3T = VFNMS(LDK(KP500000000), T3S, T3P);
T3Y = VFNMS(LDK(KP500000000), T3X, T3U);
T3Z = VSUB(T3T, T3Y);
T4p = VADD(T3T, T3Y);
}
{
V T5G, T5H, T5I, Tar, Tas, Tat;
{
V TV, TW, TX, T2P, T2Q, T2R;
TV = VADD(TN, TO);
TW = VADD(TQ, TR);
TX = BYTWJ(&(W[TWVL * 10]),VSUB(TV, TW));
ST(&(x[WS(vs, 6)]),TX,ms,&(x[WS(vs, 6)]));
ST(&(x[0]),VADD(TV, TW),ms,&(x[0]));
T2P = VADD(T2H, T2I);
T2Q = VADD(T2K, T2L);
T2R = BYTWJ(&(W[TWVL * 10]),VSUB(T2P, T2Q));
ST(&(x[WS(vs, 6) + WS(rs, 2)]),T2R,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 2)]),VADD(T2P, T2Q),ms,&(x[0]));
}
{
V T1S, T1T, T1U, T3M, T3N, T3O;
T1S = VADD(T1K, T1L);
T1T = VADD(T1N, T1O);
T1U = BYTWJ(&(W[TWVL * 10]),VSUB(T1S, T1T));
ST(&(x[WS(vs, 6) + WS(rs, 1)]),T1U,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 1)]),VADD(T1S, T1T),ms,&(x[WS(rs, 1)]));
T3M = VADD(T3E, T3F);
T3N = VADD(T3H, T3I);
T3O = BYTWJ(&(W[TWVL * 10]),VSUB(T3M, T3N));
ST(&(x[WS(vs, 6) + WS(rs, 3)]),T3O,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 3)]),VADD(T3M, T3N),ms,&(x[WS(rs, 1)]));
}
{
V T6D, T6E, T6F, Tbo, Tbp, Tbq;
T6D = VADD(T6v, T6w);
T6E = VADD(T6y, T6z);
T6F = BYTWJ(&(W[TWVL * 10]),VSUB(T6D, T6E));
ST(&(x[WS(vs, 6) + WS(rs, 6)]),T6F,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 6)]),VADD(T6D, T6E),ms,&(x[0]));
Tbo = VADD(Tbg, Tbh);
Tbp = VADD(Tbj, Tbk);
Tbq = BYTWJ(&(W[TWVL * 10]),VSUB(Tbo, Tbp));
ST(&(x[WS(vs, 6) + WS(rs, 11)]),Tbq,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 11)]),VADD(Tbo, Tbp),ms,&(x[WS(rs, 1)]));
}
T5G = VADD(T5y, T5z);
T5H = VADD(T5B, T5C);
T5I = BYTWJ(&(W[TWVL * 10]),VSUB(T5G, T5H));
ST(&(x[WS(vs, 6) + WS(rs, 5)]),T5I,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 5)]),VADD(T5G, T5H),ms,&(x[WS(rs, 1)]));
{
V T9u, T9v, T9w, T8x, T8y, T8z;
T9u = VADD(T9m, T9n);
T9v = VADD(T9p, T9q);
T9w = BYTWJ(&(W[TWVL * 10]),VSUB(T9u, T9v));
ST(&(x[WS(vs, 6) + WS(rs, 9)]),T9w,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 9)]),VADD(T9u, T9v),ms,&(x[WS(rs, 1)]));
T8x = VADD(T8p, T8q);
T8y = VADD(T8s, T8t);
T8z = BYTWJ(&(W[TWVL * 10]),VSUB(T8x, T8y));
ST(&(x[WS(vs, 6) + WS(rs, 8)]),T8z,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 8)]),VADD(T8x, T8y),ms,&(x[0]));
}
{
V T4J, T4K, T4L, T7A, T7B, T7C;
T4J = VADD(T4B, T4C);
T4K = VADD(T4E, T4F);
T4L = BYTWJ(&(W[TWVL * 10]),VSUB(T4J, T4K));
ST(&(x[WS(vs, 6) + WS(rs, 4)]),T4L,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 4)]),VADD(T4J, T4K),ms,&(x[0]));
T7A = VADD(T7s, T7t);
T7B = VADD(T7v, T7w);
T7C = BYTWJ(&(W[TWVL * 10]),VSUB(T7A, T7B));
ST(&(x[WS(vs, 6) + WS(rs, 7)]),T7C,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 7)]),VADD(T7A, T7B),ms,&(x[WS(rs, 1)]));
}
Tar = VADD(Taj, Tak);
Tas = VADD(Tam, Tan);
Tat = BYTWJ(&(W[TWVL * 10]),VSUB(Tar, Tas));
ST(&(x[WS(vs, 6) + WS(rs, 10)]),Tat,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 10)]),VADD(Tar, Tas),ms,&(x[0]));
{
V T5g, T5h, T54, T5f;
T54 = VFMA(LDK(KP866025403), T53, T4W);
T5f = VFNMS(LDK(KP866025403), T5e, T5b);
T5g = BYTWJ(&(W[0]),VFNMSI(T5f, T54));
T5h = BYTWJ(&(W[TWVL * 20]),VFMAI(T5f, T54));
ST(&(x[WS(vs, 1) + WS(rs, 5)]),T5g,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 5)]),T5h,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V Tv, Tw, Tj, Tu;
Tj = VFMA(LDK(KP866025403), Ti, Tb);
Tu = VFNMS(LDK(KP866025403), Tt, Tq);
Tv = BYTWJ(&(W[0]),VFNMSI(Tu, Tj));
Tw = BYTWJ(&(W[TWVL * 20]),VFMAI(Tu, Tj));
ST(&(x[WS(vs, 1)]),Tv,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11)]),Tw,ms,&(x[WS(vs, 11)]));
}
{
V T6d, T6e, T61, T6c;
T61 = VFMA(LDK(KP866025403), T60, T5T);
T6c = VFNMS(LDK(KP866025403), T6b, T68);
T6d = BYTWJ(&(W[0]),VFNMSI(T6c, T61));
T6e = BYTWJ(&(W[TWVL * 20]),VFMAI(T6c, T61));
ST(&(x[WS(vs, 1) + WS(rs, 6)]),T6d,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 6)]),T6e,ms,&(x[WS(vs, 11)]));
}
{
V TaY, TaZ, TaM, TaX;
TaM = VFMA(LDK(KP866025403), TaL, TaE);
TaX = VFNMS(LDK(KP866025403), TaW, TaT);
TaY = BYTWJ(&(W[0]),VFNMSI(TaX, TaM));
TaZ = BYTWJ(&(W[TWVL * 20]),VFMAI(TaX, TaM));
ST(&(x[WS(vs, 1) + WS(rs, 11)]),TaY,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 11)]),TaZ,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T7a, T7b, T6Y, T79;
T6Y = VFMA(LDK(KP866025403), T6X, T6Q);
T79 = VFNMS(LDK(KP866025403), T78, T75);
T7a = BYTWJ(&(W[0]),VFNMSI(T79, T6Y));
T7b = BYTWJ(&(W[TWVL * 20]),VFMAI(T79, T6Y));
ST(&(x[WS(vs, 1) + WS(rs, 7)]),T7a,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 7)]),T7b,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T1s, T1t, T1g, T1r;
T1g = VFMA(LDK(KP866025403), T1f, T18);
T1r = VFNMS(LDK(KP866025403), T1q, T1n);
T1s = BYTWJ(&(W[0]),VFNMSI(T1r, T1g));
T1t = BYTWJ(&(W[TWVL * 20]),VFMAI(T1r, T1g));
ST(&(x[WS(vs, 1) + WS(rs, 1)]),T1s,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 1)]),T1t,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
}
{
V Ta1, Ta2, T9P, Ta0;
T9P = VFMA(LDK(KP866025403), T9O, T9H);
Ta0 = VFNMS(LDK(KP866025403), T9Z, T9W);
Ta1 = BYTWJ(&(W[0]),VFNMSI(Ta0, T9P));
Ta2 = BYTWJ(&(W[TWVL * 20]),VFMAI(Ta0, T9P));
ST(&(x[WS(vs, 1) + WS(rs, 10)]),Ta1,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 10)]),Ta2,ms,&(x[WS(vs, 11)]));
}
{
V T2p, T2q, T2d, T2o;
T2d = VFMA(LDK(KP866025403), T2c, T25);
T2o = VFNMS(LDK(KP866025403), T2n, T2k);
T2p = BYTWJ(&(W[0]),VFNMSI(T2o, T2d));
T2q = BYTWJ(&(W[TWVL * 20]),VFMAI(T2o, T2d));
ST(&(x[WS(vs, 1) + WS(rs, 2)]),T2p,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 2)]),T2q,ms,&(x[WS(vs, 11)]));
}
{
V T87, T88, T7V, T86;
T7V = VFMA(LDK(KP866025403), T7U, T7N);
T86 = VFNMS(LDK(KP866025403), T85, T82);
T87 = BYTWJ(&(W[0]),VFNMSI(T86, T7V));
T88 = BYTWJ(&(W[TWVL * 20]),VFMAI(T86, T7V));
ST(&(x[WS(vs, 1) + WS(rs, 8)]),T87,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 8)]),T88,ms,&(x[WS(vs, 11)]));
}
{
V T3m, T3n, T3a, T3l;
T3a = VFMA(LDK(KP866025403), T39, T32);
T3l = VFNMS(LDK(KP866025403), T3k, T3h);
T3m = BYTWJ(&(W[0]),VFNMSI(T3l, T3a));
T3n = BYTWJ(&(W[TWVL * 20]),VFMAI(T3l, T3a));
ST(&(x[WS(vs, 1) + WS(rs, 3)]),T3m,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 3)]),T3n,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T4j, T4k, T47, T4i;
T47 = VFMA(LDK(KP866025403), T46, T3Z);
T4i = VFNMS(LDK(KP866025403), T4h, T4e);
T4j = BYTWJ(&(W[0]),VFNMSI(T4i, T47));
T4k = BYTWJ(&(W[TWVL * 20]),VFMAI(T4i, T47));
ST(&(x[WS(vs, 1) + WS(rs, 4)]),T4j,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 4)]),T4k,ms,&(x[WS(vs, 11)]));
}
{
V T94, T95, T8S, T93;
T8S = VFMA(LDK(KP866025403), T8R, T8K);
T93 = VFNMS(LDK(KP866025403), T92, T8Z);
T94 = BYTWJ(&(W[0]),VFNMSI(T93, T8S));
T95 = BYTWJ(&(W[TWVL * 20]),VFMAI(T93, T8S));
ST(&(x[WS(vs, 1) + WS(rs, 9)]),T94,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 9)]),T95,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V Tz, TA, Tx, Ty;
Tx = VFNMS(LDK(KP866025403), Ti, Tb);
Ty = VFMA(LDK(KP866025403), Tt, Tq);
Tz = BYTWJ(&(W[TWVL * 8]),VFNMSI(Ty, Tx));
TA = BYTWJ(&(W[TWVL * 12]),VFMAI(Ty, Tx));
ST(&(x[WS(vs, 5)]),Tz,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7)]),TA,ms,&(x[WS(vs, 7)]));
}
{
V T6h, T6i, T6f, T6g;
T6f = VFNMS(LDK(KP866025403), T60, T5T);
T6g = VFMA(LDK(KP866025403), T6b, T68);
T6h = BYTWJ(&(W[TWVL * 8]),VFNMSI(T6g, T6f));
T6i = BYTWJ(&(W[TWVL * 12]),VFMAI(T6g, T6f));
ST(&(x[WS(vs, 5) + WS(rs, 6)]),T6h,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 6)]),T6i,ms,&(x[WS(vs, 7)]));
}
{
V T3q, T3r, T3o, T3p;
T3o = VFNMS(LDK(KP866025403), T39, T32);
T3p = VFMA(LDK(KP866025403), T3k, T3h);
T3q = BYTWJ(&(W[TWVL * 8]),VFNMSI(T3p, T3o));
T3r = BYTWJ(&(W[TWVL * 12]),VFMAI(T3p, T3o));
ST(&(x[WS(vs, 5) + WS(rs, 3)]),T3q,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 3)]),T3r,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T98, T99, T96, T97;
T96 = VFNMS(LDK(KP866025403), T8R, T8K);
T97 = VFMA(LDK(KP866025403), T92, T8Z);
T98 = BYTWJ(&(W[TWVL * 8]),VFNMSI(T97, T96));
T99 = BYTWJ(&(W[TWVL * 12]),VFMAI(T97, T96));
ST(&(x[WS(vs, 5) + WS(rs, 9)]),T98,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 9)]),T99,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T7e, T7f, T7c, T7d;
T7c = VFNMS(LDK(KP866025403), T6X, T6Q);
T7d = VFMA(LDK(KP866025403), T78, T75);
T7e = BYTWJ(&(W[TWVL * 8]),VFNMSI(T7d, T7c));
T7f = BYTWJ(&(W[TWVL * 12]),VFMAI(T7d, T7c));
ST(&(x[WS(vs, 5) + WS(rs, 7)]),T7e,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 7)]),T7f,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V Ta5, Ta6, Ta3, Ta4;
Ta3 = VFNMS(LDK(KP866025403), T9O, T9H);
Ta4 = VFMA(LDK(KP866025403), T9Z, T9W);
Ta5 = BYTWJ(&(W[TWVL * 8]),VFNMSI(Ta4, Ta3));
Ta6 = BYTWJ(&(W[TWVL * 12]),VFMAI(Ta4, Ta3));
ST(&(x[WS(vs, 5) + WS(rs, 10)]),Ta5,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 10)]),Ta6,ms,&(x[WS(vs, 7)]));
}
{
V Tb2, Tb3, Tb0, Tb1;
Tb0 = VFNMS(LDK(KP866025403), TaL, TaE);
Tb1 = VFMA(LDK(KP866025403), TaW, TaT);
Tb2 = BYTWJ(&(W[TWVL * 8]),VFNMSI(Tb1, Tb0));
Tb3 = BYTWJ(&(W[TWVL * 12]),VFMAI(Tb1, Tb0));
ST(&(x[WS(vs, 5) + WS(rs, 11)]),Tb2,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 11)]),Tb3,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T8b, T8c, T89, T8a;
T89 = VFNMS(LDK(KP866025403), T7U, T7N);
T8a = VFMA(LDK(KP866025403), T85, T82);
T8b = BYTWJ(&(W[TWVL * 8]),VFNMSI(T8a, T89));
T8c = BYTWJ(&(W[TWVL * 12]),VFMAI(T8a, T89));
ST(&(x[WS(vs, 5) + WS(rs, 8)]),T8b,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 8)]),T8c,ms,&(x[WS(vs, 7)]));
}
{
V T2t, T2u, T2r, T2s;
T2r = VFNMS(LDK(KP866025403), T2c, T25);
T2s = VFMA(LDK(KP866025403), T2n, T2k);
T2t = BYTWJ(&(W[TWVL * 8]),VFNMSI(T2s, T2r));
T2u = BYTWJ(&(W[TWVL * 12]),VFMAI(T2s, T2r));
ST(&(x[WS(vs, 5) + WS(rs, 2)]),T2t,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 2)]),T2u,ms,&(x[WS(vs, 7)]));
}
{
V T4n, T4o, T4l, T4m;
T4l = VFNMS(LDK(KP866025403), T46, T3Z);
T4m = VFMA(LDK(KP866025403), T4h, T4e);
T4n = BYTWJ(&(W[TWVL * 8]),VFNMSI(T4m, T4l));
T4o = BYTWJ(&(W[TWVL * 12]),VFMAI(T4m, T4l));
ST(&(x[WS(vs, 5) + WS(rs, 4)]),T4n,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 4)]),T4o,ms,&(x[WS(vs, 7)]));
}
{
V T5k, T5l, T5i, T5j;
T5i = VFNMS(LDK(KP866025403), T53, T4W);
T5j = VFMA(LDK(KP866025403), T5e, T5b);
T5k = BYTWJ(&(W[TWVL * 8]),VFNMSI(T5j, T5i));
T5l = BYTWJ(&(W[TWVL * 12]),VFMAI(T5j, T5i));
ST(&(x[WS(vs, 5) + WS(rs, 5)]),T5k,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 5)]),T5l,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T1w, T1x, T1u, T1v;
T1u = VFNMS(LDK(KP866025403), T1f, T18);
T1v = VFMA(LDK(KP866025403), T1q, T1n);
T1w = BYTWJ(&(W[TWVL * 8]),VFNMSI(T1v, T1u));
T1x = BYTWJ(&(W[TWVL * 12]),VFMAI(T1v, T1u));
ST(&(x[WS(vs, 5) + WS(rs, 1)]),T1w,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 1)]),T1x,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V TH, TI, TD, TG;
TD = VSUB(TB, TC);
TG = VMUL(LDK(KP866025403), VSUB(TE, TF));
TH = BYTWJ(&(W[TWVL * 2]),VFMAI(TG, TD));
TI = BYTWJ(&(W[TWVL * 18]),VFNMSI(TG, TD));
ST(&(x[WS(vs, 2)]),TH,ms,&(x[WS(vs, 2)]));
ST(&(x[WS(vs, 10)]),TI,ms,&(x[WS(vs, 10)]));
}
{
V T2B, T2C, T2x, T2A;
T2x = VSUB(T2v, T2w);
T2A = VMUL(LDK(KP866025403), VSUB(T2y, T2z));
T2B = BYTWJ(&(W[TWVL * 2]),VFMAI(T2A, T2x));
T2C = BYTWJ(&(W[TWVL * 18]),VFNMSI(T2A, T2x));
ST(&(x[WS(vs, 2) + WS(rs, 2)]),T2B,ms,&(x[WS(vs, 2)]));
ST(&(x[WS(vs, 10) + WS(rs, 2)]),T2C,ms,&(x[WS(vs, 10)]));
}
{
V T1E, T1F, T1A, T1D;
T1A = VSUB(T1y, T1z);
T1D = VMUL(LDK(KP866025403), VSUB(T1B, T1C));
T1E = BYTWJ(&(W[TWVL * 2]),VFMAI(T1D, T1A));
T1F = BYTWJ(&(W[TWVL * 18]),VFNMSI(T1D, T1A));
ST(&(x[WS(vs, 2) + WS(rs, 1)]),T1E,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
ST(&(x[WS(vs, 10) + WS(rs, 1)]),T1F,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
}
{
V T3y, T3z, T3u, T3x;
T3u = VSUB(T3s, T3t);
T3x = VMUL(LDK(KP866025403), VSUB(T3v, T3w));
T3y = BYTWJ(&(W[TWVL * 2]),VFMAI(T3x, T3u));
T3z = BYTWJ(&(W[TWVL * 18]),VFNMSI(T3x, T3u));
ST(&(x[WS(vs, 2) + WS(rs, 3)]),T3y,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
ST(&(x[WS(vs, 10) + WS(rs, 3)]),T3z,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
}
{
V T6p, T6q, T6l, T6o;
T6l = VSUB(T6j, T6k);
T6o = VMUL(LDK(KP866025403), VSUB(T6m, T6n));
T6p = BYTWJ(&(W[TWVL * 2]),VFMAI(T6o, T6l));
T6q = BYTWJ(&(W[TWVL * 18]),VFNMSI(T6o, T6l));
ST(&(x[WS(vs, 2) + WS(rs, 6)]),T6p,ms,&(x[WS(vs, 2)]));
ST(&(x[WS(vs, 10) + WS(rs, 6)]),T6q,ms,&(x[WS(vs, 10)]));
}
{
V Tba, Tbb, Tb6, Tb9;
Tb6 = VSUB(Tb4, Tb5);
Tb9 = VMUL(LDK(KP866025403), VSUB(Tb7, Tb8));
Tba = BYTWJ(&(W[TWVL * 2]),VFMAI(Tb9, Tb6));
Tbb = BYTWJ(&(W[TWVL * 18]),VFNMSI(Tb9, Tb6));
ST(&(x[WS(vs, 2) + WS(rs, 11)]),Tba,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
ST(&(x[WS(vs, 10) + WS(rs, 11)]),Tbb,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
}
{
V T5s, T5t, T5o, T5r;
T5o = VSUB(T5m, T5n);
T5r = VMUL(LDK(KP866025403), VSUB(T5p, T5q));
T5s = BYTWJ(&(W[TWVL * 2]),VFMAI(T5r, T5o));
T5t = BYTWJ(&(W[TWVL * 18]),VFNMSI(T5r, T5o));
ST(&(x[WS(vs, 2) + WS(rs, 5)]),T5s,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
ST(&(x[WS(vs, 10) + WS(rs, 5)]),T5t,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
}
{
V T9g, T9h, T9c, T9f;
T9c = VSUB(T9a, T9b);
T9f = VMUL(LDK(KP866025403), VSUB(T9d, T9e));
T9g = BYTWJ(&(W[TWVL * 2]),VFMAI(T9f, T9c));
T9h = BYTWJ(&(W[TWVL * 18]),VFNMSI(T9f, T9c));
ST(&(x[WS(vs, 2) + WS(rs, 9)]),T9g,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
ST(&(x[WS(vs, 10) + WS(rs, 9)]),T9h,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
}
{
V T8j, T8k, T8f, T8i;
T8f = VSUB(T8d, T8e);
T8i = VMUL(LDK(KP866025403), VSUB(T8g, T8h));
T8j = BYTWJ(&(W[TWVL * 2]),VFMAI(T8i, T8f));
T8k = BYTWJ(&(W[TWVL * 18]),VFNMSI(T8i, T8f));
ST(&(x[WS(vs, 2) + WS(rs, 8)]),T8j,ms,&(x[WS(vs, 2)]));
ST(&(x[WS(vs, 10) + WS(rs, 8)]),T8k,ms,&(x[WS(vs, 10)]));
}
{
V T4v, T4w, T4r, T4u;
T4r = VSUB(T4p, T4q);
T4u = VMUL(LDK(KP866025403), VSUB(T4s, T4t));
T4v = BYTWJ(&(W[TWVL * 2]),VFMAI(T4u, T4r));
T4w = BYTWJ(&(W[TWVL * 18]),VFNMSI(T4u, T4r));
ST(&(x[WS(vs, 2) + WS(rs, 4)]),T4v,ms,&(x[WS(vs, 2)]));
ST(&(x[WS(vs, 10) + WS(rs, 4)]),T4w,ms,&(x[WS(vs, 10)]));
}
{
V T7m, T7n, T7i, T7l;
T7i = VSUB(T7g, T7h);
T7l = VMUL(LDK(KP866025403), VSUB(T7j, T7k));
T7m = BYTWJ(&(W[TWVL * 2]),VFMAI(T7l, T7i));
T7n = BYTWJ(&(W[TWVL * 18]),VFNMSI(T7l, T7i));
ST(&(x[WS(vs, 2) + WS(rs, 7)]),T7m,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
ST(&(x[WS(vs, 10) + WS(rs, 7)]),T7n,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
}
{
V Tad, Tae, Ta9, Tac;
Ta9 = VSUB(Ta7, Ta8);
Tac = VMUL(LDK(KP866025403), VSUB(Taa, Tab));
Tad = BYTWJ(&(W[TWVL * 2]),VFMAI(Tac, Ta9));
Tae = BYTWJ(&(W[TWVL * 18]),VFNMSI(Tac, Ta9));
ST(&(x[WS(vs, 2) + WS(rs, 10)]),Tad,ms,&(x[WS(vs, 2)]));
ST(&(x[WS(vs, 10) + WS(rs, 10)]),Tae,ms,&(x[WS(vs, 10)]));
}
{
V T5w, T5x, T5u, T5v;
T5u = VADD(T5m, T5n);
T5v = VMUL(LDK(KP866025403), VADD(T5q, T5p));
T5w = BYTWJ(&(W[TWVL * 6]),VFMAI(T5v, T5u));
T5x = BYTWJ(&(W[TWVL * 14]),VFNMSI(T5v, T5u));
ST(&(x[WS(vs, 4) + WS(rs, 5)]),T5w,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
ST(&(x[WS(vs, 8) + WS(rs, 5)]),T5x,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
}
{
V TL, TM, TJ, TK;
TJ = VADD(TB, TC);
TK = VMUL(LDK(KP866025403), VADD(TF, TE));
TL = BYTWJ(&(W[TWVL * 6]),VFMAI(TK, TJ));
TM = BYTWJ(&(W[TWVL * 14]),VFNMSI(TK, TJ));
ST(&(x[WS(vs, 4)]),TL,ms,&(x[WS(vs, 4)]));
ST(&(x[WS(vs, 8)]),TM,ms,&(x[WS(vs, 8)]));
}
{
V T6t, T6u, T6r, T6s;
T6r = VADD(T6j, T6k);
T6s = VMUL(LDK(KP866025403), VADD(T6n, T6m));
T6t = BYTWJ(&(W[TWVL * 6]),VFMAI(T6s, T6r));
T6u = BYTWJ(&(W[TWVL * 14]),VFNMSI(T6s, T6r));
ST(&(x[WS(vs, 4) + WS(rs, 6)]),T6t,ms,&(x[WS(vs, 4)]));
ST(&(x[WS(vs, 8) + WS(rs, 6)]),T6u,ms,&(x[WS(vs, 8)]));
}
{
V Tbe, Tbf, Tbc, Tbd;
Tbc = VADD(Tb4, Tb5);
Tbd = VMUL(LDK(KP866025403), VADD(Tb8, Tb7));
Tbe = BYTWJ(&(W[TWVL * 6]),VFMAI(Tbd, Tbc));
Tbf = BYTWJ(&(W[TWVL * 14]),VFNMSI(Tbd, Tbc));
ST(&(x[WS(vs, 4) + WS(rs, 11)]),Tbe,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
ST(&(x[WS(vs, 8) + WS(rs, 11)]),Tbf,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
}
{
V T7q, T7r, T7o, T7p;
T7o = VADD(T7g, T7h);
T7p = VMUL(LDK(KP866025403), VADD(T7k, T7j));
T7q = BYTWJ(&(W[TWVL * 6]),VFMAI(T7p, T7o));
T7r = BYTWJ(&(W[TWVL * 14]),VFNMSI(T7p, T7o));
ST(&(x[WS(vs, 4) + WS(rs, 7)]),T7q,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
ST(&(x[WS(vs, 8) + WS(rs, 7)]),T7r,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
}
{
V T1I, T1J, T1G, T1H;
T1G = VADD(T1y, T1z);
T1H = VMUL(LDK(KP866025403), VADD(T1C, T1B));
T1I = BYTWJ(&(W[TWVL * 6]),VFMAI(T1H, T1G));
T1J = BYTWJ(&(W[TWVL * 14]),VFNMSI(T1H, T1G));
ST(&(x[WS(vs, 4) + WS(rs, 1)]),T1I,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
ST(&(x[WS(vs, 8) + WS(rs, 1)]),T1J,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
}
{
V Tah, Tai, Taf, Tag;
Taf = VADD(Ta7, Ta8);
Tag = VMUL(LDK(KP866025403), VADD(Tab, Taa));
Tah = BYTWJ(&(W[TWVL * 6]),VFMAI(Tag, Taf));
Tai = BYTWJ(&(W[TWVL * 14]),VFNMSI(Tag, Taf));
ST(&(x[WS(vs, 4) + WS(rs, 10)]),Tah,ms,&(x[WS(vs, 4)]));
ST(&(x[WS(vs, 8) + WS(rs, 10)]),Tai,ms,&(x[WS(vs, 8)]));
}
{
V T2F, T2G, T2D, T2E;
T2D = VADD(T2v, T2w);
T2E = VMUL(LDK(KP866025403), VADD(T2z, T2y));
T2F = BYTWJ(&(W[TWVL * 6]),VFMAI(T2E, T2D));
T2G = BYTWJ(&(W[TWVL * 14]),VFNMSI(T2E, T2D));
ST(&(x[WS(vs, 4) + WS(rs, 2)]),T2F,ms,&(x[WS(vs, 4)]));
ST(&(x[WS(vs, 8) + WS(rs, 2)]),T2G,ms,&(x[WS(vs, 8)]));
}
{
V T8n, T8o, T8l, T8m;
T8l = VADD(T8d, T8e);
T8m = VMUL(LDK(KP866025403), VADD(T8h, T8g));
T8n = BYTWJ(&(W[TWVL * 6]),VFMAI(T8m, T8l));
T8o = BYTWJ(&(W[TWVL * 14]),VFNMSI(T8m, T8l));
ST(&(x[WS(vs, 4) + WS(rs, 8)]),T8n,ms,&(x[WS(vs, 4)]));
ST(&(x[WS(vs, 8) + WS(rs, 8)]),T8o,ms,&(x[WS(vs, 8)]));
}
{
V T3C, T3D, T3A, T3B;
T3A = VADD(T3s, T3t);
T3B = VMUL(LDK(KP866025403), VADD(T3w, T3v));
T3C = BYTWJ(&(W[TWVL * 6]),VFMAI(T3B, T3A));
T3D = BYTWJ(&(W[TWVL * 14]),VFNMSI(T3B, T3A));
ST(&(x[WS(vs, 4) + WS(rs, 3)]),T3C,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
ST(&(x[WS(vs, 8) + WS(rs, 3)]),T3D,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
}
{
V T4z, T4A, T4x, T4y;
T4x = VADD(T4p, T4q);
T4y = VMUL(LDK(KP866025403), VADD(T4t, T4s));
T4z = BYTWJ(&(W[TWVL * 6]),VFMAI(T4y, T4x));
T4A = BYTWJ(&(W[TWVL * 14]),VFNMSI(T4y, T4x));
ST(&(x[WS(vs, 4) + WS(rs, 4)]),T4z,ms,&(x[WS(vs, 4)]));
ST(&(x[WS(vs, 8) + WS(rs, 4)]),T4A,ms,&(x[WS(vs, 8)]));
}
{
V T9k, T9l, T9i, T9j;
T9i = VADD(T9a, T9b);
T9j = VMUL(LDK(KP866025403), VADD(T9e, T9d));
T9k = BYTWJ(&(W[TWVL * 6]),VFMAI(T9j, T9i));
T9l = BYTWJ(&(W[TWVL * 14]),VFNMSI(T9j, T9i));
ST(&(x[WS(vs, 4) + WS(rs, 9)]),T9k,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
ST(&(x[WS(vs, 8) + WS(rs, 9)]),T9l,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
}
{
V TT, TU, TP, TS;
TP = VSUB(TN, TO);
TS = VSUB(TQ, TR);
TT = BYTWJ(&(W[TWVL * 16]),VFNMSI(TS, TP));
TU = BYTWJ(&(W[TWVL * 4]),VFMAI(TS, TP));
ST(&(x[WS(vs, 9)]),TT,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3)]),TU,ms,&(x[WS(vs, 3)]));
}
{
V T6B, T6C, T6x, T6A;
T6x = VSUB(T6v, T6w);
T6A = VSUB(T6y, T6z);
T6B = BYTWJ(&(W[TWVL * 16]),VFNMSI(T6A, T6x));
T6C = BYTWJ(&(W[TWVL * 4]),VFMAI(T6A, T6x));
ST(&(x[WS(vs, 9) + WS(rs, 6)]),T6B,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 6)]),T6C,ms,&(x[WS(vs, 3)]));
}
{
V T3K, T3L, T3G, T3J;
T3G = VSUB(T3E, T3F);
T3J = VSUB(T3H, T3I);
T3K = BYTWJ(&(W[TWVL * 16]),VFNMSI(T3J, T3G));
T3L = BYTWJ(&(W[TWVL * 4]),VFMAI(T3J, T3G));
ST(&(x[WS(vs, 9) + WS(rs, 3)]),T3K,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 3)]),T3L,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V T9s, T9t, T9o, T9r;
T9o = VSUB(T9m, T9n);
T9r = VSUB(T9p, T9q);
T9s = BYTWJ(&(W[TWVL * 16]),VFNMSI(T9r, T9o));
T9t = BYTWJ(&(W[TWVL * 4]),VFMAI(T9r, T9o));
ST(&(x[WS(vs, 9) + WS(rs, 9)]),T9s,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 9)]),T9t,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V T7y, T7z, T7u, T7x;
T7u = VSUB(T7s, T7t);
T7x = VSUB(T7v, T7w);
T7y = BYTWJ(&(W[TWVL * 16]),VFNMSI(T7x, T7u));
T7z = BYTWJ(&(W[TWVL * 4]),VFMAI(T7x, T7u));
ST(&(x[WS(vs, 9) + WS(rs, 7)]),T7y,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 7)]),T7z,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V Tap, Taq, Tal, Tao;
Tal = VSUB(Taj, Tak);
Tao = VSUB(Tam, Tan);
Tap = BYTWJ(&(W[TWVL * 16]),VFNMSI(Tao, Tal));
Taq = BYTWJ(&(W[TWVL * 4]),VFMAI(Tao, Tal));
ST(&(x[WS(vs, 9) + WS(rs, 10)]),Tap,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 10)]),Taq,ms,&(x[WS(vs, 3)]));
}
{
V Tbm, Tbn, Tbi, Tbl;
Tbi = VSUB(Tbg, Tbh);
Tbl = VSUB(Tbj, Tbk);
Tbm = BYTWJ(&(W[TWVL * 16]),VFNMSI(Tbl, Tbi));
Tbn = BYTWJ(&(W[TWVL * 4]),VFMAI(Tbl, Tbi));
ST(&(x[WS(vs, 9) + WS(rs, 11)]),Tbm,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 11)]),Tbn,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V T8v, T8w, T8r, T8u;
T8r = VSUB(T8p, T8q);
T8u = VSUB(T8s, T8t);
T8v = BYTWJ(&(W[TWVL * 16]),VFNMSI(T8u, T8r));
T8w = BYTWJ(&(W[TWVL * 4]),VFMAI(T8u, T8r));
ST(&(x[WS(vs, 9) + WS(rs, 8)]),T8v,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 8)]),T8w,ms,&(x[WS(vs, 3)]));
}
{
V T2N, T2O, T2J, T2M;
T2J = VSUB(T2H, T2I);
T2M = VSUB(T2K, T2L);
T2N = BYTWJ(&(W[TWVL * 16]),VFNMSI(T2M, T2J));
T2O = BYTWJ(&(W[TWVL * 4]),VFMAI(T2M, T2J));
ST(&(x[WS(vs, 9) + WS(rs, 2)]),T2N,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 2)]),T2O,ms,&(x[WS(vs, 3)]));
}
{
V T4H, T4I, T4D, T4G;
T4D = VSUB(T4B, T4C);
T4G = VSUB(T4E, T4F);
T4H = BYTWJ(&(W[TWVL * 16]),VFNMSI(T4G, T4D));
T4I = BYTWJ(&(W[TWVL * 4]),VFMAI(T4G, T4D));
ST(&(x[WS(vs, 9) + WS(rs, 4)]),T4H,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 4)]),T4I,ms,&(x[WS(vs, 3)]));
}
{
V T5E, T5F, T5A, T5D;
T5A = VSUB(T5y, T5z);
T5D = VSUB(T5B, T5C);
T5E = BYTWJ(&(W[TWVL * 16]),VFNMSI(T5D, T5A));
T5F = BYTWJ(&(W[TWVL * 4]),VFMAI(T5D, T5A));
ST(&(x[WS(vs, 9) + WS(rs, 5)]),T5E,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 5)]),T5F,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V T1Q, T1R, T1M, T1P;
T1M = VSUB(T1K, T1L);
T1P = VSUB(T1N, T1O);
T1Q = BYTWJ(&(W[TWVL * 16]),VFNMSI(T1P, T1M));
T1R = BYTWJ(&(W[TWVL * 4]),VFMAI(T1P, T1M));
ST(&(x[WS(vs, 9) + WS(rs, 1)]),T1Q,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 1)]),T1R,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
}
VLEAVE();}


static const tw_instr twinstr[] = {
VTW(0,1),
VTW(0,2),
VTW(0,3),
VTW(0,4),
VTW(0,5),
VTW(0,6),
VTW(0,7),
VTW(0,8),
VTW(0,9),
VTW(0,10),
VTW(0,11),
{TW_NEXT, VL, 0}};

static const ct_desc desc = {12, XSIMD_STRING("q1fv_12"), twinstr, &GENUS, { 492, 288, 216, 0 }, 0, 0, 0};

void XSIMD(codelet_q1fv_12)(planner *p)
{
X(kdft_difsq_register)(p, q1fv_12, &desc);
}
#else

/* Generated by: ../../../genfft/gen_twidsq_c.native -simd -compact -variables 4 -pipeline-latency 8 -n 12 -dif -name q1fv_12 -include dft/simd/q1f.h */

/*
 * This function contains 708 FP additions, 360 FP multiplications,
 * (or, 660 additions, 312 multiplications, 48 fused multiply/add),
 * 160 stack variables, 2 constants, and 288 memory accesses
 */
#include "dft/simd/q1f.h"

static void q1fv_12(R * ri, R * ii, const R * W, stride rs, stride vs, INT mb, INT me, INT ms)
{
DVK(KP500000000, +0.500000000000000000000000000000000000000000000);
DVK(KP866025403, +0.866025403784438646763723170752936183471402627);
{
INT m;
R * x;
x = ri;
for (m = mb, W = W + (mb * ((TWVL/VL) * 22)); m < me; m = m + VL, x = x + (VL * ms), W = W + (TWVL * 22), MAKE_VOLATILE_STRIDE(24, rs), MAKE_VOLATILE_STRIDE(24, vs)){
V T5, TQ, Ta, TB, Tu, TM, T8E, T9p, T8J, T9a, T93, T9l, T8P, T9o, T8U;
V T96, T9d, T9m, Tg, TP, Tl, Tx, TE, TN, T2a, T2J, T2f, T2r, T2y, T2H;
V TaJ, Tbi, TaO, Tb0, Tb7, Tbg, Tay, Tbj, TaD, Tb4, TaX, Tbf, T1Z, T2K, T24;
V T2v, T2o, T2G, T1d, T1M, T1i, T1u, T1B, T1K, T9M, Tal, T9R, Ta3, Taa, Taj;
V T9B, Tam, T9G, Ta7, Ta0, Tai, T12, T1N, T17, T1y, T1r, T1J, T2W, T3H, T31;
V T3s, T3l, T3D, T5N, T6y, T5S, T6j, T6c, T6u, T5Y, T6x, T63, T6f, T6m, T6v;
V T37, T3G, T3c, T3o, T3v, T3E, T51, T5A, T56, T5i, T5p, T5y, T7S, T8r, T7X;
V T89, T8g, T8p, T7H, T8s, T7M, T8d, T86, T8o, T4Q, T5B, T4V, T5m, T5f, T5x;
V T44, T4D, T49, T4l, T4s, T4B, T6V, T7u, T70, T7c, T7j, T7s, T6K, T7v, T6P;
V T7g, T79, T7r, T3T, T4E, T3Y, T4p, T4i, T4A;
{
V T1, T6, T4, Tz, T9, TA, Ts, Tt;
T1 = LD(&(x[0]), ms, &(x[0]));
T6 = LD(&(x[WS(rs, 6)]), ms, &(x[0]));
{
V T2, T3, T7, T8;
T2 = LD(&(x[WS(rs, 4)]), ms, &(x[0]));
T3 = LD(&(x[WS(rs, 8)]), ms, &(x[0]));
T4 = VADD(T2, T3);
Tz = VSUB(T3, T2);
T7 = LD(&(x[WS(rs, 10)]), ms, &(x[0]));
T8 = LD(&(x[WS(rs, 2)]), ms, &(x[0]));
T9 = VADD(T7, T8);
TA = VSUB(T8, T7);
}
T5 = VADD(T1, T4);
TQ = VADD(Tz, TA);
Ta = VADD(T6, T9);
TB = VMUL(LDK(KP866025403), VSUB(Tz, TA));
Ts = VFNMS(LDK(KP500000000), T4, T1);
Tt = VFNMS(LDK(KP500000000), T9, T6);
Tu = VSUB(Ts, Tt);
TM = VADD(Ts, Tt);
}
{
V T8A, T8F, T8D, T98, T8I, T99, T91, T92;
T8A = LD(&(x[WS(vs, 9)]), ms, &(x[WS(vs, 9)]));
T8F = LD(&(x[WS(vs, 9) + WS(rs, 6)]), ms, &(x[WS(vs, 9)]));
{
V T8B, T8C, T8G, T8H;
T8B = LD(&(x[WS(vs, 9) + WS(rs, 4)]), ms, &(x[WS(vs, 9)]));
T8C = LD(&(x[WS(vs, 9) + WS(rs, 8)]), ms, &(x[WS(vs, 9)]));
T8D = VADD(T8B, T8C);
T98 = VSUB(T8C, T8B);
T8G = LD(&(x[WS(vs, 9) + WS(rs, 10)]), ms, &(x[WS(vs, 9)]));
T8H = LD(&(x[WS(vs, 9) + WS(rs, 2)]), ms, &(x[WS(vs, 9)]));
T8I = VADD(T8G, T8H);
T99 = VSUB(T8H, T8G);
}
T8E = VADD(T8A, T8D);
T9p = VADD(T98, T99);
T8J = VADD(T8F, T8I);
T9a = VMUL(LDK(KP866025403), VSUB(T98, T99));
T91 = VFNMS(LDK(KP500000000), T8D, T8A);
T92 = VFNMS(LDK(KP500000000), T8I, T8F);
T93 = VSUB(T91, T92);
T9l = VADD(T91, T92);
}
{
V T8L, T8Q, T8O, T94, T8T, T95, T9b, T9c;
T8L = LD(&(x[WS(vs, 9) + WS(rs, 3)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8Q = LD(&(x[WS(vs, 9) + WS(rs, 9)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
{
V T8M, T8N, T8R, T8S;
T8M = LD(&(x[WS(vs, 9) + WS(rs, 7)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8N = LD(&(x[WS(vs, 9) + WS(rs, 11)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8O = VADD(T8M, T8N);
T94 = VSUB(T8N, T8M);
T8R = LD(&(x[WS(vs, 9) + WS(rs, 1)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8S = LD(&(x[WS(vs, 9) + WS(rs, 5)]), ms, &(x[WS(vs, 9) + WS(rs, 1)]));
T8T = VADD(T8R, T8S);
T95 = VSUB(T8S, T8R);
}
T8P = VADD(T8L, T8O);
T9o = VADD(T94, T95);
T8U = VADD(T8Q, T8T);
T96 = VMUL(LDK(KP866025403), VSUB(T94, T95));
T9b = VFNMS(LDK(KP500000000), T8O, T8L);
T9c = VFNMS(LDK(KP500000000), T8T, T8Q);
T9d = VSUB(T9b, T9c);
T9m = VADD(T9b, T9c);
}
{
V Tc, Th, Tf, Tv, Tk, Tw, TC, TD;
Tc = LD(&(x[WS(rs, 3)]), ms, &(x[WS(rs, 1)]));
Th = LD(&(x[WS(rs, 9)]), ms, &(x[WS(rs, 1)]));
{
V Td, Te, Ti, Tj;
Td = LD(&(x[WS(rs, 7)]), ms, &(x[WS(rs, 1)]));
Te = LD(&(x[WS(rs, 11)]), ms, &(x[WS(rs, 1)]));
Tf = VADD(Td, Te);
Tv = VSUB(Te, Td);
Ti = LD(&(x[WS(rs, 1)]), ms, &(x[WS(rs, 1)]));
Tj = LD(&(x[WS(rs, 5)]), ms, &(x[WS(rs, 1)]));
Tk = VADD(Ti, Tj);
Tw = VSUB(Tj, Ti);
}
Tg = VADD(Tc, Tf);
TP = VADD(Tv, Tw);
Tl = VADD(Th, Tk);
Tx = VMUL(LDK(KP866025403), VSUB(Tv, Tw));
TC = VFNMS(LDK(KP500000000), Tf, Tc);
TD = VFNMS(LDK(KP500000000), Tk, Th);
TE = VSUB(TC, TD);
TN = VADD(TC, TD);
}
{
V T26, T2b, T29, T2p, T2e, T2q, T2w, T2x;
T26 = LD(&(x[WS(vs, 2) + WS(rs, 3)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T2b = LD(&(x[WS(vs, 2) + WS(rs, 9)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
{
V T27, T28, T2c, T2d;
T27 = LD(&(x[WS(vs, 2) + WS(rs, 7)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T28 = LD(&(x[WS(vs, 2) + WS(rs, 11)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T29 = VADD(T27, T28);
T2p = VSUB(T28, T27);
T2c = LD(&(x[WS(vs, 2) + WS(rs, 1)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T2d = LD(&(x[WS(vs, 2) + WS(rs, 5)]), ms, &(x[WS(vs, 2) + WS(rs, 1)]));
T2e = VADD(T2c, T2d);
T2q = VSUB(T2d, T2c);
}
T2a = VADD(T26, T29);
T2J = VADD(T2p, T2q);
T2f = VADD(T2b, T2e);
T2r = VMUL(LDK(KP866025403), VSUB(T2p, T2q));
T2w = VFNMS(LDK(KP500000000), T29, T26);
T2x = VFNMS(LDK(KP500000000), T2e, T2b);
T2y = VSUB(T2w, T2x);
T2H = VADD(T2w, T2x);
}
{
V TaF, TaK, TaI, TaY, TaN, TaZ, Tb5, Tb6;
TaF = LD(&(x[WS(vs, 11) + WS(rs, 3)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaK = LD(&(x[WS(vs, 11) + WS(rs, 9)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
{
V TaG, TaH, TaL, TaM;
TaG = LD(&(x[WS(vs, 11) + WS(rs, 7)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaH = LD(&(x[WS(vs, 11) + WS(rs, 11)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaI = VADD(TaG, TaH);
TaY = VSUB(TaH, TaG);
TaL = LD(&(x[WS(vs, 11) + WS(rs, 1)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaM = LD(&(x[WS(vs, 11) + WS(rs, 5)]), ms, &(x[WS(vs, 11) + WS(rs, 1)]));
TaN = VADD(TaL, TaM);
TaZ = VSUB(TaM, TaL);
}
TaJ = VADD(TaF, TaI);
Tbi = VADD(TaY, TaZ);
TaO = VADD(TaK, TaN);
Tb0 = VMUL(LDK(KP866025403), VSUB(TaY, TaZ));
Tb5 = VFNMS(LDK(KP500000000), TaI, TaF);
Tb6 = VFNMS(LDK(KP500000000), TaN, TaK);
Tb7 = VSUB(Tb5, Tb6);
Tbg = VADD(Tb5, Tb6);
}
{
V Tau, Taz, Tax, Tb2, TaC, Tb3, TaV, TaW;
Tau = LD(&(x[WS(vs, 11)]), ms, &(x[WS(vs, 11)]));
Taz = LD(&(x[WS(vs, 11) + WS(rs, 6)]), ms, &(x[WS(vs, 11)]));
{
V Tav, Taw, TaA, TaB;
Tav = LD(&(x[WS(vs, 11) + WS(rs, 4)]), ms, &(x[WS(vs, 11)]));
Taw = LD(&(x[WS(vs, 11) + WS(rs, 8)]), ms, &(x[WS(vs, 11)]));
Tax = VADD(Tav, Taw);
Tb2 = VSUB(Taw, Tav);
TaA = LD(&(x[WS(vs, 11) + WS(rs, 10)]), ms, &(x[WS(vs, 11)]));
TaB = LD(&(x[WS(vs, 11) + WS(rs, 2)]), ms, &(x[WS(vs, 11)]));
TaC = VADD(TaA, TaB);
Tb3 = VSUB(TaB, TaA);
}
Tay = VADD(Tau, Tax);
Tbj = VADD(Tb2, Tb3);
TaD = VADD(Taz, TaC);
Tb4 = VMUL(LDK(KP866025403), VSUB(Tb2, Tb3));
TaV = VFNMS(LDK(KP500000000), Tax, Tau);
TaW = VFNMS(LDK(KP500000000), TaC, Taz);
TaX = VSUB(TaV, TaW);
Tbf = VADD(TaV, TaW);
}
{
V T1V, T20, T1Y, T2t, T23, T2u, T2m, T2n;
T1V = LD(&(x[WS(vs, 2)]), ms, &(x[WS(vs, 2)]));
T20 = LD(&(x[WS(vs, 2) + WS(rs, 6)]), ms, &(x[WS(vs, 2)]));
{
V T1W, T1X, T21, T22;
T1W = LD(&(x[WS(vs, 2) + WS(rs, 4)]), ms, &(x[WS(vs, 2)]));
T1X = LD(&(x[WS(vs, 2) + WS(rs, 8)]), ms, &(x[WS(vs, 2)]));
T1Y = VADD(T1W, T1X);
T2t = VSUB(T1X, T1W);
T21 = LD(&(x[WS(vs, 2) + WS(rs, 10)]), ms, &(x[WS(vs, 2)]));
T22 = LD(&(x[WS(vs, 2) + WS(rs, 2)]), ms, &(x[WS(vs, 2)]));
T23 = VADD(T21, T22);
T2u = VSUB(T22, T21);
}
T1Z = VADD(T1V, T1Y);
T2K = VADD(T2t, T2u);
T24 = VADD(T20, T23);
T2v = VMUL(LDK(KP866025403), VSUB(T2t, T2u));
T2m = VFNMS(LDK(KP500000000), T1Y, T1V);
T2n = VFNMS(LDK(KP500000000), T23, T20);
T2o = VSUB(T2m, T2n);
T2G = VADD(T2m, T2n);
}
{
V T19, T1e, T1c, T1s, T1h, T1t, T1z, T1A;
T19 = LD(&(x[WS(vs, 1) + WS(rs, 3)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1e = LD(&(x[WS(vs, 1) + WS(rs, 9)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
{
V T1a, T1b, T1f, T1g;
T1a = LD(&(x[WS(vs, 1) + WS(rs, 7)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1b = LD(&(x[WS(vs, 1) + WS(rs, 11)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1c = VADD(T1a, T1b);
T1s = VSUB(T1b, T1a);
T1f = LD(&(x[WS(vs, 1) + WS(rs, 1)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1g = LD(&(x[WS(vs, 1) + WS(rs, 5)]), ms, &(x[WS(vs, 1) + WS(rs, 1)]));
T1h = VADD(T1f, T1g);
T1t = VSUB(T1g, T1f);
}
T1d = VADD(T19, T1c);
T1M = VADD(T1s, T1t);
T1i = VADD(T1e, T1h);
T1u = VMUL(LDK(KP866025403), VSUB(T1s, T1t));
T1z = VFNMS(LDK(KP500000000), T1c, T19);
T1A = VFNMS(LDK(KP500000000), T1h, T1e);
T1B = VSUB(T1z, T1A);
T1K = VADD(T1z, T1A);
}
{
V T9I, T9N, T9L, Ta1, T9Q, Ta2, Ta8, Ta9;
T9I = LD(&(x[WS(vs, 10) + WS(rs, 3)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9N = LD(&(x[WS(vs, 10) + WS(rs, 9)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
{
V T9J, T9K, T9O, T9P;
T9J = LD(&(x[WS(vs, 10) + WS(rs, 7)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9K = LD(&(x[WS(vs, 10) + WS(rs, 11)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9L = VADD(T9J, T9K);
Ta1 = VSUB(T9K, T9J);
T9O = LD(&(x[WS(vs, 10) + WS(rs, 1)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9P = LD(&(x[WS(vs, 10) + WS(rs, 5)]), ms, &(x[WS(vs, 10) + WS(rs, 1)]));
T9Q = VADD(T9O, T9P);
Ta2 = VSUB(T9P, T9O);
}
T9M = VADD(T9I, T9L);
Tal = VADD(Ta1, Ta2);
T9R = VADD(T9N, T9Q);
Ta3 = VMUL(LDK(KP866025403), VSUB(Ta1, Ta2));
Ta8 = VFNMS(LDK(KP500000000), T9L, T9I);
Ta9 = VFNMS(LDK(KP500000000), T9Q, T9N);
Taa = VSUB(Ta8, Ta9);
Taj = VADD(Ta8, Ta9);
}
{
V T9x, T9C, T9A, Ta5, T9F, Ta6, T9Y, T9Z;
T9x = LD(&(x[WS(vs, 10)]), ms, &(x[WS(vs, 10)]));
T9C = LD(&(x[WS(vs, 10) + WS(rs, 6)]), ms, &(x[WS(vs, 10)]));
{
V T9y, T9z, T9D, T9E;
T9y = LD(&(x[WS(vs, 10) + WS(rs, 4)]), ms, &(x[WS(vs, 10)]));
T9z = LD(&(x[WS(vs, 10) + WS(rs, 8)]), ms, &(x[WS(vs, 10)]));
T9A = VADD(T9y, T9z);
Ta5 = VSUB(T9z, T9y);
T9D = LD(&(x[WS(vs, 10) + WS(rs, 10)]), ms, &(x[WS(vs, 10)]));
T9E = LD(&(x[WS(vs, 10) + WS(rs, 2)]), ms, &(x[WS(vs, 10)]));
T9F = VADD(T9D, T9E);
Ta6 = VSUB(T9E, T9D);
}
T9B = VADD(T9x, T9A);
Tam = VADD(Ta5, Ta6);
T9G = VADD(T9C, T9F);
Ta7 = VMUL(LDK(KP866025403), VSUB(Ta5, Ta6));
T9Y = VFNMS(LDK(KP500000000), T9A, T9x);
T9Z = VFNMS(LDK(KP500000000), T9F, T9C);
Ta0 = VSUB(T9Y, T9Z);
Tai = VADD(T9Y, T9Z);
}
{
V TY, T13, T11, T1w, T16, T1x, T1p, T1q;
TY = LD(&(x[WS(vs, 1)]), ms, &(x[WS(vs, 1)]));
T13 = LD(&(x[WS(vs, 1) + WS(rs, 6)]), ms, &(x[WS(vs, 1)]));
{
V TZ, T10, T14, T15;
TZ = LD(&(x[WS(vs, 1) + WS(rs, 4)]), ms, &(x[WS(vs, 1)]));
T10 = LD(&(x[WS(vs, 1) + WS(rs, 8)]), ms, &(x[WS(vs, 1)]));
T11 = VADD(TZ, T10);
T1w = VSUB(T10, TZ);
T14 = LD(&(x[WS(vs, 1) + WS(rs, 10)]), ms, &(x[WS(vs, 1)]));
T15 = LD(&(x[WS(vs, 1) + WS(rs, 2)]), ms, &(x[WS(vs, 1)]));
T16 = VADD(T14, T15);
T1x = VSUB(T15, T14);
}
T12 = VADD(TY, T11);
T1N = VADD(T1w, T1x);
T17 = VADD(T13, T16);
T1y = VMUL(LDK(KP866025403), VSUB(T1w, T1x));
T1p = VFNMS(LDK(KP500000000), T11, TY);
T1q = VFNMS(LDK(KP500000000), T16, T13);
T1r = VSUB(T1p, T1q);
T1J = VADD(T1p, T1q);
}
{
V T2S, T2X, T2V, T3q, T30, T3r, T3j, T3k;
T2S = LD(&(x[WS(vs, 3)]), ms, &(x[WS(vs, 3)]));
T2X = LD(&(x[WS(vs, 3) + WS(rs, 6)]), ms, &(x[WS(vs, 3)]));
{
V T2T, T2U, T2Y, T2Z;
T2T = LD(&(x[WS(vs, 3) + WS(rs, 4)]), ms, &(x[WS(vs, 3)]));
T2U = LD(&(x[WS(vs, 3) + WS(rs, 8)]), ms, &(x[WS(vs, 3)]));
T2V = VADD(T2T, T2U);
T3q = VSUB(T2U, T2T);
T2Y = LD(&(x[WS(vs, 3) + WS(rs, 10)]), ms, &(x[WS(vs, 3)]));
T2Z = LD(&(x[WS(vs, 3) + WS(rs, 2)]), ms, &(x[WS(vs, 3)]));
T30 = VADD(T2Y, T2Z);
T3r = VSUB(T2Z, T2Y);
}
T2W = VADD(T2S, T2V);
T3H = VADD(T3q, T3r);
T31 = VADD(T2X, T30);
T3s = VMUL(LDK(KP866025403), VSUB(T3q, T3r));
T3j = VFNMS(LDK(KP500000000), T2V, T2S);
T3k = VFNMS(LDK(KP500000000), T30, T2X);
T3l = VSUB(T3j, T3k);
T3D = VADD(T3j, T3k);
}
{
V T5J, T5O, T5M, T6h, T5R, T6i, T6a, T6b;
T5J = LD(&(x[WS(vs, 6)]), ms, &(x[WS(vs, 6)]));
T5O = LD(&(x[WS(vs, 6) + WS(rs, 6)]), ms, &(x[WS(vs, 6)]));
{
V T5K, T5L, T5P, T5Q;
T5K = LD(&(x[WS(vs, 6) + WS(rs, 4)]), ms, &(x[WS(vs, 6)]));
T5L = LD(&(x[WS(vs, 6) + WS(rs, 8)]), ms, &(x[WS(vs, 6)]));
T5M = VADD(T5K, T5L);
T6h = VSUB(T5L, T5K);
T5P = LD(&(x[WS(vs, 6) + WS(rs, 10)]), ms, &(x[WS(vs, 6)]));
T5Q = LD(&(x[WS(vs, 6) + WS(rs, 2)]), ms, &(x[WS(vs, 6)]));
T5R = VADD(T5P, T5Q);
T6i = VSUB(T5Q, T5P);
}
T5N = VADD(T5J, T5M);
T6y = VADD(T6h, T6i);
T5S = VADD(T5O, T5R);
T6j = VMUL(LDK(KP866025403), VSUB(T6h, T6i));
T6a = VFNMS(LDK(KP500000000), T5M, T5J);
T6b = VFNMS(LDK(KP500000000), T5R, T5O);
T6c = VSUB(T6a, T6b);
T6u = VADD(T6a, T6b);
}
{
V T5U, T5Z, T5X, T6d, T62, T6e, T6k, T6l;
T5U = LD(&(x[WS(vs, 6) + WS(rs, 3)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5Z = LD(&(x[WS(vs, 6) + WS(rs, 9)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
{
V T5V, T5W, T60, T61;
T5V = LD(&(x[WS(vs, 6) + WS(rs, 7)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5W = LD(&(x[WS(vs, 6) + WS(rs, 11)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T5X = VADD(T5V, T5W);
T6d = VSUB(T5W, T5V);
T60 = LD(&(x[WS(vs, 6) + WS(rs, 1)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T61 = LD(&(x[WS(vs, 6) + WS(rs, 5)]), ms, &(x[WS(vs, 6) + WS(rs, 1)]));
T62 = VADD(T60, T61);
T6e = VSUB(T61, T60);
}
T5Y = VADD(T5U, T5X);
T6x = VADD(T6d, T6e);
T63 = VADD(T5Z, T62);
T6f = VMUL(LDK(KP866025403), VSUB(T6d, T6e));
T6k = VFNMS(LDK(KP500000000), T5X, T5U);
T6l = VFNMS(LDK(KP500000000), T62, T5Z);
T6m = VSUB(T6k, T6l);
T6v = VADD(T6k, T6l);
}
{
V T33, T38, T36, T3m, T3b, T3n, T3t, T3u;
T33 = LD(&(x[WS(vs, 3) + WS(rs, 3)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T38 = LD(&(x[WS(vs, 3) + WS(rs, 9)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
{
V T34, T35, T39, T3a;
T34 = LD(&(x[WS(vs, 3) + WS(rs, 7)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T35 = LD(&(x[WS(vs, 3) + WS(rs, 11)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T36 = VADD(T34, T35);
T3m = VSUB(T35, T34);
T39 = LD(&(x[WS(vs, 3) + WS(rs, 1)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T3a = LD(&(x[WS(vs, 3) + WS(rs, 5)]), ms, &(x[WS(vs, 3) + WS(rs, 1)]));
T3b = VADD(T39, T3a);
T3n = VSUB(T3a, T39);
}
T37 = VADD(T33, T36);
T3G = VADD(T3m, T3n);
T3c = VADD(T38, T3b);
T3o = VMUL(LDK(KP866025403), VSUB(T3m, T3n));
T3t = VFNMS(LDK(KP500000000), T36, T33);
T3u = VFNMS(LDK(KP500000000), T3b, T38);
T3v = VSUB(T3t, T3u);
T3E = VADD(T3t, T3u);
}
{
V T4X, T52, T50, T5g, T55, T5h, T5n, T5o;
T4X = LD(&(x[WS(vs, 5) + WS(rs, 3)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T52 = LD(&(x[WS(vs, 5) + WS(rs, 9)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
{
V T4Y, T4Z, T53, T54;
T4Y = LD(&(x[WS(vs, 5) + WS(rs, 7)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T4Z = LD(&(x[WS(vs, 5) + WS(rs, 11)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T50 = VADD(T4Y, T4Z);
T5g = VSUB(T4Z, T4Y);
T53 = LD(&(x[WS(vs, 5) + WS(rs, 1)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T54 = LD(&(x[WS(vs, 5) + WS(rs, 5)]), ms, &(x[WS(vs, 5) + WS(rs, 1)]));
T55 = VADD(T53, T54);
T5h = VSUB(T54, T53);
}
T51 = VADD(T4X, T50);
T5A = VADD(T5g, T5h);
T56 = VADD(T52, T55);
T5i = VMUL(LDK(KP866025403), VSUB(T5g, T5h));
T5n = VFNMS(LDK(KP500000000), T50, T4X);
T5o = VFNMS(LDK(KP500000000), T55, T52);
T5p = VSUB(T5n, T5o);
T5y = VADD(T5n, T5o);
}
{
V T7O, T7T, T7R, T87, T7W, T88, T8e, T8f;
T7O = LD(&(x[WS(vs, 8) + WS(rs, 3)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7T = LD(&(x[WS(vs, 8) + WS(rs, 9)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
{
V T7P, T7Q, T7U, T7V;
T7P = LD(&(x[WS(vs, 8) + WS(rs, 7)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7Q = LD(&(x[WS(vs, 8) + WS(rs, 11)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7R = VADD(T7P, T7Q);
T87 = VSUB(T7Q, T7P);
T7U = LD(&(x[WS(vs, 8) + WS(rs, 1)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7V = LD(&(x[WS(vs, 8) + WS(rs, 5)]), ms, &(x[WS(vs, 8) + WS(rs, 1)]));
T7W = VADD(T7U, T7V);
T88 = VSUB(T7V, T7U);
}
T7S = VADD(T7O, T7R);
T8r = VADD(T87, T88);
T7X = VADD(T7T, T7W);
T89 = VMUL(LDK(KP866025403), VSUB(T87, T88));
T8e = VFNMS(LDK(KP500000000), T7R, T7O);
T8f = VFNMS(LDK(KP500000000), T7W, T7T);
T8g = VSUB(T8e, T8f);
T8p = VADD(T8e, T8f);
}
{
V T7D, T7I, T7G, T8b, T7L, T8c, T84, T85;
T7D = LD(&(x[WS(vs, 8)]), ms, &(x[WS(vs, 8)]));
T7I = LD(&(x[WS(vs, 8) + WS(rs, 6)]), ms, &(x[WS(vs, 8)]));
{
V T7E, T7F, T7J, T7K;
T7E = LD(&(x[WS(vs, 8) + WS(rs, 4)]), ms, &(x[WS(vs, 8)]));
T7F = LD(&(x[WS(vs, 8) + WS(rs, 8)]), ms, &(x[WS(vs, 8)]));
T7G = VADD(T7E, T7F);
T8b = VSUB(T7F, T7E);
T7J = LD(&(x[WS(vs, 8) + WS(rs, 10)]), ms, &(x[WS(vs, 8)]));
T7K = LD(&(x[WS(vs, 8) + WS(rs, 2)]), ms, &(x[WS(vs, 8)]));
T7L = VADD(T7J, T7K);
T8c = VSUB(T7K, T7J);
}
T7H = VADD(T7D, T7G);
T8s = VADD(T8b, T8c);
T7M = VADD(T7I, T7L);
T8d = VMUL(LDK(KP866025403), VSUB(T8b, T8c));
T84 = VFNMS(LDK(KP500000000), T7G, T7D);
T85 = VFNMS(LDK(KP500000000), T7L, T7I);
T86 = VSUB(T84, T85);
T8o = VADD(T84, T85);
}
{
V T4M, T4R, T4P, T5k, T4U, T5l, T5d, T5e;
T4M = LD(&(x[WS(vs, 5)]), ms, &(x[WS(vs, 5)]));
T4R = LD(&(x[WS(vs, 5) + WS(rs, 6)]), ms, &(x[WS(vs, 5)]));
{
V T4N, T4O, T4S, T4T;
T4N = LD(&(x[WS(vs, 5) + WS(rs, 4)]), ms, &(x[WS(vs, 5)]));
T4O = LD(&(x[WS(vs, 5) + WS(rs, 8)]), ms, &(x[WS(vs, 5)]));
T4P = VADD(T4N, T4O);
T5k = VSUB(T4O, T4N);
T4S = LD(&(x[WS(vs, 5) + WS(rs, 10)]), ms, &(x[WS(vs, 5)]));
T4T = LD(&(x[WS(vs, 5) + WS(rs, 2)]), ms, &(x[WS(vs, 5)]));
T4U = VADD(T4S, T4T);
T5l = VSUB(T4T, T4S);
}
T4Q = VADD(T4M, T4P);
T5B = VADD(T5k, T5l);
T4V = VADD(T4R, T4U);
T5m = VMUL(LDK(KP866025403), VSUB(T5k, T5l));
T5d = VFNMS(LDK(KP500000000), T4P, T4M);
T5e = VFNMS(LDK(KP500000000), T4U, T4R);
T5f = VSUB(T5d, T5e);
T5x = VADD(T5d, T5e);
}
{
V T40, T45, T43, T4j, T48, T4k, T4q, T4r;
T40 = LD(&(x[WS(vs, 4) + WS(rs, 3)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T45 = LD(&(x[WS(vs, 4) + WS(rs, 9)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
{
V T41, T42, T46, T47;
T41 = LD(&(x[WS(vs, 4) + WS(rs, 7)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T42 = LD(&(x[WS(vs, 4) + WS(rs, 11)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T43 = VADD(T41, T42);
T4j = VSUB(T42, T41);
T46 = LD(&(x[WS(vs, 4) + WS(rs, 1)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T47 = LD(&(x[WS(vs, 4) + WS(rs, 5)]), ms, &(x[WS(vs, 4) + WS(rs, 1)]));
T48 = VADD(T46, T47);
T4k = VSUB(T47, T46);
}
T44 = VADD(T40, T43);
T4D = VADD(T4j, T4k);
T49 = VADD(T45, T48);
T4l = VMUL(LDK(KP866025403), VSUB(T4j, T4k));
T4q = VFNMS(LDK(KP500000000), T43, T40);
T4r = VFNMS(LDK(KP500000000), T48, T45);
T4s = VSUB(T4q, T4r);
T4B = VADD(T4q, T4r);
}
{
V T6R, T6W, T6U, T7a, T6Z, T7b, T7h, T7i;
T6R = LD(&(x[WS(vs, 7) + WS(rs, 3)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6W = LD(&(x[WS(vs, 7) + WS(rs, 9)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
{
V T6S, T6T, T6X, T6Y;
T6S = LD(&(x[WS(vs, 7) + WS(rs, 7)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6T = LD(&(x[WS(vs, 7) + WS(rs, 11)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6U = VADD(T6S, T6T);
T7a = VSUB(T6T, T6S);
T6X = LD(&(x[WS(vs, 7) + WS(rs, 1)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6Y = LD(&(x[WS(vs, 7) + WS(rs, 5)]), ms, &(x[WS(vs, 7) + WS(rs, 1)]));
T6Z = VADD(T6X, T6Y);
T7b = VSUB(T6Y, T6X);
}
T6V = VADD(T6R, T6U);
T7u = VADD(T7a, T7b);
T70 = VADD(T6W, T6Z);
T7c = VMUL(LDK(KP866025403), VSUB(T7a, T7b));
T7h = VFNMS(LDK(KP500000000), T6U, T6R);
T7i = VFNMS(LDK(KP500000000), T6Z, T6W);
T7j = VSUB(T7h, T7i);
T7s = VADD(T7h, T7i);
}
{
V T6G, T6L, T6J, T7e, T6O, T7f, T77, T78;
T6G = LD(&(x[WS(vs, 7)]), ms, &(x[WS(vs, 7)]));
T6L = LD(&(x[WS(vs, 7) + WS(rs, 6)]), ms, &(x[WS(vs, 7)]));
{
V T6H, T6I, T6M, T6N;
T6H = LD(&(x[WS(vs, 7) + WS(rs, 4)]), ms, &(x[WS(vs, 7)]));
T6I = LD(&(x[WS(vs, 7) + WS(rs, 8)]), ms, &(x[WS(vs, 7)]));
T6J = VADD(T6H, T6I);
T7e = VSUB(T6I, T6H);
T6M = LD(&(x[WS(vs, 7) + WS(rs, 10)]), ms, &(x[WS(vs, 7)]));
T6N = LD(&(x[WS(vs, 7) + WS(rs, 2)]), ms, &(x[WS(vs, 7)]));
T6O = VADD(T6M, T6N);
T7f = VSUB(T6N, T6M);
}
T6K = VADD(T6G, T6J);
T7v = VADD(T7e, T7f);
T6P = VADD(T6L, T6O);
T7g = VMUL(LDK(KP866025403), VSUB(T7e, T7f));
T77 = VFNMS(LDK(KP500000000), T6J, T6G);
T78 = VFNMS(LDK(KP500000000), T6O, T6L);
T79 = VSUB(T77, T78);
T7r = VADD(T77, T78);
}
{
V T3P, T3U, T3S, T4n, T3X, T4o, T4g, T4h;
T3P = LD(&(x[WS(vs, 4)]), ms, &(x[WS(vs, 4)]));
T3U = LD(&(x[WS(vs, 4) + WS(rs, 6)]), ms, &(x[WS(vs, 4)]));
{
V T3Q, T3R, T3V, T3W;
T3Q = LD(&(x[WS(vs, 4) + WS(rs, 4)]), ms, &(x[WS(vs, 4)]));
T3R = LD(&(x[WS(vs, 4) + WS(rs, 8)]), ms, &(x[WS(vs, 4)]));
T3S = VADD(T3Q, T3R);
T4n = VSUB(T3R, T3Q);
T3V = LD(&(x[WS(vs, 4) + WS(rs, 10)]), ms, &(x[WS(vs, 4)]));
T3W = LD(&(x[WS(vs, 4) + WS(rs, 2)]), ms, &(x[WS(vs, 4)]));
T3X = VADD(T3V, T3W);
T4o = VSUB(T3W, T3V);
}
T3T = VADD(T3P, T3S);
T4E = VADD(T4n, T4o);
T3Y = VADD(T3U, T3X);
T4p = VMUL(LDK(KP866025403), VSUB(T4n, T4o));
T4g = VFNMS(LDK(KP500000000), T3S, T3P);
T4h = VFNMS(LDK(KP500000000), T3X, T3U);
T4i = VSUB(T4g, T4h);
T4A = VADD(T4g, T4h);
}
{
V T5a, T5b, T5c, T9V, T9W, T9X;
{
V Tp, Tq, Tr, T2j, T2k, T2l;
Tp = VADD(T5, Ta);
Tq = VADD(Tg, Tl);
Tr = BYTWJ(&(W[TWVL * 10]),VSUB(Tp, Tq));
ST(&(x[WS(vs, 6)]),Tr,ms,&(x[WS(vs, 6)]));
ST(&(x[0]),VADD(Tp, Tq),ms,&(x[0]));
T2j = VADD(T1Z, T24);
T2k = VADD(T2a, T2f);
T2l = BYTWJ(&(W[TWVL * 10]),VSUB(T2j, T2k));
ST(&(x[WS(vs, 6) + WS(rs, 2)]),T2l,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 2)]),VADD(T2j, T2k),ms,&(x[0]));
}
{
V T1m, T1n, T1o, T3g, T3h, T3i;
T1m = VADD(T12, T17);
T1n = VADD(T1d, T1i);
T1o = BYTWJ(&(W[TWVL * 10]),VSUB(T1m, T1n));
ST(&(x[WS(vs, 6) + WS(rs, 1)]),T1o,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 1)]),VADD(T1m, T1n),ms,&(x[WS(rs, 1)]));
T3g = VADD(T2W, T31);
T3h = VADD(T37, T3c);
T3i = BYTWJ(&(W[TWVL * 10]),VSUB(T3g, T3h));
ST(&(x[WS(vs, 6) + WS(rs, 3)]),T3i,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 3)]),VADD(T3g, T3h),ms,&(x[WS(rs, 1)]));
}
{
V T67, T68, T69, TaS, TaT, TaU;
T67 = VADD(T5N, T5S);
T68 = VADD(T5Y, T63);
T69 = BYTWJ(&(W[TWVL * 10]),VSUB(T67, T68));
ST(&(x[WS(vs, 6) + WS(rs, 6)]),T69,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 6)]),VADD(T67, T68),ms,&(x[0]));
TaS = VADD(Tay, TaD);
TaT = VADD(TaJ, TaO);
TaU = BYTWJ(&(W[TWVL * 10]),VSUB(TaS, TaT));
ST(&(x[WS(vs, 6) + WS(rs, 11)]),TaU,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 11)]),VADD(TaS, TaT),ms,&(x[WS(rs, 1)]));
}
T5a = VADD(T4Q, T4V);
T5b = VADD(T51, T56);
T5c = BYTWJ(&(W[TWVL * 10]),VSUB(T5a, T5b));
ST(&(x[WS(vs, 6) + WS(rs, 5)]),T5c,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 5)]),VADD(T5a, T5b),ms,&(x[WS(rs, 1)]));
{
V T8Y, T8Z, T90, T81, T82, T83;
T8Y = VADD(T8E, T8J);
T8Z = VADD(T8P, T8U);
T90 = BYTWJ(&(W[TWVL * 10]),VSUB(T8Y, T8Z));
ST(&(x[WS(vs, 6) + WS(rs, 9)]),T90,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 9)]),VADD(T8Y, T8Z),ms,&(x[WS(rs, 1)]));
T81 = VADD(T7H, T7M);
T82 = VADD(T7S, T7X);
T83 = BYTWJ(&(W[TWVL * 10]),VSUB(T81, T82));
ST(&(x[WS(vs, 6) + WS(rs, 8)]),T83,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 8)]),VADD(T81, T82),ms,&(x[0]));
}
{
V T4d, T4e, T4f, T74, T75, T76;
T4d = VADD(T3T, T3Y);
T4e = VADD(T44, T49);
T4f = BYTWJ(&(W[TWVL * 10]),VSUB(T4d, T4e));
ST(&(x[WS(vs, 6) + WS(rs, 4)]),T4f,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 4)]),VADD(T4d, T4e),ms,&(x[0]));
T74 = VADD(T6K, T6P);
T75 = VADD(T6V, T70);
T76 = BYTWJ(&(W[TWVL * 10]),VSUB(T74, T75));
ST(&(x[WS(vs, 6) + WS(rs, 7)]),T76,ms,&(x[WS(vs, 6) + WS(rs, 1)]));
ST(&(x[WS(rs, 7)]),VADD(T74, T75),ms,&(x[WS(rs, 1)]));
}
T9V = VADD(T9B, T9G);
T9W = VADD(T9M, T9R);
T9X = BYTWJ(&(W[TWVL * 10]),VSUB(T9V, T9W));
ST(&(x[WS(vs, 6) + WS(rs, 10)]),T9X,ms,&(x[WS(vs, 6)]));
ST(&(x[WS(rs, 10)]),VADD(T9V, T9W),ms,&(x[0]));
{
V T58, T59, T4W, T57;
T4W = VSUB(T4Q, T4V);
T57 = VBYI(VSUB(T51, T56));
T58 = BYTWJ(&(W[TWVL * 16]),VSUB(T4W, T57));
T59 = BYTWJ(&(W[TWVL * 4]),VADD(T4W, T57));
ST(&(x[WS(vs, 9) + WS(rs, 5)]),T58,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 5)]),T59,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V Tn, To, Tb, Tm;
Tb = VSUB(T5, Ta);
Tm = VBYI(VSUB(Tg, Tl));
Tn = BYTWJ(&(W[TWVL * 16]),VSUB(Tb, Tm));
To = BYTWJ(&(W[TWVL * 4]),VADD(Tb, Tm));
ST(&(x[WS(vs, 9)]),Tn,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3)]),To,ms,&(x[WS(vs, 3)]));
}
{
V T65, T66, T5T, T64;
T5T = VSUB(T5N, T5S);
T64 = VBYI(VSUB(T5Y, T63));
T65 = BYTWJ(&(W[TWVL * 16]),VSUB(T5T, T64));
T66 = BYTWJ(&(W[TWVL * 4]),VADD(T5T, T64));
ST(&(x[WS(vs, 9) + WS(rs, 6)]),T65,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 6)]),T66,ms,&(x[WS(vs, 3)]));
}
{
V TaQ, TaR, TaE, TaP;
TaE = VSUB(Tay, TaD);
TaP = VBYI(VSUB(TaJ, TaO));
TaQ = BYTWJ(&(W[TWVL * 16]),VSUB(TaE, TaP));
TaR = BYTWJ(&(W[TWVL * 4]),VADD(TaE, TaP));
ST(&(x[WS(vs, 9) + WS(rs, 11)]),TaQ,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 11)]),TaR,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V T72, T73, T6Q, T71;
T6Q = VSUB(T6K, T6P);
T71 = VBYI(VSUB(T6V, T70));
T72 = BYTWJ(&(W[TWVL * 16]),VSUB(T6Q, T71));
T73 = BYTWJ(&(W[TWVL * 4]),VADD(T6Q, T71));
ST(&(x[WS(vs, 9) + WS(rs, 7)]),T72,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 7)]),T73,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V T1k, T1l, T18, T1j;
T18 = VSUB(T12, T17);
T1j = VBYI(VSUB(T1d, T1i));
T1k = BYTWJ(&(W[TWVL * 16]),VSUB(T18, T1j));
T1l = BYTWJ(&(W[TWVL * 4]),VADD(T18, T1j));
ST(&(x[WS(vs, 9) + WS(rs, 1)]),T1k,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 1)]),T1l,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
}
{
V T9T, T9U, T9H, T9S;
T9H = VSUB(T9B, T9G);
T9S = VBYI(VSUB(T9M, T9R));
T9T = BYTWJ(&(W[TWVL * 16]),VSUB(T9H, T9S));
T9U = BYTWJ(&(W[TWVL * 4]),VADD(T9H, T9S));
ST(&(x[WS(vs, 9) + WS(rs, 10)]),T9T,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 10)]),T9U,ms,&(x[WS(vs, 3)]));
}
{
V T2h, T2i, T25, T2g;
T25 = VSUB(T1Z, T24);
T2g = VBYI(VSUB(T2a, T2f));
T2h = BYTWJ(&(W[TWVL * 16]),VSUB(T25, T2g));
T2i = BYTWJ(&(W[TWVL * 4]),VADD(T25, T2g));
ST(&(x[WS(vs, 9) + WS(rs, 2)]),T2h,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 2)]),T2i,ms,&(x[WS(vs, 3)]));
}
{
V T7Z, T80, T7N, T7Y;
T7N = VSUB(T7H, T7M);
T7Y = VBYI(VSUB(T7S, T7X));
T7Z = BYTWJ(&(W[TWVL * 16]),VSUB(T7N, T7Y));
T80 = BYTWJ(&(W[TWVL * 4]),VADD(T7N, T7Y));
ST(&(x[WS(vs, 9) + WS(rs, 8)]),T7Z,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 8)]),T80,ms,&(x[WS(vs, 3)]));
}
{
V T3e, T3f, T32, T3d;
T32 = VSUB(T2W, T31);
T3d = VBYI(VSUB(T37, T3c));
T3e = BYTWJ(&(W[TWVL * 16]),VSUB(T32, T3d));
T3f = BYTWJ(&(W[TWVL * 4]),VADD(T32, T3d));
ST(&(x[WS(vs, 9) + WS(rs, 3)]),T3e,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 3)]),T3f,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V T4b, T4c, T3Z, T4a;
T3Z = VSUB(T3T, T3Y);
T4a = VBYI(VSUB(T44, T49));
T4b = BYTWJ(&(W[TWVL * 16]),VSUB(T3Z, T4a));
T4c = BYTWJ(&(W[TWVL * 4]),VADD(T3Z, T4a));
ST(&(x[WS(vs, 9) + WS(rs, 4)]),T4b,ms,&(x[WS(vs, 9)]));
ST(&(x[WS(vs, 3) + WS(rs, 4)]),T4c,ms,&(x[WS(vs, 3)]));
}
{
V T8W, T8X, T8K, T8V;
T8K = VSUB(T8E, T8J);
T8V = VBYI(VSUB(T8P, T8U));
T8W = BYTWJ(&(W[TWVL * 16]),VSUB(T8K, T8V));
T8X = BYTWJ(&(W[TWVL * 4]),VADD(T8K, T8V));
ST(&(x[WS(vs, 9) + WS(rs, 9)]),T8W,ms,&(x[WS(vs, 9) + WS(rs, 1)]));
ST(&(x[WS(vs, 3) + WS(rs, 9)]),T8X,ms,&(x[WS(vs, 3) + WS(rs, 1)]));
}
{
V TG, TH, Ty, TF;
Ty = VSUB(Tu, Tx);
TF = VBYI(VADD(TB, TE));
TG = BYTWJ(&(W[TWVL * 8]),VSUB(Ty, TF));
TH = BYTWJ(&(W[TWVL * 12]),VADD(TF, Ty));
ST(&(x[WS(vs, 5)]),TG,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7)]),TH,ms,&(x[WS(vs, 7)]));
}
{
V T6o, T6p, T6g, T6n;
T6g = VSUB(T6c, T6f);
T6n = VBYI(VADD(T6j, T6m));
T6o = BYTWJ(&(W[TWVL * 8]),VSUB(T6g, T6n));
T6p = BYTWJ(&(W[TWVL * 12]),VADD(T6n, T6g));
ST(&(x[WS(vs, 5) + WS(rs, 6)]),T6o,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 6)]),T6p,ms,&(x[WS(vs, 7)]));
}
{
V T3x, T3y, T3p, T3w;
T3p = VSUB(T3l, T3o);
T3w = VBYI(VADD(T3s, T3v));
T3x = BYTWJ(&(W[TWVL * 8]),VSUB(T3p, T3w));
T3y = BYTWJ(&(W[TWVL * 12]),VADD(T3w, T3p));
ST(&(x[WS(vs, 5) + WS(rs, 3)]),T3x,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 3)]),T3y,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T9f, T9g, T97, T9e;
T97 = VSUB(T93, T96);
T9e = VBYI(VADD(T9a, T9d));
T9f = BYTWJ(&(W[TWVL * 8]),VSUB(T97, T9e));
T9g = BYTWJ(&(W[TWVL * 12]),VADD(T9e, T97));
ST(&(x[WS(vs, 5) + WS(rs, 9)]),T9f,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 9)]),T9g,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T7l, T7m, T7d, T7k;
T7d = VSUB(T79, T7c);
T7k = VBYI(VADD(T7g, T7j));
T7l = BYTWJ(&(W[TWVL * 8]),VSUB(T7d, T7k));
T7m = BYTWJ(&(W[TWVL * 12]),VADD(T7k, T7d));
ST(&(x[WS(vs, 5) + WS(rs, 7)]),T7l,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 7)]),T7m,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V Tac, Tad, Ta4, Tab;
Ta4 = VSUB(Ta0, Ta3);
Tab = VBYI(VADD(Ta7, Taa));
Tac = BYTWJ(&(W[TWVL * 8]),VSUB(Ta4, Tab));
Tad = BYTWJ(&(W[TWVL * 12]),VADD(Tab, Ta4));
ST(&(x[WS(vs, 5) + WS(rs, 10)]),Tac,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 10)]),Tad,ms,&(x[WS(vs, 7)]));
}
{
V Tb9, Tba, Tb1, Tb8;
Tb1 = VSUB(TaX, Tb0);
Tb8 = VBYI(VADD(Tb4, Tb7));
Tb9 = BYTWJ(&(W[TWVL * 8]),VSUB(Tb1, Tb8));
Tba = BYTWJ(&(W[TWVL * 12]),VADD(Tb8, Tb1));
ST(&(x[WS(vs, 5) + WS(rs, 11)]),Tb9,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 11)]),Tba,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T8i, T8j, T8a, T8h;
T8a = VSUB(T86, T89);
T8h = VBYI(VADD(T8d, T8g));
T8i = BYTWJ(&(W[TWVL * 8]),VSUB(T8a, T8h));
T8j = BYTWJ(&(W[TWVL * 12]),VADD(T8h, T8a));
ST(&(x[WS(vs, 5) + WS(rs, 8)]),T8i,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 8)]),T8j,ms,&(x[WS(vs, 7)]));
}
{
V T2A, T2B, T2s, T2z;
T2s = VSUB(T2o, T2r);
T2z = VBYI(VADD(T2v, T2y));
T2A = BYTWJ(&(W[TWVL * 8]),VSUB(T2s, T2z));
T2B = BYTWJ(&(W[TWVL * 12]),VADD(T2z, T2s));
ST(&(x[WS(vs, 5) + WS(rs, 2)]),T2A,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 2)]),T2B,ms,&(x[WS(vs, 7)]));
}
{
V T4u, T4v, T4m, T4t;
T4m = VSUB(T4i, T4l);
T4t = VBYI(VADD(T4p, T4s));
T4u = BYTWJ(&(W[TWVL * 8]),VSUB(T4m, T4t));
T4v = BYTWJ(&(W[TWVL * 12]),VADD(T4t, T4m));
ST(&(x[WS(vs, 5) + WS(rs, 4)]),T4u,ms,&(x[WS(vs, 5)]));
ST(&(x[WS(vs, 7) + WS(rs, 4)]),T4v,ms,&(x[WS(vs, 7)]));
}
{
V T5r, T5s, T5j, T5q;
T5j = VSUB(T5f, T5i);
T5q = VBYI(VADD(T5m, T5p));
T5r = BYTWJ(&(W[TWVL * 8]),VSUB(T5j, T5q));
T5s = BYTWJ(&(W[TWVL * 12]),VADD(T5q, T5j));
ST(&(x[WS(vs, 5) + WS(rs, 5)]),T5r,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 5)]),T5s,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V T1D, T1E, T1v, T1C;
T1v = VSUB(T1r, T1u);
T1C = VBYI(VADD(T1y, T1B));
T1D = BYTWJ(&(W[TWVL * 8]),VSUB(T1v, T1C));
T1E = BYTWJ(&(W[TWVL * 12]),VADD(T1C, T1v));
ST(&(x[WS(vs, 5) + WS(rs, 1)]),T1D,ms,&(x[WS(vs, 5) + WS(rs, 1)]));
ST(&(x[WS(vs, 7) + WS(rs, 1)]),T1E,ms,&(x[WS(vs, 7) + WS(rs, 1)]));
}
{
V TK, TL, TI, TJ;
TI = VBYI(VSUB(TB, TE));
TJ = VADD(Tu, Tx);
TK = BYTWJ(&(W[0]),VADD(TI, TJ));
TL = BYTWJ(&(W[TWVL * 20]),VSUB(TJ, TI));
ST(&(x[WS(vs, 1)]),TK,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11)]),TL,ms,&(x[WS(vs, 11)]));
}
{
V T2E, T2F, T2C, T2D;
T2C = VBYI(VSUB(T2v, T2y));
T2D = VADD(T2o, T2r);
T2E = BYTWJ(&(W[0]),VADD(T2C, T2D));
T2F = BYTWJ(&(W[TWVL * 20]),VSUB(T2D, T2C));
ST(&(x[WS(vs, 1) + WS(rs, 2)]),T2E,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 2)]),T2F,ms,&(x[WS(vs, 11)]));
}
{
V T1H, T1I, T1F, T1G;
T1F = VBYI(VSUB(T1y, T1B));
T1G = VADD(T1r, T1u);
T1H = BYTWJ(&(W[0]),VADD(T1F, T1G));
T1I = BYTWJ(&(W[TWVL * 20]),VSUB(T1G, T1F));
ST(&(x[WS(vs, 1) + WS(rs, 1)]),T1H,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 1)]),T1I,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T3B, T3C, T3z, T3A;
T3z = VBYI(VSUB(T3s, T3v));
T3A = VADD(T3l, T3o);
T3B = BYTWJ(&(W[0]),VADD(T3z, T3A));
T3C = BYTWJ(&(W[TWVL * 20]),VSUB(T3A, T3z));
ST(&(x[WS(vs, 1) + WS(rs, 3)]),T3B,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 3)]),T3C,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T6s, T6t, T6q, T6r;
T6q = VBYI(VSUB(T6j, T6m));
T6r = VADD(T6c, T6f);
T6s = BYTWJ(&(W[0]),VADD(T6q, T6r));
T6t = BYTWJ(&(W[TWVL * 20]),VSUB(T6r, T6q));
ST(&(x[WS(vs, 1) + WS(rs, 6)]),T6s,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 6)]),T6t,ms,&(x[WS(vs, 11)]));
}
{
V Tbd, Tbe, Tbb, Tbc;
Tbb = VBYI(VSUB(Tb4, Tb7));
Tbc = VADD(TaX, Tb0);
Tbd = BYTWJ(&(W[0]),VADD(Tbb, Tbc));
Tbe = BYTWJ(&(W[TWVL * 20]),VSUB(Tbc, Tbb));
ST(&(x[WS(vs, 1) + WS(rs, 11)]),Tbd,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 11)]),Tbe,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T5v, T5w, T5t, T5u;
T5t = VBYI(VSUB(T5m, T5p));
T5u = VADD(T5f, T5i);
T5v = BYTWJ(&(W[0]),VADD(T5t, T5u));
T5w = BYTWJ(&(W[TWVL * 20]),VSUB(T5u, T5t));
ST(&(x[WS(vs, 1) + WS(rs, 5)]),T5v,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 5)]),T5w,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T9j, T9k, T9h, T9i;
T9h = VBYI(VSUB(T9a, T9d));
T9i = VADD(T93, T96);
T9j = BYTWJ(&(W[0]),VADD(T9h, T9i));
T9k = BYTWJ(&(W[TWVL * 20]),VSUB(T9i, T9h));
ST(&(x[WS(vs, 1) + WS(rs, 9)]),T9j,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 9)]),T9k,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V T8m, T8n, T8k, T8l;
T8k = VBYI(VSUB(T8d, T8g));
T8l = VADD(T86, T89);
T8m = BYTWJ(&(W[0]),VADD(T8k, T8l));
T8n = BYTWJ(&(W[TWVL * 20]),VSUB(T8l, T8k));
ST(&(x[WS(vs, 1) + WS(rs, 8)]),T8m,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 8)]),T8n,ms,&(x[WS(vs, 11)]));
}
{
V T4y, T4z, T4w, T4x;
T4w = VBYI(VSUB(T4p, T4s));
T4x = VADD(T4i, T4l);
T4y = BYTWJ(&(W[0]),VADD(T4w, T4x));
T4z = BYTWJ(&(W[TWVL * 20]),VSUB(T4x, T4w));
ST(&(x[WS(vs, 1) + WS(rs, 4)]),T4y,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 4)]),T4z,ms,&(x[WS(vs, 11)]));
}
{
V T7p, T7q, T7n, T7o;
T7n = VBYI(VSUB(T7g, T7j));
T7o = VADD(T79, T7c);
T7p = BYTWJ(&(W[0]),VADD(T7n, T7o));
T7q = BYTWJ(&(W[TWVL * 20]),VSUB(T7o, T7n));
ST(&(x[WS(vs, 1) + WS(rs, 7)]),T7p,ms,&(x[WS(vs, 1) + WS(rs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 7)]),T7q,ms,&(x[WS(vs, 11) + WS(rs, 1)]));
}
{
V Tag, Tah, Tae, Taf;
Tae = VBYI(VSUB(Ta7, Taa));
Taf = VADD(Ta0, Ta3);
Tag = BYTWJ(&(W[0]),VADD(Tae, Taf));
Tah = BYTWJ(&(W[TWVL * 20]),VSUB(Taf, Tae));
ST(&(x[WS(vs, 1) + WS(rs, 10)]),Tag,ms,&(x[WS(vs, 1)]));
ST(&(x[WS(vs, 11) + WS(rs, 10)]),Tah,ms,&(x[WS(vs, 11)]));
}
{
V T5D, T5E, T5z, T5C;
T5z = VSUB(T5x, T5y);
T5C = VBYI(VMUL(LDK(KP866025403), VSUB(T5A, T5B)));
T5D = BYTWJ(&(W[TWVL * 18]),VSUB(T5z, T5C));
T5E = BYTWJ(&(W[TWVL * 2]),VADD(T5z, T5C));
ST(&(x[WS(vs, 10) + WS(rs, 5)]),T5D,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
ST(&(x[WS(vs, 2) + WS(rs, 5)]),T5E,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
}
{
V TS, TT, TO, TR;
TO = VSUB(TM, TN);
TR = VBYI(VMUL(LDK(KP866025403), VSUB(TP, TQ)));
TS = BYTWJ(&(W[TWVL * 18]),VSUB(TO, TR));
TT = BYTWJ(&(W[TWVL * 2]),VADD(TO, TR));
ST(&(x[WS(vs, 10)]),TS,ms,&(x[WS(vs, 10)]));
ST(&(x[WS(vs, 2)]),TT,ms,&(x[WS(vs, 2)]));
}
{
V T6A, T6B, T6w, T6z;
T6w = VSUB(T6u, T6v);
T6z = VBYI(VMUL(LDK(KP866025403), VSUB(T6x, T6y)));
T6A = BYTWJ(&(W[TWVL * 18]),VSUB(T6w, T6z));
T6B = BYTWJ(&(W[TWVL * 2]),VADD(T6w, T6z));
ST(&(x[WS(vs, 10) + WS(rs, 6)]),T6A,ms,&(x[WS(vs, 10)]));
ST(&(x[WS(vs, 2) + WS(rs, 6)]),T6B,ms,&(x[WS(vs, 2)]));
}
{
V Tbl, Tbm, Tbh, Tbk;
Tbh = VSUB(Tbf, Tbg);
Tbk = VBYI(VMUL(LDK(KP866025403), VSUB(Tbi, Tbj)));
Tbl = BYTWJ(&(W[TWVL * 18]),VSUB(Tbh, Tbk));
Tbm = BYTWJ(&(W[TWVL * 2]),VADD(Tbh, Tbk));
ST(&(x[WS(vs, 10) + WS(rs, 11)]),Tbl,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
ST(&(x[WS(vs, 2) + WS(rs, 11)]),Tbm,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
}
{
V T7x, T7y, T7t, T7w;
T7t = VSUB(T7r, T7s);
T7w = VBYI(VMUL(LDK(KP866025403), VSUB(T7u, T7v)));
T7x = BYTWJ(&(W[TWVL * 18]),VSUB(T7t, T7w));
T7y = BYTWJ(&(W[TWVL * 2]),VADD(T7t, T7w));
ST(&(x[WS(vs, 10) + WS(rs, 7)]),T7x,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
ST(&(x[WS(vs, 2) + WS(rs, 7)]),T7y,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
}
{
V T1P, T1Q, T1L, T1O;
T1L = VSUB(T1J, T1K);
T1O = VBYI(VMUL(LDK(KP866025403), VSUB(T1M, T1N)));
T1P = BYTWJ(&(W[TWVL * 18]),VSUB(T1L, T1O));
T1Q = BYTWJ(&(W[TWVL * 2]),VADD(T1L, T1O));
ST(&(x[WS(vs, 10) + WS(rs, 1)]),T1P,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
ST(&(x[WS(vs, 2) + WS(rs, 1)]),T1Q,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
}
{
V Tao, Tap, Tak, Tan;
Tak = VSUB(Tai, Taj);
Tan = VBYI(VMUL(LDK(KP866025403), VSUB(Tal, Tam)));
Tao = BYTWJ(&(W[TWVL * 18]),VSUB(Tak, Tan));
Tap = BYTWJ(&(W[TWVL * 2]),VADD(Tak, Tan));
ST(&(x[WS(vs, 10) + WS(rs, 10)]),Tao,ms,&(x[WS(vs, 10)]));
ST(&(x[WS(vs, 2) + WS(rs, 10)]),Tap,ms,&(x[WS(vs, 2)]));
}
{
V T2M, T2N, T2I, T2L;
T2I = VSUB(T2G, T2H);
T2L = VBYI(VMUL(LDK(KP866025403), VSUB(T2J, T2K)));
T2M = BYTWJ(&(W[TWVL * 18]),VSUB(T2I, T2L));
T2N = BYTWJ(&(W[TWVL * 2]),VADD(T2I, T2L));
ST(&(x[WS(vs, 10) + WS(rs, 2)]),T2M,ms,&(x[WS(vs, 10)]));
ST(&(x[WS(vs, 2) + WS(rs, 2)]),T2N,ms,&(x[WS(vs, 2)]));
}
{
V T8u, T8v, T8q, T8t;
T8q = VSUB(T8o, T8p);
T8t = VBYI(VMUL(LDK(KP866025403), VSUB(T8r, T8s)));
T8u = BYTWJ(&(W[TWVL * 18]),VSUB(T8q, T8t));
T8v = BYTWJ(&(W[TWVL * 2]),VADD(T8q, T8t));
ST(&(x[WS(vs, 10) + WS(rs, 8)]),T8u,ms,&(x[WS(vs, 10)]));
ST(&(x[WS(vs, 2) + WS(rs, 8)]),T8v,ms,&(x[WS(vs, 2)]));
}
{
V T3J, T3K, T3F, T3I;
T3F = VSUB(T3D, T3E);
T3I = VBYI(VMUL(LDK(KP866025403), VSUB(T3G, T3H)));
T3J = BYTWJ(&(W[TWVL * 18]),VSUB(T3F, T3I));
T3K = BYTWJ(&(W[TWVL * 2]),VADD(T3F, T3I));
ST(&(x[WS(vs, 10) + WS(rs, 3)]),T3J,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
ST(&(x[WS(vs, 2) + WS(rs, 3)]),T3K,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
}
{
V T4G, T4H, T4C, T4F;
T4C = VSUB(T4A, T4B);
T4F = VBYI(VMUL(LDK(KP866025403), VSUB(T4D, T4E)));
T4G = BYTWJ(&(W[TWVL * 18]),VSUB(T4C, T4F));
T4H = BYTWJ(&(W[TWVL * 2]),VADD(T4C, T4F));
ST(&(x[WS(vs, 10) + WS(rs, 4)]),T4G,ms,&(x[WS(vs, 10)]));
ST(&(x[WS(vs, 2) + WS(rs, 4)]),T4H,ms,&(x[WS(vs, 2)]));
}
{
V T9r, T9s, T9n, T9q;
T9n = VSUB(T9l, T9m);
T9q = VBYI(VMUL(LDK(KP866025403), VSUB(T9o, T9p)));
T9r = BYTWJ(&(W[TWVL * 18]),VSUB(T9n, T9q));
T9s = BYTWJ(&(W[TWVL * 2]),VADD(T9n, T9q));
ST(&(x[WS(vs, 10) + WS(rs, 9)]),T9r,ms,&(x[WS(vs, 10) + WS(rs, 1)]));
ST(&(x[WS(vs, 2) + WS(rs, 9)]),T9s,ms,&(x[WS(vs, 2) + WS(rs, 1)]));
}
{
V TW, TX, TU, TV;
TU = VADD(TM, TN);
TV = VBYI(VMUL(LDK(KP866025403), VADD(TQ, TP)));
TW = BYTWJ(&(W[TWVL * 14]),VSUB(TU, TV));
TX = BYTWJ(&(W[TWVL * 6]),VADD(TU, TV));
ST(&(x[WS(vs, 8)]),TW,ms,&(x[WS(vs, 8)]));
ST(&(x[WS(vs, 4)]),TX,ms,&(x[WS(vs, 4)]));
}
{
V T6E, T6F, T6C, T6D;
T6C = VADD(T6u, T6v);
T6D = VBYI(VMUL(LDK(KP866025403), VADD(T6y, T6x)));
T6E = BYTWJ(&(W[TWVL * 14]),VSUB(T6C, T6D));
T6F = BYTWJ(&(W[TWVL * 6]),VADD(T6C, T6D));
ST(&(x[WS(vs, 8) + WS(rs, 6)]),T6E,ms,&(x[WS(vs, 8)]));
ST(&(x[WS(vs, 4) + WS(rs, 6)]),T6F,ms,&(x[WS(vs, 4)]));
}
{
V T3N, T3O, T3L, T3M;
T3L = VADD(T3D, T3E);
T3M = VBYI(VMUL(LDK(KP866025403), VADD(T3H, T3G)));
T3N = BYTWJ(&(W[TWVL * 14]),VSUB(T3L, T3M));
T3O = BYTWJ(&(W[TWVL * 6]),VADD(T3L, T3M));
ST(&(x[WS(vs, 8) + WS(rs, 3)]),T3N,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
ST(&(x[WS(vs, 4) + WS(rs, 3)]),T3O,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
{
V T9v, T9w, T9t, T9u;
T9t = VADD(T9l, T9m);
T9u = VBYI(VMUL(LDK(KP866025403), VADD(T9p, T9o)));
T9v = BYTWJ(&(W[TWVL * 14]),VSUB(T9t, T9u));
T9w = BYTWJ(&(W[TWVL * 6]),VADD(T9t, T9u));
ST(&(x[WS(vs, 8) + WS(rs, 9)]),T9v,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
ST(&(x[WS(vs, 4) + WS(rs, 9)]),T9w,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
{
V T7B, T7C, T7z, T7A;
T7z = VADD(T7r, T7s);
T7A = VBYI(VMUL(LDK(KP866025403), VADD(T7v, T7u)));
T7B = BYTWJ(&(W[TWVL * 14]),VSUB(T7z, T7A));
T7C = BYTWJ(&(W[TWVL * 6]),VADD(T7z, T7A));
ST(&(x[WS(vs, 8) + WS(rs, 7)]),T7B,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
ST(&(x[WS(vs, 4) + WS(rs, 7)]),T7C,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
{
V Tas, Tat, Taq, Tar;
Taq = VADD(Tai, Taj);
Tar = VBYI(VMUL(LDK(KP866025403), VADD(Tam, Tal)));
Tas = BYTWJ(&(W[TWVL * 14]),VSUB(Taq, Tar));
Tat = BYTWJ(&(W[TWVL * 6]),VADD(Taq, Tar));
ST(&(x[WS(vs, 8) + WS(rs, 10)]),Tas,ms,&(x[WS(vs, 8)]));
ST(&(x[WS(vs, 4) + WS(rs, 10)]),Tat,ms,&(x[WS(vs, 4)]));
}
{
V Tbp, Tbq, Tbn, Tbo;
Tbn = VADD(Tbf, Tbg);
Tbo = VBYI(VMUL(LDK(KP866025403), VADD(Tbj, Tbi)));
Tbp = BYTWJ(&(W[TWVL * 14]),VSUB(Tbn, Tbo));
Tbq = BYTWJ(&(W[TWVL * 6]),VADD(Tbn, Tbo));
ST(&(x[WS(vs, 8) + WS(rs, 11)]),Tbp,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
ST(&(x[WS(vs, 4) + WS(rs, 11)]),Tbq,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
{
V T8y, T8z, T8w, T8x;
T8w = VADD(T8o, T8p);
T8x = VBYI(VMUL(LDK(KP866025403), VADD(T8s, T8r)));
T8y = BYTWJ(&(W[TWVL * 14]),VSUB(T8w, T8x));
T8z = BYTWJ(&(W[TWVL * 6]),VADD(T8w, T8x));
ST(&(x[WS(vs, 8) + WS(rs, 8)]),T8y,ms,&(x[WS(vs, 8)]));
ST(&(x[WS(vs, 4) + WS(rs, 8)]),T8z,ms,&(x[WS(vs, 4)]));
}
{
V T2Q, T2R, T2O, T2P;
T2O = VADD(T2G, T2H);
T2P = VBYI(VMUL(LDK(KP866025403), VADD(T2K, T2J)));
T2Q = BYTWJ(&(W[TWVL * 14]),VSUB(T2O, T2P));
T2R = BYTWJ(&(W[TWVL * 6]),VADD(T2O, T2P));
ST(&(x[WS(vs, 8) + WS(rs, 2)]),T2Q,ms,&(x[WS(vs, 8)]));
ST(&(x[WS(vs, 4) + WS(rs, 2)]),T2R,ms,&(x[WS(vs, 4)]));
}
{
V T4K, T4L, T4I, T4J;
T4I = VADD(T4A, T4B);
T4J = VBYI(VMUL(LDK(KP866025403), VADD(T4E, T4D)));
T4K = BYTWJ(&(W[TWVL * 14]),VSUB(T4I, T4J));
T4L = BYTWJ(&(W[TWVL * 6]),VADD(T4I, T4J));
ST(&(x[WS(vs, 8) + WS(rs, 4)]),T4K,ms,&(x[WS(vs, 8)]));
ST(&(x[WS(vs, 4) + WS(rs, 4)]),T4L,ms,&(x[WS(vs, 4)]));
}
{
V T5H, T5I, T5F, T5G;
T5F = VADD(T5x, T5y);
T5G = VBYI(VMUL(LDK(KP866025403), VADD(T5B, T5A)));
T5H = BYTWJ(&(W[TWVL * 14]),VSUB(T5F, T5G));
T5I = BYTWJ(&(W[TWVL * 6]),VADD(T5F, T5G));
ST(&(x[WS(vs, 8) + WS(rs, 5)]),T5H,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
ST(&(x[WS(vs, 4) + WS(rs, 5)]),T5I,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
{
V T1T, T1U, T1R, T1S;
T1R = VADD(T1J, T1K);
T1S = VBYI(VMUL(LDK(KP866025403), VADD(T1N, T1M)));
T1T = BYTWJ(&(W[TWVL * 14]),VSUB(T1R, T1S));
T1U = BYTWJ(&(W[TWVL * 6]),VADD(T1R, T1S));
ST(&(x[WS(vs, 8) + WS(rs, 1)]),T1T,ms,&(x[WS(vs, 8) + WS(rs, 1)]));
ST(&(x[WS(vs, 4) + WS(rs, 1)]),T1U,ms,&(x[WS(vs, 4) + WS(rs, 1)]));
}
}
}
VLEAVE();}


static const tw_instr twinstr[] = {
VTW(0,1),
VTW(0,2),
VTW(0,3),
VTW(0,4),
VTW(0,5),
VTW(0,6),
VTW(0,7),
VTW(0,8),
VTW(0,9),
VTW(0,10),
VTW(0,11),
{TW_NEXT, VL, 0}};

static const ct_desc desc = {12, XSIMD_STRING("q1fv_12"), twinstr, &GENUS, { 660, 312, 48, 0 }, 0, 0, 0};

void XSIMD(codelet_q1fv_12)(planner *p)
{
X(kdft_difsq_register)(p, q1fv_12, &desc);
}
#endif
