/*
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/* This file was automatically generated --- DO NOT EDIT */
/* Generated on Fri Feb  7 13:12:35 IST 2020 */

#include "dft/codelet-dft.h"



#if defined(ARCH_PREFERS_FMA) || defined(ISA_EXTENSION_PREFERS_FMA)

/* Generated by: ../../../genfft/gen_twiddle_c.native -fma -simd -compact -variables 4 -pipeline-latency 8 -twiddle-log3 -precompute-twiddles -no-generate-bytw -n 64 -name t3fv_64 -include dft/simd/t3f.h */

/*
 * This function contains 577 FP additions, 500 FP multiplications,
 * (or, 319 additions, 242 multiplications, 258 fused multiply/add),
 * 170 stack variables, 15 constants, and 128 memory accesses
 */
#include "dft/simd/t3f.h"

static void t3fv_64(R * ri, R * ii, const R * W, stride rs, INT mb, INT me, INT ms)
{
DVK(KP773010453, +0.773010453362736960810906609758469800971041293);
DVK(KP995184726, +0.995184726672196886244836953109479921575474869);
DVK(KP820678790, +0.820678790828660330972281985331011598767386482);
DVK(KP098491403, +0.098491403357164253077197521291327432293052451);
DVK(KP956940335, +0.956940335732208864935797886980269969482849206);
DVK(KP881921264, +0.881921264348355029712756863660388349508442621);
DVK(KP303346683, +0.303346683607342391675883946941299872384187453);
DVK(KP534511135, +0.534511135950791641089685961295362908582039528);
DVK(KP831469612, +0.831469612302545237078788377617905756738560812);
DVK(KP668178637, +0.668178637919298919997757686523080761552472251);
DVK(KP980785280, +0.980785280403230449126182236134239036973933731);
DVK(KP198912367, +0.198912367379658006911597622644676228597850501);
DVK(KP923879532, +0.923879532511286756128183189396788286822416626);
DVK(KP414213562, +0.414213562373095048801688724209698078569671875);
DVK(KP707106781, +0.707106781186547524400844362104849039284835938);
{
INT m;
R * x;
x = ri;
for (m = mb, W = W + (mb * ((TWVL/VL) * 10)); m < me; m = m + VL, x = x + (VL * ms), W = W + (TWVL * 10), MAKE_VOLATILE_STRIDE(64, rs)){
V T2, T3, T4, Tc, T5, T7, T6, T1b, T1e, Td, Th, TN, T15, Tv, T12;
V T8, T3F, T1n, T44, Tr, TH, TY, T3Y, T3L, T3c, T2t, T2f, T1w, T2Z, T2P;
V T22, T1S, Te, T1D, T1M, Ti, Tw, T1f, T1A, TO, Tj, Tk, Tz, T1g, T3V;
V T3i, T16, T3C, T3v, TP, TE, T3n, T35, T2M, T2l, T1k, T28, T2q, T1t, T1E;
V T2z, T2I, T1J;
T2 = LDW(&(W[0]));
T3 = LDW(&(W[TWVL * 2]));
T4 = VZMUL(T2, T3);
Tc = VZMULJ(T2, T3);
T5 = LDW(&(W[TWVL * 4]));
T7 = LDW(&(W[TWVL * 6]));
T6 = VZMULJ(T4, T5);
T1b = VZMUL(T2, T5);
T1e = VZMULJ(T3, T5);
Td = VZMUL(Tc, T5);
Th = VZMUL(T3, T5);
TN = VZMULJ(T2, T5);
T15 = VZMUL(T4, T5);
Tv = VZMULJ(Tc, T5);
T12 = VZMULJ(T5, T7);
T8 = VZMUL(T6, T7);
T3F = VZMULJ(T4, T7);
T1n = VZMULJ(T2, T7);
T44 = VZMUL(T15, T7);
Tr = VZMUL(T5, T7);
TH = VZMUL(T2, T7);
TY = VZMUL(Tv, T7);
T3Y = VZMULJ(T3, T7);
T3L = VZMUL(Th, T7);
T3c = VZMUL(TN, T7);
T2t = VZMUL(Tc, T7);
T2f = VZMUL(T1b, T7);
T1w = VZMUL(T3, T7);
T2Z = VZMUL(T4, T7);
T2P = VZMULJ(Tc, T7);
T22 = VZMUL(T1e, T7);
T1S = VZMUL(Td, T7);
Te = VZMULJ(Td, T7);
T1D = VZMULJ(T1b, T7);
T1M = VZMULJ(T6, T7);
Ti = VZMULJ(Th, T7);
Tw = VZMULJ(Tv, T7);
T1f = VZMULJ(T1e, T7);
T1A = VZMULJ(T15, T7);
TO = VZMULJ(TN, T7);
Tj = LDW(&(W[TWVL * 8]));
Tk = VZMULJ(Ti, Tj);
Tz = VZMULJ(Td, Tj);
T1g = VZMULJ(T1f, Tj);
T3V = VZMULJ(Tv, Tj);
T3i = VZMULJ(Th, Tj);
T16 = VZMULJ(T15, Tj);
T3C = VZMULJ(TN, Tj);
T3v = VZMULJ(Tw, Tj);
TP = VZMULJ(TO, Tj);
TE = VZMULJ(T3, Tj);
T3n = VZMULJ(T4, Tj);
T35 = VZMULJ(Te, Tj);
T2M = VZMULJ(T1e, Tj);
T2l = VZMULJ(T1b, Tj);
T1k = VZMULJ(T6, Tj);
T28 = VZMULJ(T1A, Tj);
T2q = VZMULJ(Tc, Tj);
T1t = VZMULJ(T2, Tj);
T1E = VZMULJ(T1D, Tj);
T2z = VZMULJ(T12, Tj);
T2I = VZMULJ(T1M, Tj);
T1J = VZMULJ(T5, Tj);
{
V To, T4V, T7m, T8C, T48, T4W, T69, T8b, T2c, T2T, T54, T5G, T6G, T8m, T6R;
V T8p, T39, T3P, T5b, T5J, T71, T8t, T7c, T8w, T5i, T5j, T5D, T6y, T8h, T1X;
V T4b, T6v, T8i, T5l, T5m, T5C, T6p, T8e, T1s, T4c, T6m, T8f, T4Y, T4Z, TU;
V T49, T6g, T8D, T7p, T8c, T2E, T2U, T6U, T8n, T57, T5H, T6N, T8q, T3A, T3Q;
V T7f, T8u, T5e, T5K, T78, T8x;
{
V T1, Ta, Tm, Tg, T43, T46, T66, T3X, T40, T67, T9, Tl, Tf;
T1 = LD(&(x[0]), ms, &(x[0]));
T9 = LD(&(x[WS(rs, 32)]), ms, &(x[0]));
Ta = VZMULJ(T8, T9);
Tl = LD(&(x[WS(rs, 48)]), ms, &(x[0]));
Tm = VZMULJ(Tk, Tl);
Tf = LD(&(x[WS(rs, 16)]), ms, &(x[0]));
Tg = VZMULJ(Te, Tf);
{
V T42, T45, T3W, T3Z;
T42 = LD(&(x[WS(rs, 8)]), ms, &(x[0]));
T43 = VZMULJ(TN, T42);
T45 = LD(&(x[WS(rs, 40)]), ms, &(x[0]));
T46 = VZMULJ(T44, T45);
T66 = VSUB(T43, T46);
T3W = LD(&(x[WS(rs, 56)]), ms, &(x[0]));
T3X = VZMULJ(T3V, T3W);
T3Z = LD(&(x[WS(rs, 24)]), ms, &(x[0]));
T40 = VZMULJ(T3Y, T3Z);
T67 = VSUB(T3X, T40);
}
{
V Tb, Tn, T7k, T7l;
Tb = VADD(T1, Ta);
Tn = VADD(Tg, Tm);
To = VSUB(Tb, Tn);
T4V = VADD(Tb, Tn);
T7k = VSUB(Tg, Tm);
T7l = VSUB(T67, T66);
T7m = VFNMS(LDK(KP707106781), T7l, T7k);
T8C = VFMA(LDK(KP707106781), T7l, T7k);
}
{
V T41, T47, T65, T68;
T41 = VADD(T3X, T40);
T47 = VADD(T43, T46);
T48 = VSUB(T41, T47);
T4W = VADD(T47, T41);
T65 = VSUB(T1, Ta);
T68 = VADD(T66, T67);
T69 = VFMA(LDK(KP707106781), T68, T65);
T8b = VFNMS(LDK(KP707106781), T68, T65);
}
}
{
V T21, T24, T25, T27, T2a, T2b, T2L, T6D, T2S, T6E, T52, T53;
{
V T20, T23, T26, T29;
T20 = LD(&(x[WS(rs, 1)]), ms, &(x[WS(rs, 1)]));
T21 = VZMULJ(T2, T20);
T23 = LD(&(x[WS(rs, 33)]), ms, &(x[WS(rs, 1)]));
T24 = VZMULJ(T22, T23);
T25 = VADD(T21, T24);
T26 = LD(&(x[WS(rs, 17)]), ms, &(x[WS(rs, 1)]));
T27 = VZMULJ(T1D, T26);
T29 = LD(&(x[WS(rs, 49)]), ms, &(x[WS(rs, 1)]));
T2a = VZMULJ(T28, T29);
T2b = VADD(T27, T2a);
}
{
V T2H, T2K, T2G, T2J;
T2G = LD(&(x[WS(rs, 9)]), ms, &(x[WS(rs, 1)]));
T2H = VZMULJ(T5, T2G);
T2J = LD(&(x[WS(rs, 41)]), ms, &(x[WS(rs, 1)]));
T2K = VZMULJ(T2I, T2J);
T2L = VADD(T2H, T2K);
T6D = VSUB(T2H, T2K);
}
{
V T2O, T2R, T2N, T2Q;
T2N = LD(&(x[WS(rs, 57)]), ms, &(x[WS(rs, 1)]));
T2O = VZMULJ(T2M, T2N);
T2Q = LD(&(x[WS(rs, 25)]), ms, &(x[WS(rs, 1)]));
T2R = VZMULJ(T2P, T2Q);
T2S = VADD(T2O, T2R);
T6E = VSUB(T2O, T2R);
}
T2c = VSUB(T25, T2b);
T2T = VSUB(T2L, T2S);
T52 = VADD(T25, T2b);
T53 = VADD(T2L, T2S);
T54 = VADD(T52, T53);
T5G = VSUB(T52, T53);
{
V T6C, T6F, T6P, T6Q;
T6C = VSUB(T21, T24);
T6F = VADD(T6D, T6E);
T6G = VFMA(LDK(KP707106781), T6F, T6C);
T8m = VFNMS(LDK(KP707106781), T6F, T6C);
T6P = VSUB(T27, T2a);
T6Q = VSUB(T6D, T6E);
T6R = VFMA(LDK(KP707106781), T6Q, T6P);
T8p = VFNMS(LDK(KP707106781), T6Q, T6P);
}
}
{
V T2Y, T31, T32, T34, T37, T38, T3I, T6Z, T3O, T6Y, T59, T5a;
{
V T2X, T30, T33, T36;
T2X = LD(&(x[WS(rs, 63)]), ms, &(x[WS(rs, 1)]));
T2Y = VZMULJ(Tj, T2X);
T30 = LD(&(x[WS(rs, 31)]), ms, &(x[WS(rs, 1)]));
T31 = VZMULJ(T2Z, T30);
T32 = VADD(T2Y, T31);
T33 = LD(&(x[WS(rs, 15)]), ms, &(x[WS(rs, 1)]));
T34 = VZMULJ(Ti, T33);
T36 = LD(&(x[WS(rs, 47)]), ms, &(x[WS(rs, 1)]));
T37 = VZMULJ(T35, T36);
T38 = VADD(T34, T37);
}
{
V T3E, T3H, T3D, T3G;
T3D = LD(&(x[WS(rs, 55)]), ms, &(x[WS(rs, 1)]));
T3E = VZMULJ(T3C, T3D);
T3G = LD(&(x[WS(rs, 23)]), ms, &(x[WS(rs, 1)]));
T3H = VZMULJ(T3F, T3G);
T3I = VADD(T3E, T3H);
T6Z = VSUB(T3E, T3H);
}
{
V T3K, T3N, T3J, T3M;
T3J = LD(&(x[WS(rs, 7)]), ms, &(x[WS(rs, 1)]));
T3K = VZMULJ(Tv, T3J);
T3M = LD(&(x[WS(rs, 39)]), ms, &(x[WS(rs, 1)]));
T3N = VZMULJ(T3L, T3M);
T3O = VADD(T3K, T3N);
T6Y = VSUB(T3K, T3N);
}
T39 = VSUB(T32, T38);
T3P = VSUB(T3I, T3O);
T59 = VADD(T32, T38);
T5a = VADD(T3O, T3I);
T5b = VADD(T59, T5a);
T5J = VSUB(T59, T5a);
{
V T6X, T70, T7a, T7b;
T6X = VSUB(T2Y, T31);
T70 = VADD(T6Y, T6Z);
T71 = VFMA(LDK(KP707106781), T70, T6X);
T8t = VFNMS(LDK(KP707106781), T70, T6X);
T7a = VSUB(T37, T34);
T7b = VSUB(T6Z, T6Y);
T7c = VFMA(LDK(KP707106781), T7b, T7a);
T8w = VFNMS(LDK(KP707106781), T7b, T7a);
}
}
{
V T1v, T1y, T1z, T1C, T1G, T1H, T1P, T6t, T1V, T6s, T6w, T6x;
{
V T1u, T1x, T1B, T1F;
T1u = LD(&(x[WS(rs, 62)]), ms, &(x[0]));
T1v = VZMULJ(T1t, T1u);
T1x = LD(&(x[WS(rs, 30)]), ms, &(x[0]));
T1y = VZMULJ(T1w, T1x);
T1z = VADD(T1v, T1y);
T1B = LD(&(x[WS(rs, 14)]), ms, &(x[0]));
T1C = VZMULJ(T1A, T1B);
T1F = LD(&(x[WS(rs, 46)]), ms, &(x[0]));
T1G = VZMULJ(T1E, T1F);
T1H = VADD(T1C, T1G);
}
{
V T1L, T1O, T1K, T1N;
T1K = LD(&(x[WS(rs, 54)]), ms, &(x[0]));
T1L = VZMULJ(T1J, T1K);
T1N = LD(&(x[WS(rs, 22)]), ms, &(x[0]));
T1O = VZMULJ(T1M, T1N);
T1P = VADD(T1L, T1O);
T6t = VSUB(T1L, T1O);
}
{
V T1R, T1U, T1Q, T1T;
T1Q = LD(&(x[WS(rs, 6)]), ms, &(x[0]));
T1R = VZMULJ(T1e, T1Q);
T1T = LD(&(x[WS(rs, 38)]), ms, &(x[0]));
T1U = VZMULJ(T1S, T1T);
T1V = VADD(T1R, T1U);
T6s = VSUB(T1R, T1U);
}
T5i = VADD(T1z, T1H);
T5j = VADD(T1V, T1P);
T5D = VSUB(T5i, T5j);
T6w = VSUB(T1G, T1C);
T6x = VSUB(T6t, T6s);
T6y = VFMA(LDK(KP707106781), T6x, T6w);
T8h = VFNMS(LDK(KP707106781), T6x, T6w);
{
V T1I, T1W, T6r, T6u;
T1I = VSUB(T1z, T1H);
T1W = VSUB(T1P, T1V);
T1X = VFNMS(LDK(KP414213562), T1W, T1I);
T4b = VFMA(LDK(KP414213562), T1I, T1W);
T6r = VSUB(T1v, T1y);
T6u = VADD(T6s, T6t);
T6v = VFMA(LDK(KP707106781), T6u, T6r);
T8i = VFNMS(LDK(KP707106781), T6u, T6r);
}
}
{
V TX, T10, T11, T14, T18, T19, T1j, T6j, T1q, T6k, T6n, T6o;
{
V TW, TZ, T13, T17;
TW = LD(&(x[WS(rs, 2)]), ms, &(x[0]));
TX = VZMULJ(Tc, TW);
TZ = LD(&(x[WS(rs, 34)]), ms, &(x[0]));
T10 = VZMULJ(TY, TZ);
T11 = VADD(TX, T10);
T13 = LD(&(x[WS(rs, 18)]), ms, &(x[0]));
T14 = VZMULJ(T12, T13);
T17 = LD(&(x[WS(rs, 50)]), ms, &(x[0]));
T18 = VZMULJ(T16, T17);
T19 = VADD(T14, T18);
}
{
V T1d, T1i, T1c, T1h;
T1c = LD(&(x[WS(rs, 10)]), ms, &(x[0]));
T1d = VZMULJ(T1b, T1c);
T1h = LD(&(x[WS(rs, 42)]), ms, &(x[0]));
T1i = VZMULJ(T1g, T1h);
T1j = VADD(T1d, T1i);
T6j = VSUB(T1d, T1i);
}
{
V T1m, T1p, T1l, T1o;
T1l = LD(&(x[WS(rs, 58)]), ms, &(x[0]));
T1m = VZMULJ(T1k, T1l);
T1o = LD(&(x[WS(rs, 26)]), ms, &(x[0]));
T1p = VZMULJ(T1n, T1o);
T1q = VADD(T1m, T1p);
T6k = VSUB(T1m, T1p);
}
T5l = VADD(T11, T19);
T5m = VADD(T1j, T1q);
T5C = VSUB(T5l, T5m);
T6n = VSUB(T14, T18);
T6o = VSUB(T6j, T6k);
T6p = VFMA(LDK(KP707106781), T6o, T6n);
T8e = VFNMS(LDK(KP707106781), T6o, T6n);
{
V T1a, T1r, T6i, T6l;
T1a = VSUB(T11, T19);
T1r = VSUB(T1j, T1q);
T1s = VFNMS(LDK(KP414213562), T1r, T1a);
T4c = VFMA(LDK(KP414213562), T1a, T1r);
T6i = VSUB(TX, T10);
T6l = VADD(T6j, T6k);
T6m = VFMA(LDK(KP707106781), T6l, T6i);
T8f = VFNMS(LDK(KP707106781), T6l, T6i);
}
}
{
V Tu, T6a, TS, T6e, TC, T6b, TK, T6d, TD, TT;
{
V Tq, Tt, Tp, Ts;
Tp = LD(&(x[WS(rs, 4)]), ms, &(x[0]));
Tq = VZMULJ(T4, Tp);
Ts = LD(&(x[WS(rs, 36)]), ms, &(x[0]));
Tt = VZMULJ(Tr, Ts);
Tu = VADD(Tq, Tt);
T6a = VSUB(Tq, Tt);
}
{
V TM, TR, TL, TQ;
TL = LD(&(x[WS(rs, 12)]), ms, &(x[0]));
TM = VZMULJ(Th, TL);
TQ = LD(&(x[WS(rs, 44)]), ms, &(x[0]));
TR = VZMULJ(TP, TQ);
TS = VADD(TM, TR);
T6e = VSUB(TR, TM);
}
{
V Ty, TB, Tx, TA;
Tx = LD(&(x[WS(rs, 20)]), ms, &(x[0]));
Ty = VZMULJ(Tw, Tx);
TA = LD(&(x[WS(rs, 52)]), ms, &(x[0]));
TB = VZMULJ(Tz, TA);
TC = VADD(Ty, TB);
T6b = VSUB(Ty, TB);
}
{
V TG, TJ, TF, TI;
TF = LD(&(x[WS(rs, 60)]), ms, &(x[0]));
TG = VZMULJ(TE, TF);
TI = LD(&(x[WS(rs, 28)]), ms, &(x[0]));
TJ = VZMULJ(TH, TI);
TK = VADD(TG, TJ);
T6d = VSUB(TG, TJ);
}
T4Y = VADD(Tu, TC);
T4Z = VADD(TK, TS);
TD = VSUB(Tu, TC);
TT = VSUB(TK, TS);
TU = VADD(TD, TT);
T49 = VSUB(TT, TD);
{
V T6c, T6f, T7n, T7o;
T6c = VFNMS(LDK(KP414213562), T6b, T6a);
T6f = VFNMS(LDK(KP414213562), T6e, T6d);
T6g = VADD(T6c, T6f);
T8D = VSUB(T6f, T6c);
T7n = VFMA(LDK(KP414213562), T6a, T6b);
T7o = VFMA(LDK(KP414213562), T6d, T6e);
T7p = VSUB(T7n, T7o);
T8c = VADD(T7n, T7o);
}
}
{
V T2i, T6H, T2C, T6L, T2o, T6I, T2w, T6K;
{
V T2e, T2h, T2d, T2g;
T2d = LD(&(x[WS(rs, 5)]), ms, &(x[WS(rs, 1)]));
T2e = VZMULJ(T6, T2d);
T2g = LD(&(x[WS(rs, 37)]), ms, &(x[WS(rs, 1)]));
T2h = VZMULJ(T2f, T2g);
T2i = VADD(T2e, T2h);
T6H = VSUB(T2e, T2h);
}
{
V T2y, T2B, T2x, T2A;
T2x = LD(&(x[WS(rs, 13)]), ms, &(x[WS(rs, 1)]));
T2y = VZMULJ(T15, T2x);
T2A = LD(&(x[WS(rs, 45)]), ms, &(x[WS(rs, 1)]));
T2B = VZMULJ(T2z, T2A);
T2C = VADD(T2y, T2B);
T6L = VSUB(T2y, T2B);
}
{
V T2k, T2n, T2j, T2m;
T2j = LD(&(x[WS(rs, 21)]), ms, &(x[WS(rs, 1)]));
T2k = VZMULJ(T1f, T2j);
T2m = LD(&(x[WS(rs, 53)]), ms, &(x[WS(rs, 1)]));
T2n = VZMULJ(T2l, T2m);
T2o = VADD(T2k, T2n);
T6I = VSUB(T2k, T2n);
}
{
V T2s, T2v, T2r, T2u;
T2r = LD(&(x[WS(rs, 61)]), ms, &(x[WS(rs, 1)]));
T2s = VZMULJ(T2q, T2r);
T2u = LD(&(x[WS(rs, 29)]), ms, &(x[WS(rs, 1)]));
T2v = VZMULJ(T2t, T2u);
T2w = VADD(T2s, T2v);
T6K = VSUB(T2s, T2v);
}
{
V T2p, T2D, T6S, T6T;
T2p = VSUB(T2i, T2o);
T2D = VSUB(T2w, T2C);
T2E = VADD(T2p, T2D);
T2U = VSUB(T2p, T2D);
T6S = VFMA(LDK(KP414213562), T6H, T6I);
T6T = VFNMS(LDK(KP414213562), T6K, T6L);
T6U = VADD(T6S, T6T);
T8n = VSUB(T6S, T6T);
}
{
V T55, T56, T6J, T6M;
T55 = VADD(T2i, T2o);
T56 = VADD(T2w, T2C);
T57 = VADD(T55, T56);
T5H = VSUB(T55, T56);
T6J = VFNMS(LDK(KP414213562), T6I, T6H);
T6M = VFMA(LDK(KP414213562), T6L, T6K);
T6N = VADD(T6J, T6M);
T8q = VSUB(T6J, T6M);
}
}
{
V T3f, T72, T3y, T76, T3l, T73, T3s, T75;
{
V T3b, T3e, T3a, T3d;
T3a = LD(&(x[WS(rs, 3)]), ms, &(x[WS(rs, 1)]));
T3b = VZMULJ(T3, T3a);
T3d = LD(&(x[WS(rs, 35)]), ms, &(x[WS(rs, 1)]));
T3e = VZMULJ(T3c, T3d);
T3f = VADD(T3b, T3e);
T72 = VSUB(T3b, T3e);
}
{
V T3u, T3x, T3t, T3w;
T3t = LD(&(x[WS(rs, 11)]), ms, &(x[WS(rs, 1)]));
T3u = VZMULJ(Td, T3t);
T3w = LD(&(x[WS(rs, 43)]), ms, &(x[WS(rs, 1)]));
T3x = VZMULJ(T3v, T3w);
T3y = VADD(T3u, T3x);
T76 = VSUB(T3x, T3u);
}
{
V T3h, T3k, T3g, T3j;
T3g = LD(&(x[WS(rs, 19)]), ms, &(x[WS(rs, 1)]));
T3h = VZMULJ(TO, T3g);
T3j = LD(&(x[WS(rs, 51)]), ms, &(x[WS(rs, 1)]));
T3k = VZMULJ(T3i, T3j);
T3l = VADD(T3h, T3k);
T73 = VSUB(T3k, T3h);
}
{
V T3p, T3r, T3o, T3q;
T3o = LD(&(x[WS(rs, 59)]), ms, &(x[WS(rs, 1)]));
T3p = VZMULJ(T3n, T3o);
T3q = LD(&(x[WS(rs, 27)]), ms, &(x[WS(rs, 1)]));
T3r = VZMULJ(T7, T3q);
T3s = VADD(T3p, T3r);
T75 = VSUB(T3p, T3r);
}
{
V T3m, T3z, T7d, T7e;
T3m = VSUB(T3f, T3l);
T3z = VSUB(T3s, T3y);
T3A = VADD(T3m, T3z);
T3Q = VSUB(T3z, T3m);
T7d = VFNMS(LDK(KP414213562), T72, T73);
T7e = VFMA(LDK(KP414213562), T75, T76);
T7f = VADD(T7d, T7e);
T8u = VSUB(T7e, T7d);
}
{
V T5c, T5d, T74, T77;
T5c = VADD(T3f, T3l);
T5d = VADD(T3s, T3y);
T5e = VADD(T5c, T5d);
T5K = VSUB(T5d, T5c);
T74 = VFMA(LDK(KP414213562), T73, T72);
T77 = VFNMS(LDK(KP414213562), T76, T75);
T78 = VADD(T74, T77);
T8x = VSUB(T77, T74);
}
}
{
V T51, T5t, T5y, T5A, T5g, T5p, T5o, T5u, T5v, T5z;
{
V T4X, T50, T5w, T5x;
T4X = VADD(T4V, T4W);
T50 = VADD(T4Y, T4Z);
T51 = VSUB(T4X, T50);
T5t = VADD(T4X, T50);
T5w = VADD(T54, T57);
T5x = VADD(T5b, T5e);
T5y = VADD(T5w, T5x);
T5A = VSUB(T5x, T5w);
}
{
V T58, T5f, T5k, T5n;
T58 = VSUB(T54, T57);
T5f = VSUB(T5b, T5e);
T5g = VADD(T58, T5f);
T5p = VSUB(T5f, T58);
T5k = VADD(T5i, T5j);
T5n = VADD(T5l, T5m);
T5o = VSUB(T5k, T5n);
T5u = VADD(T5n, T5k);
}
T5v = VADD(T5t, T5u);
ST(&(x[WS(rs, 32)]),VSUB(T5v, T5y),ms,&(x[0]));
ST(&(x[0]),VADD(T5v, T5y),ms,&(x[0]));
T5z = VSUB(T5t, T5u);
ST(&(x[WS(rs, 48)]),VFNMSI(T5A, T5z),ms,&(x[0]));
ST(&(x[WS(rs, 16)]),VFMAI(T5A, T5z),ms,&(x[0]));
{
V T5h, T5q, T5r, T5s;
T5h = VFNMS(LDK(KP707106781), T5g, T51);
T5q = VFNMS(LDK(KP707106781), T5p, T5o);
ST(&(x[WS(rs, 24)]),VFNMSI(T5q, T5h),ms,&(x[0]));
ST(&(x[WS(rs, 40)]),VFMAI(T5q, T5h),ms,&(x[0]));
T5r = VFMA(LDK(KP707106781), T5g, T51);
T5s = VFMA(LDK(KP707106781), T5p, T5o);
ST(&(x[WS(rs, 56)]),VFNMSI(T5s, T5r),ms,&(x[0]));
ST(&(x[WS(rs, 8)]),VFMAI(T5s, T5r),ms,&(x[0]));
}
}
{
V T5F, T5X, T5T, T5Y, T5M, T61, T5Q, T60;
{
V T5B, T5E, T5R, T5S;
T5B = VSUB(T4V, T4W);
T5E = VADD(T5C, T5D);
T5F = VFMA(LDK(KP707106781), T5E, T5B);
T5X = VFNMS(LDK(KP707106781), T5E, T5B);
T5R = VFMA(LDK(KP414213562), T5J, T5K);
T5S = VFMA(LDK(KP414213562), T5G, T5H);
T5T = VSUB(T5R, T5S);
T5Y = VADD(T5S, T5R);
}
{
V T5I, T5L, T5O, T5P;
T5I = VFNMS(LDK(KP414213562), T5H, T5G);
T5L = VFNMS(LDK(KP414213562), T5K, T5J);
T5M = VADD(T5I, T5L);
T61 = VSUB(T5L, T5I);
T5O = VSUB(T4Z, T4Y);
T5P = VSUB(T5D, T5C);
T5Q = VFMA(LDK(KP707106781), T5P, T5O);
T60 = VFNMS(LDK(KP707106781), T5P, T5O);
}
{
V T5N, T5U, T63, T64;
T5N = VFNMS(LDK(KP923879532), T5M, T5F);
T5U = VFNMS(LDK(KP923879532), T5T, T5Q);
ST(&(x[WS(rs, 28)]),VFNMSI(T5U, T5N),ms,&(x[0]));
ST(&(x[WS(rs, 36)]),VFMAI(T5U, T5N),ms,&(x[0]));
T63 = VFMA(LDK(KP923879532), T5Y, T5X);
T64 = VFNMS(LDK(KP923879532), T61, T60);
ST(&(x[WS(rs, 12)]),VFNMSI(T64, T63),ms,&(x[0]));
ST(&(x[WS(rs, 52)]),VFMAI(T64, T63),ms,&(x[0]));
}
{
V T5V, T5W, T5Z, T62;
T5V = VFMA(LDK(KP923879532), T5M, T5F);
T5W = VFMA(LDK(KP923879532), T5T, T5Q);
ST(&(x[WS(rs, 60)]),VFNMSI(T5W, T5V),ms,&(x[0]));
ST(&(x[WS(rs, 4)]),VFMAI(T5W, T5V),ms,&(x[0]));
T5Z = VFNMS(LDK(KP923879532), T5Y, T5X);
T62 = VFMA(LDK(KP923879532), T61, T60);
ST(&(x[WS(rs, 20)]),VFMAI(T62, T5Z),ms,&(x[0]));
ST(&(x[WS(rs, 44)]),VFNMSI(T62, T5Z),ms,&(x[0]));
}
}
{
V T1Z, T4l, T4e, T4o, T3T, T4p, T4h, T4m;
{
V TV, T1Y, T4a, T4d;
TV = VFMA(LDK(KP707106781), TU, To);
T1Y = VADD(T1s, T1X);
T1Z = VFMA(LDK(KP923879532), T1Y, TV);
T4l = VFNMS(LDK(KP923879532), T1Y, TV);
T4a = VFMA(LDK(KP707106781), T49, T48);
T4d = VSUB(T4b, T4c);
T4e = VFMA(LDK(KP923879532), T4d, T4a);
T4o = VFNMS(LDK(KP923879532), T4d, T4a);
{
V T2W, T4g, T3S, T4f;
{
V T2F, T2V, T3B, T3R;
T2F = VFMA(LDK(KP707106781), T2E, T2c);
T2V = VFMA(LDK(KP707106781), T2U, T2T);
T2W = VFNMS(LDK(KP198912367), T2V, T2F);
T4g = VFMA(LDK(KP198912367), T2F, T2V);
T3B = VFMA(LDK(KP707106781), T3A, T39);
T3R = VFMA(LDK(KP707106781), T3Q, T3P);
T3S = VFNMS(LDK(KP198912367), T3R, T3B);
T4f = VFMA(LDK(KP198912367), T3B, T3R);
}
T3T = VADD(T2W, T3S);
T4p = VSUB(T3S, T2W);
T4h = VSUB(T4f, T4g);
T4m = VADD(T4g, T4f);
}
}
{
V T3U, T4i, T4r, T4s;
T3U = VFNMS(LDK(KP980785280), T3T, T1Z);
T4i = VFNMS(LDK(KP980785280), T4h, T4e);
ST(&(x[WS(rs, 30)]),VFNMSI(T4i, T3U),ms,&(x[0]));
ST(&(x[WS(rs, 34)]),VFMAI(T4i, T3U),ms,&(x[0]));
T4r = VFMA(LDK(KP980785280), T4m, T4l);
T4s = VFNMS(LDK(KP980785280), T4p, T4o);
ST(&(x[WS(rs, 14)]),VFNMSI(T4s, T4r),ms,&(x[0]));
ST(&(x[WS(rs, 50)]),VFMAI(T4s, T4r),ms,&(x[0]));
}
{
V T4j, T4k, T4n, T4q;
T4j = VFMA(LDK(KP980785280), T3T, T1Z);
T4k = VFMA(LDK(KP980785280), T4h, T4e);
ST(&(x[WS(rs, 62)]),VFNMSI(T4k, T4j),ms,&(x[0]));
ST(&(x[WS(rs, 2)]),VFMAI(T4k, T4j),ms,&(x[0]));
T4n = VFNMS(LDK(KP980785280), T4m, T4l);
T4q = VFMA(LDK(KP980785280), T4p, T4o);
ST(&(x[WS(rs, 18)]),VFMAI(T4q, T4n),ms,&(x[0]));
ST(&(x[WS(rs, 46)]),VFNMSI(T4q, T4n),ms,&(x[0]));
}
}
{
V T4v, T4N, T4G, T4Q, T4C, T4R, T4J, T4O;
{
V T4t, T4u, T4E, T4F;
T4t = VFNMS(LDK(KP707106781), TU, To);
T4u = VADD(T4c, T4b);
T4v = VFMA(LDK(KP923879532), T4u, T4t);
T4N = VFNMS(LDK(KP923879532), T4u, T4t);
T4E = VFNMS(LDK(KP707106781), T49, T48);
T4F = VSUB(T1X, T1s);
T4G = VFNMS(LDK(KP923879532), T4F, T4E);
T4Q = VFMA(LDK(KP923879532), T4F, T4E);
{
V T4y, T4I, T4B, T4H;
{
V T4w, T4x, T4z, T4A;
T4w = VFNMS(LDK(KP707106781), T2E, T2c);
T4x = VFNMS(LDK(KP707106781), T2U, T2T);
T4y = VFMA(LDK(KP668178637), T4x, T4w);
T4I = VFNMS(LDK(KP668178637), T4w, T4x);
T4z = VFNMS(LDK(KP707106781), T3A, T39);
T4A = VFNMS(LDK(KP707106781), T3Q, T3P);
T4B = VFMA(LDK(KP668178637), T4A, T4z);
T4H = VFNMS(LDK(KP668178637), T4z, T4A);
}
T4C = VADD(T4y, T4B);
T4R = VSUB(T4B, T4y);
T4J = VSUB(T4H, T4I);
T4O = VADD(T4I, T4H);
}
}
{
V T4D, T4K, T4T, T4U;
T4D = VFNMS(LDK(KP831469612), T4C, T4v);
T4K = VFNMS(LDK(KP831469612), T4J, T4G);
ST(&(x[WS(rs, 38)]),VFNMSI(T4K, T4D),ms,&(x[0]));
ST(&(x[WS(rs, 26)]),VFMAI(T4K, T4D),ms,&(x[0]));
T4T = VFNMS(LDK(KP831469612), T4O, T4N);
T4U = VFMA(LDK(KP831469612), T4R, T4Q);
ST(&(x[WS(rs, 10)]),VFMAI(T4U, T4T),ms,&(x[0]));
ST(&(x[WS(rs, 54)]),VFNMSI(T4U, T4T),ms,&(x[0]));
}
{
V T4L, T4M, T4P, T4S;
T4L = VFMA(LDK(KP831469612), T4C, T4v);
T4M = VFMA(LDK(KP831469612), T4J, T4G);
ST(&(x[WS(rs, 6)]),VFNMSI(T4M, T4L),ms,&(x[0]));
ST(&(x[WS(rs, 58)]),VFMAI(T4M, T4L),ms,&(x[0]));
T4P = VFMA(LDK(KP831469612), T4O, T4N);
T4S = VFNMS(LDK(KP831469612), T4R, T4Q);
ST(&(x[WS(rs, 22)]),VFNMSI(T4S, T4P),ms,&(x[0]));
ST(&(x[WS(rs, 42)]),VFMAI(T4S, T4P),ms,&(x[0]));
}
}
{
V T8l, T9k, T8P, T9a, T8I, T9h, T8S, T8Z, T8A, T8T, T8L, T8Q, T96, T9l, T9d;
V T9i;
{
V T8d, T98, T8k, T99, T8g, T8j;
T8d = VFNMS(LDK(KP923879532), T8c, T8b);
T98 = VFMA(LDK(KP923879532), T8D, T8C);
T8g = VFNMS(LDK(KP668178637), T8f, T8e);
T8j = VFNMS(LDK(KP668178637), T8i, T8h);
T8k = VADD(T8g, T8j);
T99 = VSUB(T8g, T8j);
T8l = VFNMS(LDK(KP831469612), T8k, T8d);
T9k = VFNMS(LDK(KP831469612), T99, T98);
T8P = VFMA(LDK(KP831469612), T8k, T8d);
T9a = VFMA(LDK(KP831469612), T99, T98);
}
{
V T8E, T8X, T8H, T8Y, T8F, T8G;
T8E = VFNMS(LDK(KP923879532), T8D, T8C);
T8X = VFMA(LDK(KP923879532), T8c, T8b);
T8F = VFMA(LDK(KP668178637), T8h, T8i);
T8G = VFMA(LDK(KP668178637), T8e, T8f);
T8H = VSUB(T8F, T8G);
T8Y = VADD(T8G, T8F);
T8I = VFNMS(LDK(KP831469612), T8H, T8E);
T9h = VFNMS(LDK(KP831469612), T8Y, T8X);
T8S = VFMA(LDK(KP831469612), T8H, T8E);
T8Z = VFMA(LDK(KP831469612), T8Y, T8X);
}
{
V T8s, T8J, T8z, T8K;
{
V T8o, T8r, T8v, T8y;
T8o = VFNMS(LDK(KP923879532), T8n, T8m);
T8r = VFMA(LDK(KP923879532), T8q, T8p);
T8s = VFNMS(LDK(KP534511135), T8r, T8o);
T8J = VFMA(LDK(KP534511135), T8o, T8r);
T8v = VFNMS(LDK(KP923879532), T8u, T8t);
T8y = VFMA(LDK(KP923879532), T8x, T8w);
T8z = VFNMS(LDK(KP534511135), T8y, T8v);
T8K = VFMA(LDK(KP534511135), T8v, T8y);
}
T8A = VADD(T8s, T8z);
T8T = VSUB(T8z, T8s);
T8L = VSUB(T8J, T8K);
T8Q = VADD(T8J, T8K);
}
{
V T92, T9b, T95, T9c;
{
V T90, T91, T93, T94;
T90 = VFMA(LDK(KP923879532), T8n, T8m);
T91 = VFNMS(LDK(KP923879532), T8q, T8p);
T92 = VFMA(LDK(KP303346683), T91, T90);
T9b = VFNMS(LDK(KP303346683), T90, T91);
T93 = VFMA(LDK(KP923879532), T8u, T8t);
T94 = VFNMS(LDK(KP923879532), T8x, T8w);
T95 = VFMA(LDK(KP303346683), T94, T93);
T9c = VFNMS(LDK(KP303346683), T93, T94);
}
T96 = VADD(T92, T95);
T9l = VSUB(T95, T92);
T9d = VSUB(T9b, T9c);
T9i = VADD(T9b, T9c);
}
{
V T8B, T8M, T9j, T9m;
T8B = VFNMS(LDK(KP881921264), T8A, T8l);
T8M = VFNMS(LDK(KP881921264), T8L, T8I);
ST(&(x[WS(rs, 37)]),VFNMSI(T8M, T8B),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 27)]),VFMAI(T8M, T8B),ms,&(x[WS(rs, 1)]));
T9j = VFMA(LDK(KP956940335), T9i, T9h);
T9m = VFMA(LDK(KP956940335), T9l, T9k);
ST(&(x[WS(rs, 19)]),VFMAI(T9m, T9j),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 45)]),VFNMSI(T9m, T9j),ms,&(x[WS(rs, 1)]));
}
{
V T9n, T9o, T8N, T8O;
T9n = VFNMS(LDK(KP956940335), T9i, T9h);
T9o = VFNMS(LDK(KP956940335), T9l, T9k);
ST(&(x[WS(rs, 13)]),VFNMSI(T9o, T9n),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 51)]),VFMAI(T9o, T9n),ms,&(x[WS(rs, 1)]));
T8N = VFMA(LDK(KP881921264), T8A, T8l);
T8O = VFMA(LDK(KP881921264), T8L, T8I);
ST(&(x[WS(rs, 5)]),VFNMSI(T8O, T8N),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 59)]),VFMAI(T8O, T8N),ms,&(x[WS(rs, 1)]));
}
{
V T8R, T8U, T97, T9e;
T8R = VFNMS(LDK(KP881921264), T8Q, T8P);
T8U = VFNMS(LDK(KP881921264), T8T, T8S);
ST(&(x[WS(rs, 21)]),VFNMSI(T8U, T8R),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 43)]),VFMAI(T8U, T8R),ms,&(x[WS(rs, 1)]));
T97 = VFNMS(LDK(KP956940335), T96, T8Z);
T9e = VFNMS(LDK(KP956940335), T9d, T9a);
ST(&(x[WS(rs, 29)]),VFNMSI(T9e, T97),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 35)]),VFMAI(T9e, T97),ms,&(x[WS(rs, 1)]));
}
{
V T9f, T9g, T8V, T8W;
T9f = VFMA(LDK(KP956940335), T96, T8Z);
T9g = VFMA(LDK(KP956940335), T9d, T9a);
ST(&(x[WS(rs, 61)]),VFNMSI(T9g, T9f),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 3)]),VFMAI(T9g, T9f),ms,&(x[WS(rs, 1)]));
T8V = VFMA(LDK(KP881921264), T8Q, T8P);
T8W = VFMA(LDK(KP881921264), T8T, T8S);
ST(&(x[WS(rs, 11)]),VFMAI(T8W, T8V),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 53)]),VFNMSI(T8W, T8V),ms,&(x[WS(rs, 1)]));
}
}
{
V T6B, T86, T7B, T7W, T7u, T83, T7E, T7L, T7i, T7F, T7x, T7C, T7S, T87, T7Z;
V T84;
{
V T6h, T7U, T6A, T7V, T6q, T6z;
T6h = VFMA(LDK(KP923879532), T6g, T69);
T7U = VFNMS(LDK(KP923879532), T7p, T7m);
T6q = VFNMS(LDK(KP198912367), T6p, T6m);
T6z = VFNMS(LDK(KP198912367), T6y, T6v);
T6A = VADD(T6q, T6z);
T7V = VSUB(T6z, T6q);
T6B = VFMA(LDK(KP980785280), T6A, T6h);
T86 = VFNMS(LDK(KP980785280), T7V, T7U);
T7B = VFNMS(LDK(KP980785280), T6A, T6h);
T7W = VFMA(LDK(KP980785280), T7V, T7U);
}
{
V T7q, T7J, T7t, T7K, T7r, T7s;
T7q = VFMA(LDK(KP923879532), T7p, T7m);
T7J = VFNMS(LDK(KP923879532), T6g, T69);
T7r = VFMA(LDK(KP198912367), T6m, T6p);
T7s = VFMA(LDK(KP198912367), T6v, T6y);
T7t = VSUB(T7r, T7s);
T7K = VADD(T7r, T7s);
T7u = VFMA(LDK(KP980785280), T7t, T7q);
T83 = VFNMS(LDK(KP980785280), T7K, T7J);
T7E = VFNMS(LDK(KP980785280), T7t, T7q);
T7L = VFMA(LDK(KP980785280), T7K, T7J);
}
{
V T6W, T7v, T7h, T7w;
{
V T6O, T6V, T79, T7g;
T6O = VFMA(LDK(KP923879532), T6N, T6G);
T6V = VFMA(LDK(KP923879532), T6U, T6R);
T6W = VFNMS(LDK(KP098491403), T6V, T6O);
T7v = VFMA(LDK(KP098491403), T6O, T6V);
T79 = VFMA(LDK(KP923879532), T78, T71);
T7g = VFMA(LDK(KP923879532), T7f, T7c);
T7h = VFNMS(LDK(KP098491403), T7g, T79);
T7w = VFMA(LDK(KP098491403), T79, T7g);
}
T7i = VADD(T6W, T7h);
T7F = VSUB(T7h, T6W);
T7x = VSUB(T7v, T7w);
T7C = VADD(T7v, T7w);
}
{
V T7O, T7X, T7R, T7Y;
{
V T7M, T7N, T7P, T7Q;
T7M = VFNMS(LDK(KP923879532), T6N, T6G);
T7N = VFNMS(LDK(KP923879532), T6U, T6R);
T7O = VFMA(LDK(KP820678790), T7N, T7M);
T7X = VFNMS(LDK(KP820678790), T7M, T7N);
T7P = VFNMS(LDK(KP923879532), T78, T71);
T7Q = VFNMS(LDK(KP923879532), T7f, T7c);
T7R = VFMA(LDK(KP820678790), T7Q, T7P);
T7Y = VFNMS(LDK(KP820678790), T7P, T7Q);
}
T7S = VADD(T7O, T7R);
T87 = VSUB(T7R, T7O);
T7Z = VSUB(T7X, T7Y);
T84 = VADD(T7X, T7Y);
}
{
V T7j, T7y, T85, T88;
T7j = VFNMS(LDK(KP995184726), T7i, T6B);
T7y = VFNMS(LDK(KP995184726), T7x, T7u);
ST(&(x[WS(rs, 33)]),VFNMSI(T7y, T7j),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 31)]),VFMAI(T7y, T7j),ms,&(x[WS(rs, 1)]));
T85 = VFMA(LDK(KP773010453), T84, T83);
T88 = VFMA(LDK(KP773010453), T87, T86);
ST(&(x[WS(rs, 23)]),VFMAI(T88, T85),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 41)]),VFNMSI(T88, T85),ms,&(x[WS(rs, 1)]));
}
{
V T89, T8a, T7z, T7A;
T89 = VFNMS(LDK(KP773010453), T84, T83);
T8a = VFNMS(LDK(KP773010453), T87, T86);
ST(&(x[WS(rs, 9)]),VFNMSI(T8a, T89),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 55)]),VFMAI(T8a, T89),ms,&(x[WS(rs, 1)]));
T7z = VFMA(LDK(KP995184726), T7i, T6B);
T7A = VFMA(LDK(KP995184726), T7x, T7u);
ST(&(x[WS(rs, 1)]),VFNMSI(T7A, T7z),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 63)]),VFMAI(T7A, T7z),ms,&(x[WS(rs, 1)]));
}
{
V T7D, T7G, T7T, T80;
T7D = VFNMS(LDK(KP995184726), T7C, T7B);
T7G = VFNMS(LDK(KP995184726), T7F, T7E);
ST(&(x[WS(rs, 17)]),VFNMSI(T7G, T7D),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 47)]),VFMAI(T7G, T7D),ms,&(x[WS(rs, 1)]));
T7T = VFNMS(LDK(KP773010453), T7S, T7L);
T80 = VFNMS(LDK(KP773010453), T7Z, T7W);
ST(&(x[WS(rs, 25)]),VFNMSI(T80, T7T),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 39)]),VFMAI(T80, T7T),ms,&(x[WS(rs, 1)]));
}
{
V T81, T82, T7H, T7I;
T81 = VFMA(LDK(KP773010453), T7S, T7L);
T82 = VFMA(LDK(KP773010453), T7Z, T7W);
ST(&(x[WS(rs, 57)]),VFNMSI(T82, T81),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 7)]),VFMAI(T82, T81),ms,&(x[WS(rs, 1)]));
T7H = VFMA(LDK(KP995184726), T7C, T7B);
T7I = VFMA(LDK(KP995184726), T7F, T7E);
ST(&(x[WS(rs, 15)]),VFMAI(T7I, T7H),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 49)]),VFNMSI(T7I, T7H),ms,&(x[WS(rs, 1)]));
}
}
}
}
}
VLEAVE();}


static const tw_instr twinstr[] = {
VTW(0,1),
VTW(0,3),
VTW(0,9),
VTW(0,27),
VTW(0,63),
{TW_NEXT, VL, 0}};

static const ct_desc desc = {64, XSIMD_STRING("t3fv_64"), twinstr, &GENUS, { 319, 242, 258, 0 }, 0, 0, 0};

void XSIMD(codelet_t3fv_64)(planner *p)
{
X(kdft_dit_register)(p, t3fv_64, &desc);
}
#else

/* Generated by: ../../../genfft/gen_twiddle_c.native -simd -compact -variables 4 -pipeline-latency 8 -twiddle-log3 -precompute-twiddles -no-generate-bytw -n 64 -name t3fv_64 -include dft/simd/t3f.h */

/*
 * This function contains 577 FP additions, 366 FP multiplications,
 * (or, 525 additions, 314 multiplications, 52 fused multiply/add),
 * 170 stack variables, 15 constants, and 128 memory accesses
 */
#include "dft/simd/t3f.h"

static void t3fv_64(R * ri, R * ii, const R * W, stride rs, INT mb, INT me, INT ms)
{
DVK(KP995184726, +0.995184726672196886244836953109479921575474869);
DVK(KP098017140, +0.098017140329560601994195563888641845861136673);
DVK(KP773010453, +0.773010453362736960810906609758469800971041293);
DVK(KP634393284, +0.634393284163645498215171613225493370675687095);
DVK(KP471396736, +0.471396736825997648556387625905254377657460319);
DVK(KP881921264, +0.881921264348355029712756863660388349508442621);
DVK(KP290284677, +0.290284677254462367636192375817395274691476278);
DVK(KP956940335, +0.956940335732208864935797886980269969482849206);
DVK(KP555570233, +0.555570233019602224742830813948532874374937191);
DVK(KP831469612, +0.831469612302545237078788377617905756738560812);
DVK(KP195090322, +0.195090322016128267848284868477022240927691618);
DVK(KP980785280, +0.980785280403230449126182236134239036973933731);
DVK(KP382683432, +0.382683432365089771728459984030398866761344562);
DVK(KP923879532, +0.923879532511286756128183189396788286822416626);
DVK(KP707106781, +0.707106781186547524400844362104849039284835938);
{
INT m;
R * x;
x = ri;
for (m = mb, W = W + (mb * ((TWVL/VL) * 10)); m < me; m = m + VL, x = x + (VL * ms), W = W + (TWVL * 10), MAKE_VOLATILE_STRIDE(64, rs)){
V T2, T3, T4, Tk, T5, T7, T6, T1u, T1R, Tc, Tf, TF, T1a, Tl, TS;
V T8, T3d, TO, T3y, Tg, Tq, Ty, T3q, T3j, T30, T2d, T21, T16, T2F, T2q;
V T1F, T1d, TC, T42, T45, TV, T1k, T1v, T1L, T1r, Tm, Tn, TG, T1h, T4l;
V T3E, T13, T46, T3R, TW, TL, T3J, T3n, T2S, T2j, T1w, T2a, T2w, T1C, T1M;
V T2C, T2L, T1U;
T2 = LDW(&(W[0]));
T3 = LDW(&(W[TWVL * 2]));
T4 = VZMUL(T2, T3);
Tk = VZMULJ(T2, T3);
T5 = LDW(&(W[TWVL * 4]));
T7 = LDW(&(W[TWVL * 6]));
T6 = VZMULJ(T4, T5);
T1u = VZMUL(T2, T5);
T1R = VZMULJ(T5, T7);
Tc = VZMULJ(T2, T5);
Tf = VZMUL(T4, T5);
TF = VZMUL(Tk, T5);
T1a = VZMULJ(T3, T5);
Tl = VZMULJ(Tk, T5);
TS = VZMUL(T3, T5);
T8 = VZMUL(T6, T7);
T3d = VZMUL(T4, T7);
TO = VZMUL(T2, T7);
T3y = VZMUL(Tc, T7);
Tg = VZMUL(Tf, T7);
Tq = VZMULJ(T3, T7);
Ty = VZMUL(T5, T7);
T3q = VZMULJ(T4, T7);
T3j = VZMUL(TS, T7);
T30 = VZMUL(T1a, T7);
T2d = VZMUL(Tk, T7);
T21 = VZMUL(Tl, T7);
T16 = VZMUL(T3, T7);
T2F = VZMULJ(Tk, T7);
T2q = VZMUL(T1u, T7);
T1F = VZMULJ(T2, T7);
T1d = VZMUL(TF, T7);
TC = VZMULJ(Tl, T7);
T42 = VZMULJ(TS, T7);
T45 = VZMULJ(TF, T7);
TV = VZMULJ(Tc, T7);
T1k = VZMULJ(T6, T7);
T1v = VZMULJ(T1u, T7);
T1L = VZMULJ(T1a, T7);
T1r = VZMULJ(Tf, T7);
Tm = LDW(&(W[TWVL * 8]));
Tn = VZMULJ(Tl, Tm);
TG = VZMULJ(TF, Tm);
T1h = VZMULJ(T5, Tm);
T4l = VZMULJ(T42, Tm);
T3E = VZMULJ(TS, Tm);
T13 = VZMULJ(T2, Tm);
T46 = VZMULJ(T45, Tm);
T3R = VZMULJ(TC, Tm);
TW = VZMULJ(TV, Tm);
TL = VZMULJ(T3, Tm);
T3J = VZMULJ(T4, Tm);
T3n = VZMULJ(Tc, Tm);
T2S = VZMULJ(T1r, Tm);
T2j = VZMULJ(T1R, Tm);
T1w = VZMULJ(T1v, Tm);
T2a = VZMULJ(Tk, Tm);
T2w = VZMULJ(T1u, Tm);
T1C = VZMULJ(T6, Tm);
T1M = VZMULJ(T1L, Tm);
T2C = VZMULJ(T1a, Tm);
T2L = VZMULJ(T1k, Tm);
T1U = VZMULJ(Tf, Tm);
{
V Tv, T5b, T7s, T8g, T4p, T5C, T6r, T8f, T6S, T73, T2W, T5p, T35, T5m, T8o;
V T90, T79, T7k, T3v, T5t, T4a, T5w, T8v, T93, T8F, T8G, T8W, T6G, T7v, T1Y;
V T5f, T26, T5e, T8C, T8D, T8X, T6N, T7w, T1p, T5h, T1A, T5i, T8i, T8j, T11;
V T5D, T4h, T5c, T6y, T7t, T2B, T5n, T8r, T91, T38, T5q, T6Z, T74, T3W, T5x;
V T8y, T94, T40, T5u, T7g, T7l;
{
V T1, Ta, T4n, T4k, Tp, Ts, Tt, Te, Ti, Tj, T9, T4m, T4j;
T1 = LD(&(x[0]), ms, &(x[0]));
T9 = LD(&(x[WS(rs, 32)]), ms, &(x[0]));
Ta = VZMULJ(T8, T9);
T4m = LD(&(x[WS(rs, 48)]), ms, &(x[0]));
T4n = VZMULJ(T4l, T4m);
T4j = LD(&(x[WS(rs, 16)]), ms, &(x[0]));
T4k = VZMULJ(T45, T4j);
{
V To, Tr, Td, Th;
To = LD(&(x[WS(rs, 56)]), ms, &(x[0]));
Tp = VZMULJ(Tn, To);
Tr = LD(&(x[WS(rs, 24)]), ms, &(x[0]));
Ts = VZMULJ(Tq, Tr);
Tt = VSUB(Tp, Ts);
Td = LD(&(x[WS(rs, 8)]), ms, &(x[0]));
Te = VZMULJ(Tc, Td);
Th = LD(&(x[WS(rs, 40)]), ms, &(x[0]));
Ti = VZMULJ(Tg, Th);
Tj = VSUB(Te, Ti);
}
{
V Tb, Tu, T7q, T7r;
Tb = VSUB(T1, Ta);
Tu = VMUL(LDK(KP707106781), VADD(Tj, Tt));
Tv = VADD(Tb, Tu);
T5b = VSUB(Tb, Tu);
T7q = VADD(Tp, Ts);
T7r = VADD(Te, Ti);
T7s = VSUB(T7q, T7r);
T8g = VADD(T7r, T7q);
}
{
V T4i, T4o, T6p, T6q;
T4i = VMUL(LDK(KP707106781), VSUB(Tt, Tj));
T4o = VSUB(T4k, T4n);
T4p = VSUB(T4i, T4o);
T5C = VADD(T4o, T4i);
T6p = VADD(T1, Ta);
T6q = VADD(T4k, T4n);
T6r = VSUB(T6p, T6q);
T8f = VADD(T6p, T6q);
}
}
{
V T2R, T2U, T6R, T2Z, T32, T6Q, T2I, T71, T2O, T72, T2P, T2V;
{
V T2Q, T2T, T2Y, T31;
T2Q = LD(&(x[WS(rs, 17)]), ms, &(x[WS(rs, 1)]));
T2R = VZMULJ(T1v, T2Q);
T2T = LD(&(x[WS(rs, 49)]), ms, &(x[WS(rs, 1)]));
T2U = VZMULJ(T2S, T2T);
T6R = VADD(T2R, T2U);
T2Y = LD(&(x[WS(rs, 1)]), ms, &(x[WS(rs, 1)]));
T2Z = VZMULJ(T2, T2Y);
T31 = LD(&(x[WS(rs, 33)]), ms, &(x[WS(rs, 1)]));
T32 = VZMULJ(T30, T31);
T6Q = VADD(T2Z, T32);
}
{
V T2E, T2H, T2D, T2G;
T2D = LD(&(x[WS(rs, 57)]), ms, &(x[WS(rs, 1)]));
T2E = VZMULJ(T2C, T2D);
T2G = LD(&(x[WS(rs, 25)]), ms, &(x[WS(rs, 1)]));
T2H = VZMULJ(T2F, T2G);
T2I = VSUB(T2E, T2H);
T71 = VADD(T2E, T2H);
}
{
V T2K, T2N, T2J, T2M;
T2J = LD(&(x[WS(rs, 9)]), ms, &(x[WS(rs, 1)]));
T2K = VZMULJ(T5, T2J);
T2M = LD(&(x[WS(rs, 41)]), ms, &(x[WS(rs, 1)]));
T2N = VZMULJ(T2L, T2M);
T2O = VSUB(T2K, T2N);
T72 = VADD(T2K, T2N);
}
T6S = VSUB(T6Q, T6R);
T73 = VSUB(T71, T72);
T2P = VMUL(LDK(KP707106781), VSUB(T2I, T2O));
T2V = VSUB(T2R, T2U);
T2W = VSUB(T2P, T2V);
T5p = VADD(T2V, T2P);
{
V T33, T34, T8m, T8n;
T33 = VSUB(T2Z, T32);
T34 = VMUL(LDK(KP707106781), VADD(T2O, T2I));
T35 = VADD(T33, T34);
T5m = VSUB(T33, T34);
T8m = VADD(T6Q, T6R);
T8n = VADD(T72, T71);
T8o = VADD(T8m, T8n);
T90 = VSUB(T8m, T8n);
}
}
{
V T3c, T3f, T77, T44, T48, T78, T3m, T7j, T3t, T7i, T3g, T3u;
{
V T3b, T3e, T43, T47;
T3b = LD(&(x[WS(rs, 63)]), ms, &(x[WS(rs, 1)]));
T3c = VZMULJ(Tm, T3b);
T3e = LD(&(x[WS(rs, 31)]), ms, &(x[WS(rs, 1)]));
T3f = VZMULJ(T3d, T3e);
T77 = VADD(T3c, T3f);
T43 = LD(&(x[WS(rs, 15)]), ms, &(x[WS(rs, 1)]));
T44 = VZMULJ(T42, T43);
T47 = LD(&(x[WS(rs, 47)]), ms, &(x[WS(rs, 1)]));
T48 = VZMULJ(T46, T47);
T78 = VADD(T44, T48);
}
{
V T3i, T3l, T3h, T3k;
T3h = LD(&(x[WS(rs, 7)]), ms, &(x[WS(rs, 1)]));
T3i = VZMULJ(Tl, T3h);
T3k = LD(&(x[WS(rs, 39)]), ms, &(x[WS(rs, 1)]));
T3l = VZMULJ(T3j, T3k);
T3m = VSUB(T3i, T3l);
T7j = VADD(T3i, T3l);
}
{
V T3p, T3s, T3o, T3r;
T3o = LD(&(x[WS(rs, 55)]), ms, &(x[WS(rs, 1)]));
T3p = VZMULJ(T3n, T3o);
T3r = LD(&(x[WS(rs, 23)]), ms, &(x[WS(rs, 1)]));
T3s = VZMULJ(T3q, T3r);
T3t = VSUB(T3p, T3s);
T7i = VADD(T3p, T3s);
}
T79 = VSUB(T77, T78);
T7k = VSUB(T7i, T7j);
T3g = VSUB(T3c, T3f);
T3u = VMUL(LDK(KP707106781), VADD(T3m, T3t));
T3v = VADD(T3g, T3u);
T5t = VSUB(T3g, T3u);
{
V T41, T49, T8t, T8u;
T41 = VMUL(LDK(KP707106781), VSUB(T3t, T3m));
T49 = VSUB(T44, T48);
T4a = VSUB(T41, T49);
T5w = VADD(T49, T41);
T8t = VADD(T77, T78);
T8u = VADD(T7j, T7i);
T8v = VADD(T8t, T8u);
T93 = VSUB(T8t, T8u);
}
}
{
V T1T, T1W, T6B, T20, T23, T6A, T1I, T6D, T1P, T6E, T6C, T6F;
{
V T1S, T1V, T1Z, T22;
T1S = LD(&(x[WS(rs, 18)]), ms, &(x[0]));
T1T = VZMULJ(T1R, T1S);
T1V = LD(&(x[WS(rs, 50)]), ms, &(x[0]));
T1W = VZMULJ(T1U, T1V);
T6B = VADD(T1T, T1W);
T1Z = LD(&(x[WS(rs, 2)]), ms, &(x[0]));
T20 = VZMULJ(Tk, T1Z);
T22 = LD(&(x[WS(rs, 34)]), ms, &(x[0]));
T23 = VZMULJ(T21, T22);
T6A = VADD(T20, T23);
}
{
V T1E, T1H, T1D, T1G;
T1D = LD(&(x[WS(rs, 58)]), ms, &(x[0]));
T1E = VZMULJ(T1C, T1D);
T1G = LD(&(x[WS(rs, 26)]), ms, &(x[0]));
T1H = VZMULJ(T1F, T1G);
T1I = VSUB(T1E, T1H);
T6D = VADD(T1E, T1H);
}
{
V T1K, T1O, T1J, T1N;
T1J = LD(&(x[WS(rs, 10)]), ms, &(x[0]));
T1K = VZMULJ(T1u, T1J);
T1N = LD(&(x[WS(rs, 42)]), ms, &(x[0]));
T1O = VZMULJ(T1M, T1N);
T1P = VSUB(T1K, T1O);
T6E = VADD(T1K, T1O);
}
T8F = VADD(T6A, T6B);
T8G = VADD(T6E, T6D);
T8W = VSUB(T8F, T8G);
T6C = VSUB(T6A, T6B);
T6F = VSUB(T6D, T6E);
T6G = VFMA(LDK(KP923879532), T6C, VMUL(LDK(KP382683432), T6F));
T7v = VFNMS(LDK(KP382683432), T6C, VMUL(LDK(KP923879532), T6F));
{
V T1Q, T1X, T24, T25;
T1Q = VMUL(LDK(KP707106781), VSUB(T1I, T1P));
T1X = VSUB(T1T, T1W);
T1Y = VSUB(T1Q, T1X);
T5f = VADD(T1X, T1Q);
T24 = VSUB(T20, T23);
T25 = VMUL(LDK(KP707106781), VADD(T1P, T1I));
T26 = VADD(T24, T25);
T5e = VSUB(T24, T25);
}
}
{
V T15, T18, T6H, T1t, T1y, T6I, T1g, T6L, T1n, T6K, T6J, T6M;
{
V T14, T17, T1s, T1x;
T14 = LD(&(x[WS(rs, 62)]), ms, &(x[0]));
T15 = VZMULJ(T13, T14);
T17 = LD(&(x[WS(rs, 30)]), ms, &(x[0]));
T18 = VZMULJ(T16, T17);
T6H = VADD(T15, T18);
T1s = LD(&(x[WS(rs, 14)]), ms, &(x[0]));
T1t = VZMULJ(T1r, T1s);
T1x = LD(&(x[WS(rs, 46)]), ms, &(x[0]));
T1y = VZMULJ(T1w, T1x);
T6I = VADD(T1t, T1y);
}
{
V T1c, T1f, T1b, T1e;
T1b = LD(&(x[WS(rs, 6)]), ms, &(x[0]));
T1c = VZMULJ(T1a, T1b);
T1e = LD(&(x[WS(rs, 38)]), ms, &(x[0]));
T1f = VZMULJ(T1d, T1e);
T1g = VSUB(T1c, T1f);
T6L = VADD(T1c, T1f);
}
{
V T1j, T1m, T1i, T1l;
T1i = LD(&(x[WS(rs, 54)]), ms, &(x[0]));
T1j = VZMULJ(T1h, T1i);
T1l = LD(&(x[WS(rs, 22)]), ms, &(x[0]));
T1m = VZMULJ(T1k, T1l);
T1n = VSUB(T1j, T1m);
T6K = VADD(T1j, T1m);
}
T8C = VADD(T6H, T6I);
T8D = VADD(T6L, T6K);
T8X = VSUB(T8C, T8D);
T6J = VSUB(T6H, T6I);
T6M = VSUB(T6K, T6L);
T6N = VFNMS(LDK(KP382683432), T6M, VMUL(LDK(KP923879532), T6J));
T7w = VFMA(LDK(KP382683432), T6J, VMUL(LDK(KP923879532), T6M));
{
V T19, T1o, T1q, T1z;
T19 = VSUB(T15, T18);
T1o = VMUL(LDK(KP707106781), VADD(T1g, T1n));
T1p = VADD(T19, T1o);
T5h = VSUB(T19, T1o);
T1q = VMUL(LDK(KP707106781), VSUB(T1n, T1g));
T1z = VSUB(T1t, T1y);
T1A = VSUB(T1q, T1z);
T5i = VADD(T1z, T1q);
}
}
{
V TB, T6s, TZ, T6w, TJ, T6t, TR, T6v, TK, T10;
{
V Tx, TA, Tw, Tz;
Tw = LD(&(x[WS(rs, 4)]), ms, &(x[0]));
Tx = VZMULJ(T4, Tw);
Tz = LD(&(x[WS(rs, 36)]), ms, &(x[0]));
TA = VZMULJ(Ty, Tz);
TB = VSUB(Tx, TA);
T6s = VADD(Tx, TA);
}
{
V TU, TY, TT, TX;
TT = LD(&(x[WS(rs, 12)]), ms, &(x[0]));
TU = VZMULJ(TS, TT);
TX = LD(&(x[WS(rs, 44)]), ms, &(x[0]));
TY = VZMULJ(TW, TX);
TZ = VSUB(TU, TY);
T6w = VADD(TU, TY);
}
{
V TE, TI, TD, TH;
TD = LD(&(x[WS(rs, 20)]), ms, &(x[0]));
TE = VZMULJ(TC, TD);
TH = LD(&(x[WS(rs, 52)]), ms, &(x[0]));
TI = VZMULJ(TG, TH);
TJ = VSUB(TE, TI);
T6t = VADD(TE, TI);
}
{
V TN, TQ, TM, TP;
TM = LD(&(x[WS(rs, 60)]), ms, &(x[0]));
TN = VZMULJ(TL, TM);
TP = LD(&(x[WS(rs, 28)]), ms, &(x[0]));
TQ = VZMULJ(TO, TP);
TR = VSUB(TN, TQ);
T6v = VADD(TN, TQ);
}
T8i = VADD(T6s, T6t);
T8j = VADD(T6v, T6w);
TK = VFNMS(LDK(KP382683432), TJ, VMUL(LDK(KP923879532), TB));
T10 = VFMA(LDK(KP923879532), TR, VMUL(LDK(KP382683432), TZ));
T11 = VADD(TK, T10);
T5D = VSUB(T10, TK);
{
V T4f, T4g, T6u, T6x;
T4f = VFNMS(LDK(KP923879532), TZ, VMUL(LDK(KP382683432), TR));
T4g = VFMA(LDK(KP382683432), TB, VMUL(LDK(KP923879532), TJ));
T4h = VSUB(T4f, T4g);
T5c = VADD(T4g, T4f);
T6u = VSUB(T6s, T6t);
T6x = VSUB(T6v, T6w);
T6y = VMUL(LDK(KP707106781), VADD(T6u, T6x));
T7t = VMUL(LDK(KP707106781), VSUB(T6x, T6u));
}
}
{
V T2g, T6W, T2z, T6U, T2m, T6X, T2t, T6T;
{
V T2c, T2f, T2b, T2e;
T2b = LD(&(x[WS(rs, 61)]), ms, &(x[WS(rs, 1)]));
T2c = VZMULJ(T2a, T2b);
T2e = LD(&(x[WS(rs, 29)]), ms, &(x[WS(rs, 1)]));
T2f = VZMULJ(T2d, T2e);
T2g = VSUB(T2c, T2f);
T6W = VADD(T2c, T2f);
}
{
V T2v, T2y, T2u, T2x;
T2u = LD(&(x[WS(rs, 21)]), ms, &(x[WS(rs, 1)]));
T2v = VZMULJ(T1L, T2u);
T2x = LD(&(x[WS(rs, 53)]), ms, &(x[WS(rs, 1)]));
T2y = VZMULJ(T2w, T2x);
T2z = VSUB(T2v, T2y);
T6U = VADD(T2v, T2y);
}
{
V T2i, T2l, T2h, T2k;
T2h = LD(&(x[WS(rs, 13)]), ms, &(x[WS(rs, 1)]));
T2i = VZMULJ(Tf, T2h);
T2k = LD(&(x[WS(rs, 45)]), ms, &(x[WS(rs, 1)]));
T2l = VZMULJ(T2j, T2k);
T2m = VSUB(T2i, T2l);
T6X = VADD(T2i, T2l);
}
{
V T2p, T2s, T2o, T2r;
T2o = LD(&(x[WS(rs, 5)]), ms, &(x[WS(rs, 1)]));
T2p = VZMULJ(T6, T2o);
T2r = LD(&(x[WS(rs, 37)]), ms, &(x[WS(rs, 1)]));
T2s = VZMULJ(T2q, T2r);
T2t = VSUB(T2p, T2s);
T6T = VADD(T2p, T2s);
}
{
V T2n, T2A, T8p, T8q;
T2n = VFNMS(LDK(KP923879532), T2m, VMUL(LDK(KP382683432), T2g));
T2A = VFMA(LDK(KP382683432), T2t, VMUL(LDK(KP923879532), T2z));
T2B = VSUB(T2n, T2A);
T5n = VADD(T2A, T2n);
T8p = VADD(T6T, T6U);
T8q = VADD(T6W, T6X);
T8r = VADD(T8p, T8q);
T91 = VSUB(T8q, T8p);
}
{
V T36, T37, T6V, T6Y;
T36 = VFNMS(LDK(KP382683432), T2z, VMUL(LDK(KP923879532), T2t));
T37 = VFMA(LDK(KP923879532), T2g, VMUL(LDK(KP382683432), T2m));
T38 = VADD(T36, T37);
T5q = VSUB(T37, T36);
T6V = VSUB(T6T, T6U);
T6Y = VSUB(T6W, T6X);
T6Z = VMUL(LDK(KP707106781), VADD(T6V, T6Y));
T74 = VMUL(LDK(KP707106781), VSUB(T6Y, T6V));
}
}
{
V T3B, T7a, T3U, T7e, T3H, T7b, T3O, T7d;
{
V T3x, T3A, T3w, T3z;
T3w = LD(&(x[WS(rs, 3)]), ms, &(x[WS(rs, 1)]));
T3x = VZMULJ(T3, T3w);
T3z = LD(&(x[WS(rs, 35)]), ms, &(x[WS(rs, 1)]));
T3A = VZMULJ(T3y, T3z);
T3B = VSUB(T3x, T3A);
T7a = VADD(T3x, T3A);
}
{
V T3Q, T3T, T3P, T3S;
T3P = LD(&(x[WS(rs, 11)]), ms, &(x[WS(rs, 1)]));
T3Q = VZMULJ(TF, T3P);
T3S = LD(&(x[WS(rs, 43)]), ms, &(x[WS(rs, 1)]));
T3T = VZMULJ(T3R, T3S);
T3U = VSUB(T3Q, T3T);
T7e = VADD(T3Q, T3T);
}
{
V T3D, T3G, T3C, T3F;
T3C = LD(&(x[WS(rs, 19)]), ms, &(x[WS(rs, 1)]));
T3D = VZMULJ(TV, T3C);
T3F = LD(&(x[WS(rs, 51)]), ms, &(x[WS(rs, 1)]));
T3G = VZMULJ(T3E, T3F);
T3H = VSUB(T3D, T3G);
T7b = VADD(T3D, T3G);
}
{
V T3L, T3N, T3K, T3M;
T3K = LD(&(x[WS(rs, 59)]), ms, &(x[WS(rs, 1)]));
T3L = VZMULJ(T3J, T3K);
T3M = LD(&(x[WS(rs, 27)]), ms, &(x[WS(rs, 1)]));
T3N = VZMULJ(T7, T3M);
T3O = VSUB(T3L, T3N);
T7d = VADD(T3L, T3N);
}
{
V T3I, T3V, T8w, T8x;
T3I = VFNMS(LDK(KP382683432), T3H, VMUL(LDK(KP923879532), T3B));
T3V = VFMA(LDK(KP923879532), T3O, VMUL(LDK(KP382683432), T3U));
T3W = VADD(T3I, T3V);
T5x = VSUB(T3V, T3I);
T8w = VADD(T7a, T7b);
T8x = VADD(T7d, T7e);
T8y = VADD(T8w, T8x);
T94 = VSUB(T8x, T8w);
}
{
V T3Y, T3Z, T7c, T7f;
T3Y = VFNMS(LDK(KP923879532), T3U, VMUL(LDK(KP382683432), T3O));
T3Z = VFMA(LDK(KP382683432), T3B, VMUL(LDK(KP923879532), T3H));
T40 = VSUB(T3Y, T3Z);
T5u = VADD(T3Z, T3Y);
T7c = VSUB(T7a, T7b);
T7f = VSUB(T7d, T7e);
T7g = VMUL(LDK(KP707106781), VADD(T7c, T7f));
T7l = VMUL(LDK(KP707106781), VSUB(T7f, T7c));
}
}
{
V T8l, T8N, T8S, T8U, T8A, T8J, T8I, T8O, T8P, T8T;
{
V T8h, T8k, T8Q, T8R;
T8h = VADD(T8f, T8g);
T8k = VADD(T8i, T8j);
T8l = VSUB(T8h, T8k);
T8N = VADD(T8h, T8k);
T8Q = VADD(T8o, T8r);
T8R = VADD(T8v, T8y);
T8S = VADD(T8Q, T8R);
T8U = VBYI(VSUB(T8R, T8Q));
}
{
V T8s, T8z, T8E, T8H;
T8s = VSUB(T8o, T8r);
T8z = VSUB(T8v, T8y);
T8A = VMUL(LDK(KP707106781), VADD(T8s, T8z));
T8J = VMUL(LDK(KP707106781), VSUB(T8z, T8s));
T8E = VADD(T8C, T8D);
T8H = VADD(T8F, T8G);
T8I = VSUB(T8E, T8H);
T8O = VADD(T8H, T8E);
}
T8P = VADD(T8N, T8O);
ST(&(x[WS(rs, 32)]),VSUB(T8P, T8S),ms,&(x[0]));
ST(&(x[0]),VADD(T8P, T8S),ms,&(x[0]));
T8T = VSUB(T8N, T8O);
ST(&(x[WS(rs, 48)]),VSUB(T8T, T8U),ms,&(x[0]));
ST(&(x[WS(rs, 16)]),VADD(T8T, T8U),ms,&(x[0]));
{
V T8B, T8K, T8L, T8M;
T8B = VADD(T8l, T8A);
T8K = VBYI(VADD(T8I, T8J));
ST(&(x[WS(rs, 56)]),VSUB(T8B, T8K),ms,&(x[0]));
ST(&(x[WS(rs, 8)]),VADD(T8B, T8K),ms,&(x[0]));
T8L = VSUB(T8l, T8A);
T8M = VBYI(VSUB(T8J, T8I));
ST(&(x[WS(rs, 40)]),VSUB(T8L, T8M),ms,&(x[0]));
ST(&(x[WS(rs, 24)]),VADD(T8L, T8M),ms,&(x[0]));
}
}
{
V T8Z, T9k, T9d, T9l, T96, T9h, T9a, T9i;
{
V T8V, T8Y, T9b, T9c;
T8V = VSUB(T8f, T8g);
T8Y = VMUL(LDK(KP707106781), VADD(T8W, T8X));
T8Z = VADD(T8V, T8Y);
T9k = VSUB(T8V, T8Y);
T9b = VFNMS(LDK(KP382683432), T90, VMUL(LDK(KP923879532), T91));
T9c = VFMA(LDK(KP382683432), T93, VMUL(LDK(KP923879532), T94));
T9d = VADD(T9b, T9c);
T9l = VSUB(T9c, T9b);
}
{
V T92, T95, T98, T99;
T92 = VFMA(LDK(KP923879532), T90, VMUL(LDK(KP382683432), T91));
T95 = VFNMS(LDK(KP382683432), T94, VMUL(LDK(KP923879532), T93));
T96 = VADD(T92, T95);
T9h = VSUB(T95, T92);
T98 = VSUB(T8j, T8i);
T99 = VMUL(LDK(KP707106781), VSUB(T8X, T8W));
T9a = VADD(T98, T99);
T9i = VSUB(T99, T98);
}
{
V T97, T9e, T9n, T9o;
T97 = VADD(T8Z, T96);
T9e = VBYI(VADD(T9a, T9d));
ST(&(x[WS(rs, 60)]),VSUB(T97, T9e),ms,&(x[0]));
ST(&(x[WS(rs, 4)]),VADD(T97, T9e),ms,&(x[0]));
T9n = VBYI(VADD(T9i, T9h));
T9o = VADD(T9k, T9l);
ST(&(x[WS(rs, 12)]),VADD(T9n, T9o),ms,&(x[0]));
ST(&(x[WS(rs, 52)]),VSUB(T9o, T9n),ms,&(x[0]));
}
{
V T9f, T9g, T9j, T9m;
T9f = VSUB(T8Z, T96);
T9g = VBYI(VSUB(T9d, T9a));
ST(&(x[WS(rs, 36)]),VSUB(T9f, T9g),ms,&(x[0]));
ST(&(x[WS(rs, 28)]),VADD(T9f, T9g),ms,&(x[0]));
T9j = VBYI(VSUB(T9h, T9i));
T9m = VSUB(T9k, T9l);
ST(&(x[WS(rs, 20)]),VADD(T9j, T9m),ms,&(x[0]));
ST(&(x[WS(rs, 44)]),VSUB(T9m, T9j),ms,&(x[0]));
}
}
{
V T6P, T7I, T7y, T7G, T7o, T7J, T7B, T7F;
{
V T6z, T6O, T7u, T7x;
T6z = VADD(T6r, T6y);
T6O = VADD(T6G, T6N);
T6P = VADD(T6z, T6O);
T7I = VSUB(T6z, T6O);
T7u = VADD(T7s, T7t);
T7x = VADD(T7v, T7w);
T7y = VADD(T7u, T7x);
T7G = VSUB(T7x, T7u);
{
V T76, T7z, T7n, T7A;
{
V T70, T75, T7h, T7m;
T70 = VADD(T6S, T6Z);
T75 = VADD(T73, T74);
T76 = VFMA(LDK(KP980785280), T70, VMUL(LDK(KP195090322), T75));
T7z = VFNMS(LDK(KP195090322), T70, VMUL(LDK(KP980785280), T75));
T7h = VADD(T79, T7g);
T7m = VADD(T7k, T7l);
T7n = VFNMS(LDK(KP195090322), T7m, VMUL(LDK(KP980785280), T7h));
T7A = VFMA(LDK(KP195090322), T7h, VMUL(LDK(KP980785280), T7m));
}
T7o = VADD(T76, T7n);
T7J = VSUB(T7A, T7z);
T7B = VADD(T7z, T7A);
T7F = VSUB(T7n, T76);
}
}
{
V T7p, T7C, T7L, T7M;
T7p = VADD(T6P, T7o);
T7C = VBYI(VADD(T7y, T7B));
ST(&(x[WS(rs, 62)]),VSUB(T7p, T7C),ms,&(x[0]));
ST(&(x[WS(rs, 2)]),VADD(T7p, T7C),ms,&(x[0]));
T7L = VBYI(VADD(T7G, T7F));
T7M = VADD(T7I, T7J);
ST(&(x[WS(rs, 14)]),VADD(T7L, T7M),ms,&(x[0]));
ST(&(x[WS(rs, 50)]),VSUB(T7M, T7L),ms,&(x[0]));
}
{
V T7D, T7E, T7H, T7K;
T7D = VSUB(T6P, T7o);
T7E = VBYI(VSUB(T7B, T7y));
ST(&(x[WS(rs, 34)]),VSUB(T7D, T7E),ms,&(x[0]));
ST(&(x[WS(rs, 30)]),VADD(T7D, T7E),ms,&(x[0]));
T7H = VBYI(VSUB(T7F, T7G));
T7K = VSUB(T7I, T7J);
ST(&(x[WS(rs, 18)]),VADD(T7H, T7K),ms,&(x[0]));
ST(&(x[WS(rs, 46)]),VSUB(T7K, T7H),ms,&(x[0]));
}
}
{
V T7P, T8a, T80, T88, T7W, T8b, T83, T87;
{
V T7N, T7O, T7Y, T7Z;
T7N = VSUB(T6r, T6y);
T7O = VSUB(T7w, T7v);
T7P = VADD(T7N, T7O);
T8a = VSUB(T7N, T7O);
T7Y = VSUB(T7t, T7s);
T7Z = VSUB(T6N, T6G);
T80 = VADD(T7Y, T7Z);
T88 = VSUB(T7Z, T7Y);
{
V T7S, T81, T7V, T82;
{
V T7Q, T7R, T7T, T7U;
T7Q = VSUB(T6S, T6Z);
T7R = VSUB(T74, T73);
T7S = VFMA(LDK(KP831469612), T7Q, VMUL(LDK(KP555570233), T7R));
T81 = VFNMS(LDK(KP555570233), T7Q, VMUL(LDK(KP831469612), T7R));
T7T = VSUB(T79, T7g);
T7U = VSUB(T7l, T7k);
T7V = VFNMS(LDK(KP555570233), T7U, VMUL(LDK(KP831469612), T7T));
T82 = VFMA(LDK(KP555570233), T7T, VMUL(LDK(KP831469612), T7U));
}
T7W = VADD(T7S, T7V);
T8b = VSUB(T82, T81);
T83 = VADD(T81, T82);
T87 = VSUB(T7V, T7S);
}
}
{
V T7X, T84, T8d, T8e;
T7X = VADD(T7P, T7W);
T84 = VBYI(VADD(T80, T83));
ST(&(x[WS(rs, 58)]),VSUB(T7X, T84),ms,&(x[0]));
ST(&(x[WS(rs, 6)]),VADD(T7X, T84),ms,&(x[0]));
T8d = VBYI(VADD(T88, T87));
T8e = VADD(T8a, T8b);
ST(&(x[WS(rs, 10)]),VADD(T8d, T8e),ms,&(x[0]));
ST(&(x[WS(rs, 54)]),VSUB(T8e, T8d),ms,&(x[0]));
}
{
V T85, T86, T89, T8c;
T85 = VSUB(T7P, T7W);
T86 = VBYI(VSUB(T83, T80));
ST(&(x[WS(rs, 38)]),VSUB(T85, T86),ms,&(x[0]));
ST(&(x[WS(rs, 26)]),VADD(T85, T86),ms,&(x[0]));
T89 = VBYI(VSUB(T87, T88));
T8c = VSUB(T8a, T8b);
ST(&(x[WS(rs, 22)]),VADD(T89, T8c),ms,&(x[0]));
ST(&(x[WS(rs, 42)]),VSUB(T8c, T89),ms,&(x[0]));
}
}
{
V T5l, T6i, T5S, T6a, T5I, T6k, T5Q, T5Z, T5A, T5T, T5L, T5P, T66, T6l, T6d;
V T6h;
{
V T5d, T68, T5k, T69, T5g, T5j;
T5d = VADD(T5b, T5c);
T68 = VSUB(T5D, T5C);
T5g = VFMA(LDK(KP831469612), T5e, VMUL(LDK(KP555570233), T5f));
T5j = VFNMS(LDK(KP555570233), T5i, VMUL(LDK(KP831469612), T5h));
T5k = VADD(T5g, T5j);
T69 = VSUB(T5j, T5g);
T5l = VADD(T5d, T5k);
T6i = VSUB(T69, T68);
T5S = VSUB(T5d, T5k);
T6a = VADD(T68, T69);
}
{
V T5E, T5X, T5H, T5Y, T5F, T5G;
T5E = VADD(T5C, T5D);
T5X = VSUB(T5b, T5c);
T5F = VFNMS(LDK(KP555570233), T5e, VMUL(LDK(KP831469612), T5f));
T5G = VFMA(LDK(KP555570233), T5h, VMUL(LDK(KP831469612), T5i));
T5H = VADD(T5F, T5G);
T5Y = VSUB(T5G, T5F);
T5I = VADD(T5E, T5H);
T6k = VSUB(T5X, T5Y);
T5Q = VSUB(T5H, T5E);
T5Z = VADD(T5X, T5Y);
}
{
V T5s, T5J, T5z, T5K;
{
V T5o, T5r, T5v, T5y;
T5o = VADD(T5m, T5n);
T5r = VADD(T5p, T5q);
T5s = VFMA(LDK(KP956940335), T5o, VMUL(LDK(KP290284677), T5r));
T5J = VFNMS(LDK(KP290284677), T5o, VMUL(LDK(KP956940335), T5r));
T5v = VADD(T5t, T5u);
T5y = VADD(T5w, T5x);
T5z = VFNMS(LDK(KP290284677), T5y, VMUL(LDK(KP956940335), T5v));
T5K = VFMA(LDK(KP290284677), T5v, VMUL(LDK(KP956940335), T5y));
}
T5A = VADD(T5s, T5z);
T5T = VSUB(T5K, T5J);
T5L = VADD(T5J, T5K);
T5P = VSUB(T5z, T5s);
}
{
V T62, T6b, T65, T6c;
{
V T60, T61, T63, T64;
T60 = VSUB(T5m, T5n);
T61 = VSUB(T5q, T5p);
T62 = VFMA(LDK(KP881921264), T60, VMUL(LDK(KP471396736), T61));
T6b = VFNMS(LDK(KP471396736), T60, VMUL(LDK(KP881921264), T61));
T63 = VSUB(T5t, T5u);
T64 = VSUB(T5x, T5w);
T65 = VFNMS(LDK(KP471396736), T64, VMUL(LDK(KP881921264), T63));
T6c = VFMA(LDK(KP471396736), T63, VMUL(LDK(KP881921264), T64));
}
T66 = VADD(T62, T65);
T6l = VSUB(T6c, T6b);
T6d = VADD(T6b, T6c);
T6h = VSUB(T65, T62);
}
{
V T5B, T5M, T6j, T6m;
T5B = VADD(T5l, T5A);
T5M = VBYI(VADD(T5I, T5L));
ST(&(x[WS(rs, 61)]),VSUB(T5B, T5M),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 3)]),VADD(T5B, T5M),ms,&(x[WS(rs, 1)]));
T6j = VBYI(VSUB(T6h, T6i));
T6m = VSUB(T6k, T6l);
ST(&(x[WS(rs, 21)]),VADD(T6j, T6m),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 43)]),VSUB(T6m, T6j),ms,&(x[WS(rs, 1)]));
}
{
V T6n, T6o, T5N, T5O;
T6n = VBYI(VADD(T6i, T6h));
T6o = VADD(T6k, T6l);
ST(&(x[WS(rs, 11)]),VADD(T6n, T6o),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 53)]),VSUB(T6o, T6n),ms,&(x[WS(rs, 1)]));
T5N = VSUB(T5l, T5A);
T5O = VBYI(VSUB(T5L, T5I));
ST(&(x[WS(rs, 35)]),VSUB(T5N, T5O),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 29)]),VADD(T5N, T5O),ms,&(x[WS(rs, 1)]));
}
{
V T5R, T5U, T67, T6e;
T5R = VBYI(VSUB(T5P, T5Q));
T5U = VSUB(T5S, T5T);
ST(&(x[WS(rs, 19)]),VADD(T5R, T5U),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 45)]),VSUB(T5U, T5R),ms,&(x[WS(rs, 1)]));
T67 = VADD(T5Z, T66);
T6e = VBYI(VADD(T6a, T6d));
ST(&(x[WS(rs, 59)]),VSUB(T67, T6e),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 5)]),VADD(T67, T6e),ms,&(x[WS(rs, 1)]));
}
{
V T6f, T6g, T5V, T5W;
T6f = VSUB(T5Z, T66);
T6g = VBYI(VSUB(T6d, T6a));
ST(&(x[WS(rs, 37)]),VSUB(T6f, T6g),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 27)]),VADD(T6f, T6g),ms,&(x[WS(rs, 1)]));
T5V = VBYI(VADD(T5Q, T5P));
T5W = VADD(T5S, T5T);
ST(&(x[WS(rs, 13)]),VADD(T5V, T5W),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 51)]),VSUB(T5W, T5V),ms,&(x[WS(rs, 1)]));
}
}
{
V T29, T54, T4E, T4W, T4u, T56, T4C, T4L, T4d, T4F, T4x, T4B, T4S, T57, T4Z;
V T53;
{
V T12, T4U, T28, T4V, T1B, T27;
T12 = VSUB(Tv, T11);
T4U = VADD(T4p, T4h);
T1B = VFMA(LDK(KP195090322), T1p, VMUL(LDK(KP980785280), T1A));
T27 = VFNMS(LDK(KP195090322), T26, VMUL(LDK(KP980785280), T1Y));
T28 = VSUB(T1B, T27);
T4V = VADD(T27, T1B);
T29 = VADD(T12, T28);
T54 = VSUB(T4V, T4U);
T4E = VSUB(T12, T28);
T4W = VADD(T4U, T4V);
}
{
V T4q, T4J, T4t, T4K, T4r, T4s;
T4q = VSUB(T4h, T4p);
T4J = VADD(Tv, T11);
T4r = VFNMS(LDK(KP195090322), T1A, VMUL(LDK(KP980785280), T1p));
T4s = VFMA(LDK(KP980785280), T26, VMUL(LDK(KP195090322), T1Y));
T4t = VSUB(T4r, T4s);
T4K = VADD(T4s, T4r);
T4u = VADD(T4q, T4t);
T56 = VSUB(T4J, T4K);
T4C = VSUB(T4t, T4q);
T4L = VADD(T4J, T4K);
}
{
V T3a, T4v, T4c, T4w;
{
V T2X, T39, T3X, T4b;
T2X = VSUB(T2B, T2W);
T39 = VSUB(T35, T38);
T3a = VFMA(LDK(KP634393284), T2X, VMUL(LDK(KP773010453), T39));
T4v = VFNMS(LDK(KP634393284), T39, VMUL(LDK(KP773010453), T2X));
T3X = VSUB(T3v, T3W);
T4b = VSUB(T40, T4a);
T4c = VFNMS(LDK(KP634393284), T4b, VMUL(LDK(KP773010453), T3X));
T4w = VFMA(LDK(KP773010453), T4b, VMUL(LDK(KP634393284), T3X));
}
T4d = VADD(T3a, T4c);
T4F = VSUB(T4w, T4v);
T4x = VADD(T4v, T4w);
T4B = VSUB(T4c, T3a);
}
{
V T4O, T4X, T4R, T4Y;
{
V T4M, T4N, T4P, T4Q;
T4M = VADD(T2W, T2B);
T4N = VADD(T35, T38);
T4O = VFMA(LDK(KP098017140), T4M, VMUL(LDK(KP995184726), T4N));
T4X = VFNMS(LDK(KP098017140), T4N, VMUL(LDK(KP995184726), T4M));
T4P = VADD(T3v, T3W);
T4Q = VADD(T4a, T40);
T4R = VFNMS(LDK(KP098017140), T4Q, VMUL(LDK(KP995184726), T4P));
T4Y = VFMA(LDK(KP995184726), T4Q, VMUL(LDK(KP098017140), T4P));
}
T4S = VADD(T4O, T4R);
T57 = VSUB(T4Y, T4X);
T4Z = VADD(T4X, T4Y);
T53 = VSUB(T4R, T4O);
}
{
V T4e, T4y, T55, T58;
T4e = VADD(T29, T4d);
T4y = VBYI(VADD(T4u, T4x));
ST(&(x[WS(rs, 57)]),VSUB(T4e, T4y),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 7)]),VADD(T4e, T4y),ms,&(x[WS(rs, 1)]));
T55 = VBYI(VSUB(T53, T54));
T58 = VSUB(T56, T57);
ST(&(x[WS(rs, 17)]),VADD(T55, T58),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 47)]),VSUB(T58, T55),ms,&(x[WS(rs, 1)]));
}
{
V T59, T5a, T4z, T4A;
T59 = VBYI(VADD(T54, T53));
T5a = VADD(T56, T57);
ST(&(x[WS(rs, 15)]),VADD(T59, T5a),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 49)]),VSUB(T5a, T59),ms,&(x[WS(rs, 1)]));
T4z = VSUB(T29, T4d);
T4A = VBYI(VSUB(T4x, T4u));
ST(&(x[WS(rs, 39)]),VSUB(T4z, T4A),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 25)]),VADD(T4z, T4A),ms,&(x[WS(rs, 1)]));
}
{
V T4D, T4G, T4T, T50;
T4D = VBYI(VSUB(T4B, T4C));
T4G = VSUB(T4E, T4F);
ST(&(x[WS(rs, 23)]),VADD(T4D, T4G),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 41)]),VSUB(T4G, T4D),ms,&(x[WS(rs, 1)]));
T4T = VADD(T4L, T4S);
T50 = VBYI(VADD(T4W, T4Z));
ST(&(x[WS(rs, 63)]),VSUB(T4T, T50),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 1)]),VADD(T4T, T50),ms,&(x[WS(rs, 1)]));
}
{
V T51, T52, T4H, T4I;
T51 = VSUB(T4L, T4S);
T52 = VBYI(VSUB(T4Z, T4W));
ST(&(x[WS(rs, 33)]),VSUB(T51, T52),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 31)]),VADD(T51, T52),ms,&(x[WS(rs, 1)]));
T4H = VBYI(VADD(T4C, T4B));
T4I = VADD(T4E, T4F);
ST(&(x[WS(rs, 9)]),VADD(T4H, T4I),ms,&(x[WS(rs, 1)]));
ST(&(x[WS(rs, 55)]),VSUB(T4I, T4H),ms,&(x[WS(rs, 1)]));
}
}
}
}
}
VLEAVE();}


static const tw_instr twinstr[] = {
VTW(0,1),
VTW(0,3),
VTW(0,9),
VTW(0,27),
VTW(0,63),
{TW_NEXT, VL, 0}};

static const ct_desc desc = {64, XSIMD_STRING("t3fv_64"), twinstr, &GENUS, { 525, 314, 52, 0 }, 0, 0, 0};

void XSIMD(codelet_t3fv_64)(planner *p)
{
X(kdft_dit_register)(p, t3fv_64, &desc);
}
#endif
